- packages/perspective/src/cpp/main.cpp
- packages/perspective/test/js/updates.js
Use table api to prepare pkey and op columns for insertion into a gnode. This simplifies creation of a t_table from user data.
> Refactor pkey/op creation for tables

- README.md
Just cloned and installed, and `npm install` seems to already run `lerna bootstrap --hoist`
```
:~$ git clone git@github.com:loicbourgois/perspective.git
Cloning into 'perspective'...
remote: Counting objects: 1692, done.
remote: Compressing objects: 100% (94/94), done.
remote: Total 1692 (delta 63), reused 112 (delta 49), pack-reused 1543
Receiving objects: 100% (1692/1692), 8.36 MiB | 1.31 MiB/s, done.
Resolving deltas: 100% (871/871), done.
:~$ cd perspective/
:~/perspective$ npm install
> undefined postinstall /home/user/perspective
> lerna bootstrap --hoist
lerna info version 2.8.0
lerna info Bootstrapping 7 packages
lerna info lifecycle preinstall
lerna info Installing external dependencies
lerna info hoist Installing hoisted dependencies into root
lerna info hoist Pruning hoisted …
```
> Remove seemingly unnecessary install step in README.md

- packages/perspective-common/index.js
Hi there, thank you for publishing such a great project! I've just been getting a demo up and running using Visual Studio 2017 (using standard VS templates). By default, the VS/webpack toolchain will append a version hash query string to its script bundle references. e.g:
`http://localhost:59090/dist/main.js?v=hyw4nPT-JXNYaAsGUUqAfkThIaWT7qch0FVyfgwK9zg`
The ScriptPath object purposefully throws an exception in order to extract the script path from the stack trace. A regular expression is used to extract the path components. The expression does not expect a query string in the script path.
In my particular case, the stack trace string with the query string on the script path looks like this: 
```
at Object.module.exports (http://localhost:59090/dist/main.js?v=0gN5LBVFBXS_KkM6Si37YaPTqhTdNs …
```
> Fixes ScriptPath for script paths with query strings

- packages/perspective-jupyterlab/src/ts/index.ts
- usable from any comm-connection assuming it implements the correct connection string/api
- comm://\<jupyter session id\>/\<applicationname\>/\<channel id\>
> removing lantern dependency

- packages/perspective-viewer-highcharts/package.json
- packages/perspective-viewer-highcharts/src/js/heatmap.js
Added tests and fixed overlap regression with bubble charts, as it does not seem these are in /modules yet.
> Refactored Highcharts imports to use heatmap module from base package.

- packages/perspective/package.json
- packages/perspective/src/cpp/main.cpp
- packages/perspective/src/js/perspective.js
Continuing from #38, this PR includes the following changes:
- implements Arrow column reflection as an Arrow `TypeVisitor`
- updates `main.cpp` to reflect Arrow 0.3.0's internal API changes
I marked this PR as WIP until I can get all the arrow tests passing. Compiling with `PSP_DEBUG=1`, this is the stack trace of the failures:
```
● perspective.js › ASMJS › Constructors › Arrow constructor
TypeError: Cannot read property '0' of undefined
at __emval_get_property (build/webpack:/build/wasm_sync/psp.js:4947:1)
at dynCall_iii (wasm-function[4691]:17)
at invoke_iii (build/webpack:/build/wasm_sync/psp.js:5612:1)
at __ZNK10emscripten3valixIiEES0_RKT_ (wasm-function[239]:69)
at __ZN5arrow14fill_col_validEN10emscripten3valENSt3__210shared_ptrIN11perspective8t_columnEEE (wasm-function[238]:93)
at …
```
> [WIP]: update to apache-arrow@0.3.0

- packages/perspective/src/cpp/main.cpp
- packages/perspective/src/js/perspective.js
- packages/perspective/src/js/perspective.parallel.js
- packages/perspective/test/js/updates.js
Adds a 'remove' command, which takes a list of primary keys, of the type of the column specified by the 'index' attribute., to remove from a `perspective.table`.  Fixed #56  (delete method name is already taken and deletes the component itself).
> Added 'remove' command to perspective.table

- .gitignore
Small DX improvement if you have to copy boost headers into the project.
> Ignore boost in perspective cpp

- packages/perspective-viewer-highcharts/src/js/config.js
The UX/API around this is due for a refresh, but in the meantime it makes sense (IMHO) that stacked area charts are more useful than non-stacked area charts, at least across column pivots.
Fixes #89
> Made y_area charts stacked by default

- packages/perspective-jupyterlab/README.md
- packages/perspective-jupyterlab/package.json
- packages/perspective-jupyterlab/src/config/plugin.config.js
- packages/perspective-jupyterlab/src/css/index.css
- packages/perspective-jupyterlab/src/js/embed.js
- packages/perspective-jupyterlab/src/ts/index.ts
- packages/perspective/src/js/perspective.parallel.js
Builds a single fat build of Perspective viewer, plugins, worker and WebAssembly payload, for easier embedding in Jupyter-lab.
> Jupyter embedded mode

- packages/perspective-viewer/src/less/default.less
- packages/perspective-viewer/src/less/material.dark.less
- packages/perspective-viewer/src/less/material.less
- packages/perspective-viewer/src/less/variables.less
- split out common colors & fonts into variables.less
- restructure and refactor material.less & material.dark.less for readability and reduction of duplicate rule declaration.
> Refactor Material Theme

- packages/perspective/src/js/perspective.js
- packages/perspective/test/js/constructors.js
- packages/perspective/test/js/updates.js
Added test case for construction of a table and updating a table in column oriented form (as described in docs). Add fix for issue of list of names and types being appended to even if they are already populated.
> Add tests and fix for regressed column update.

- packages/perspective-viewer/src/js/view.js
Fixing issue when the filters attribute of the perspective-viewer gets incorrectly set when multiple filters are set per column.
> Fixing filters when setting multiple filters per column

- packages/perspective/src/js/perspective.js
- packages/perspective/test/js/updates.js
Fixed partial updates via column-oriented JSON.  Updated PR of #205, with a few additional memory cleanup fixes and spurious merge commits removed.
> Column oriented partial update

- packages/perspective/src/cpp/main.cpp
- packages/perspective/src/js/defaults.js
- packages/perspective/src/js/perspective.js
- packages/perspective/test/js/pivots.js
Separating LAST and LAST_VALUE aggregates in JS mapping
Renaming first/last to be first/last by index for clarity
Provide sensible default implementation sorting by pkey
Added tests
> First & Last by Index Aggregates

- packages/perspective/src/cpp/gnode_state.cpp
> Simpler implementation of aggregate fix

- .travis.yml
- package.json
- packages/perspective-viewer-hypergrid/test/results/results.json
- packages/perspective-viewer/src/js/view.js
- packages/perspective/src/js/view_formatters.js
- packages/perspective/test/js/pivots.js
- packages/perspective/test/js/updates.js
Fixed issue in column-oriented JSON output, when only a column pivot is applied, which caused additional rows in the output.
> Fixed column-oriented output with column-only pivot

- packages/perspective-examples/src/html/streaming.html
- packages/perspective-viewer/src/js/view.js
- packages/perspective/src/cpp/main.cpp
- packages/perspective/src/js/perspective.js
- packages/perspective/test/js/updates.js
Added `limit` option to the `table` constructor, to limit the total number of rows on non-indexed tables.
> Limit tables

- packages/perspective/src/cpp/base.cpp
- packages/perspective/src/cpp/filter.cpp
- packages/perspective/src/cpp/main.cpp
- packages/perspective/src/include/perspective/base.h
- packages/perspective/src/include/perspective/build_filter.h
- packages/perspective/src/include/perspective/filter.h
- packages/perspective/src/js/perspective.js
- packages/perspective/test/js/filters.js
For columns with lots of possible string values, 'not in' can be more efficient than an 'in' filter with all the other values.
> Add 'not in' filter operation

- docs/perspective-viewer.md
- docs/perspective.md
- packages/perspective-viewer-highcharts/package.json
- packages/perspective-viewer-highcharts/src/js/draw.js
- packages/perspective-viewer-hypergrid/src/js/hypergrid.js
- packages/perspective-viewer-hypergrid/src/less/hypergrid.less
- packages/perspective-viewer/README.md
- packages/perspective/README.md
- packages/perspective/src/js/api.js
- packages/perspective/src/js/defaults.js
- packages/perspective/src/js/perspective.js
- packages/perspective/test/js/constructors.js
- src/cpp/main.cpp
Create C++/JS API to return view columns as a `TypedArray` for faster consumption and transferable usage.
> Expose view columns as TypedArrays

- packages/perspective-viewer-highcharts/src/js/draw.js
- packages/perspective-viewer/src/js/view.js
Replace `_column_view()`, a method with far too many delegated responsibilities and code paths, with a series of semantically named functions that read DOM state of the viewer.  Additionally, replace all usages of `Array.prototype.slice.call()` with `_get_view_dom_columns()`, which returns DOM view columns in an array.
> Replace _column_view with semantically named methods

- packages/perspective-viewer-highcharts/package.json
- packages/perspective-viewer-hypergrid/package.json
- packages/perspective-viewer/package.json
- packages/perspective-viewer/src/config/view.config.js
- packages/perspective/package.json
- packages/perspective/src/js/perspective.asmjs.js
Moved bable-polyfill out of transform-runtime plugin to avoid a [webpack integration bug.](https://github.com/webpack/webpack/issues/3974#issuecomment-369260590)
> Moved babel-polyfill to avoid webpack/babel bug

- examples/simple/citibike.html
- examples/simple/superstore-arrow.html
- packages/perspective-viewer/src/html/view.html
- packages/perspective-viewer/src/js/view.js
- packages/perspective-viewer/src/js/view/CancelTask.js
- packages/perspective-viewer/src/js/view/ViewPrivate.js
- packages/perspective-viewer/src/js/view/dom.js
- packages/perspective-viewer/src/js/view/renderers.js
- Refactor out DOM manipulation methods
- Refactor out CancelTask
- Add `toggleConfig()` on `view.js` as a public API method for programmatically interacting with the viewer, thus reducing dependency on internal `_toggle_config`.
- Reorder ViewPrivate a little more semantically, with getters at the top followed by update methods. Grouped methods with similar logic/interdependency together.
> Reorganize ViewPrivate

- docs/installation.md
It looks like you need to load perspective.js in order to instantiate the 'engine':
```
const worker = perspective.worker();
```
> docs: update installation guide

- packages/perspective/src/js/parse_data.js
- packages/perspective/src/js/perspective.js
- scripts/CMakeLists.txt
- src/cpp/main.cpp
- Reduce the number of parameters to `make_table` in cpp
- Add `--source-map-base` for emcc, should kick in when source map generation for wasm is fixed
- Refactor out repetitive lines of code associated with `make_table`
> Refactor make_table

- packages/perspective-viewer-hypergrid/src/js/hypergrid.js
- packages/perspective-viewer/src/js/viewer.js
- packages/perspective-viewer/src/js/viewer/cancel_task.js
- packages/perspective-viewer/src/js/viewer/perspective_element.js
- packages/perspective-viewer/test/js/computed_columns.spec.js
- packages/perspective-viewer/test/js/leaks.spec.js
- packages/perspective-viewer/test/results/results.json
- packages/perspective/src/js/api.js
- packages/perspective/src/js/perspective.js
Cleaned up handler refereneces to all `delete()`d viewers.
> Viewer memory leak on delete()

- package.json
- packages/perspective-viewer-highcharts/src/less/highcharts.less
- packages/perspective-viewer/src/less/default.less
- packages/perspective-viewer/src/themes/material.less
Fixes theming inconsistencies with the Material themes
> Material fixes

- .travis.yml
- docs/development.md
- package.json
- packages/perspective-viewer-highcharts/test/js/axis_tests.js
- packages/perspective-viewer-highcharts/test/js/bar.spec.js
- packages/perspective-viewer-highcharts/test/js/heatmap.spec.js
- packages/perspective-viewer-highcharts/test/js/line.spec.js
- packages/perspective-viewer-highcharts/test/js/scatter.spec.js
- packages/perspective-viewer-highcharts/test/js/treemap.spec.js
- packages/perspective-viewer-hypergrid/package.json
- packages/perspective-viewer-hypergrid/src/js/PerspectiveDataModel.js
- packages/perspective-viewer-hypergrid/src/js/hypergrid.js
- packages/perspective-viewer-hypergrid/src/js/perspective-plugin.js
- packages/perspective-viewer-hypergrid/test/js/regressions.spec.js
- packages/perspective-viewer-hypergrid/test/js/superstore.spec.js
- packages/perspective-viewer/package.json
- packages/perspective-viewer/test/js/computed_columns.spec.js
- packages/perspective-viewer/test/js/leaks.spec.js
- packages/perspective-viewer/test/js/regressions.spec.js
- packages/perspective-viewer/test/js/responsive_tests.js
- packages/perspective-viewer/test/js/superstore.spec.js
- packages/perspective-viewer/test/js/utils.js
- packages/perspective/package.json
- packages/perspective/src/js/perspective.js
Further parallelize Puppeteer test suite by reusing the `page` object between tests, and allow `jest` to run all package tests in parallel.
> Parallel tests

- packages/perspective-jupyterlab/package.json
- packages/perspective-jupyterlab/src/config/mimerenderer.config.js
- packages/perspective-jupyterlab/src/config/plugin.config.js
- packages/perspective-jupyterlab/tsconfig.json
`ipywidgets` embedding expects the output to be dist:
https://github.com/jupyter-widgets/ipywidgets/blob/master/packages/html-manager/src/libembed-amd.ts#L46
> Build into dist, plays nicer with ipywidgets

- packages/perspective/test/js/constructors.js
- src/cpp/main.cpp
Fixed issue which inferred a type `"float"` when given a schema-less JS column of all empty strings.
> Empty string column type inference fix

- packages/perspective/test/js/constructors.js
- packages/perspective/test/js/filters.js
- packages/perspective/test/js/pivots.js
- packages/perspective/test/js/updates.js
- scripts/test.js
- Add the following flags to the test script:
- `--bail`: quits after the first test suite failure
- `--debug`: preserves all console statements
- Make order of `expect().toEqual()` in Perspective.js tests consistent.
> Test quality-of-life updates

- python/README.md
Not sure where this should go, for now i've just put it in the `python` folder
> adding readme for python

- packages/perspective/test/js/constructors.js
- src/cpp/main.cpp
- Fix issue #368 in data parser
- Use `std::min` instead of embind to JS Math module
> Correctly type parse numbers wrapped in strings

- src/cpp/main.cpp
for both size reasons, and because it causes issues on the (future) arrow build.
> remove boost::format

- packages/perspective-viewer-highcharts/test/results/results.json
- packages/perspective-viewer-hypergrid/test/results/results.json
- packages/perspective-viewer/src/html/row.html
- packages/perspective-viewer/src/js/viewer/perspective_element.js
- packages/perspective-viewer/src/js/viewer/state_element.js
- packages/perspective-viewer/src/less/column_labels.less
- packages/perspective-viewer/src/less/row.less
- packages/perspective-viewer/test/js/simple_tests.js
- packages/perspective-viewer/test/results/results.json
- packages/perspective/src/js/api.js
- packages/perspective/src/js/perspective.js
- packages/perspective/test/js/filters.js
#349 UI filters should give user feedback when they are valid
* Exposed new table method for determining if a filter is valid
* Viewer validates filters before passing to table
* Invalid filters operands are underlined in red with a red exclamation mark next to them
* Filtering by an empty string is now invalid (this seems more appropriate for the current viewer UI)
* Added a screenshot test for the new invalid filter highlighting
* Added test for filtering by empty string
* Added tests for newly exposed is_valid_filter method
> Invalid filters

- packages/perspective-viewer-highcharts/package.json
- packages/perspective-viewer-highcharts/src/js/draw.js
- packages/perspective-viewer-highcharts/src/js/series.js
- packages/perspective-viewer-hypergrid/src/js/psp-to-hypergrid.js
- packages/perspective-viewer/package.json
- packages/perspective-viewer/src/js/utils.js
- packages/perspective-viewer/src/js/viewer/dragdrop.js
- packages/perspective/package.json
- packages/perspective/src/js/utils.js
- yarn.lock
Remove the cross imported files from `/src` directories in perspective packages. Useful so that we can build self contained bundles without needing to reach into packages. 
1. Added a comment for usages of `COLUMN_SEPARATOR_STRING` and replaced with constant. 
2. Replaced `detectIE` with external `detectie` package.
> Remove cross /src imports in packages

- .gitignore
- packages/perspective-viewer-highcharts/package.json
- packages/perspective-viewer-highcharts/src/config/highcharts.plugin.cjs.config.js
- packages/perspective-viewer-hypergrid/package.json
- packages/perspective-viewer-hypergrid/src/config/hypergrid.plugin.cjs.config.js
- packages/perspective-viewer/package.json
- packages/perspective-viewer/src/config/view.cjs.config.js
Output a `slim` version of the perspective viewer packages which is targeted when consuming the package from a module bundler (e.g. webpack, rollup, etc.)
1. Reduce the scope creep of #378 
2. unminified, precompiled assets, will be quicker for Webpack to parse and compile than the UMD builds. 
3. It will prevent duplication of dependencies of `perspective-*` packages when built together - leading to smaller bundle sizes for consumers.
> Output CJS module bundles for perspective-viewer packages

- docs/development.md
- packages/perspective/bench/js/bench.js
- scripts/bench.js
- src/cpp/emscripten.cpp
1. Benchmark script now has a `--limit <NUMBER>` flag, where `<NUMBER>` is the number of previous releases that will be run. For example, `--limit 1` will bench only the master, while `--limit 2` benches master and the preceding release.
2. Minor changes to the C++ side of DataAccessor to fit `const&` semantics for function parameters that are not mutated.
> Benchmark limit + minor changes to DataAccessor

- CMakeLists.txt
- packages/perspective/test/js/constructors.js
- src/cpp/date_parser.cpp
- src/include/perspective/base.h
- src/include/perspective/date_parser.h
1. Add a date parser on the C++ side that correctly validates date/datetime strings using the `iomanip` header. 
- *The parser is not called by any running code, nor is it included in `CMakeLists.txt`.* 
- The header does not include support for milliseconds and timezones, which is fine for string validation but will be problematic for parsing.
2. Added tests for the date parser, and moved computed column tests into their own `describe` block.
3. Fixed the use of now-undefined `PSP_ABORT` in `PSP_VERBOSE_ASSERT2`.
> C++ Date Validation

- packages/perspective-viewer/src/js/viewer/perspective_element.js
- packages/perspective/src/js/perspective.js
- packages/perspective/test/js/filters.js
#349 #375 Prior to my pull request for invalid filters, I've had a slight re-think of my implementation. My implementation resulted in empty strings being invalid filter operands. Although this makes sense for the viewer component, it doesn't seem to be appropriate for those using Perspective without the viewer. Therefore, I've pulled the check for empty strings into the viewer and updated the tests as necessary.
> Empty filters

- README.md
Adds an example based on IEX's new IEX Cloud streaming api to readme. Utilizes blocks and server-side-events.
> adding iex streaming example to readme

- packages/perspective/src/js/DataAccessor/DateParser.js
- packages/perspective/test/js/constructors.js
- src/cpp/context_grouped_pkey.cpp
Fixes a `date`/`datetime` parsing issue, which caused such columns with mixed string/integer to fail.  This should really not be a real use case - but due to the optimized parse code path, failures in this case resulted in unintelligible emscripten error messages, which is also resolved by this PR.
> Date parsing bug

- packages/perspective-viewer-highcharts/src/js/series.js
- packages/perspective-viewer-highcharts/test/html/null.html
- packages/perspective-viewer-highcharts/test/js/bar.spec.js
- packages/perspective-viewer-highcharts/test/results/results.json
Bar (and some other) charts with `null` values in categories fail to render;  this patch replaces them with the correct display value for null, `-`.
> `null` category axis fix

- packages/perspective-webpack-plugin/index.js
- packages/perspective-webpack-plugin/package.json
- packages/perspective-webpack-plugin/src/js/psp-worker-loader.js
- packages/perspective/package.json
- packages/perspective/src/js/perspective.js
- packages/perspective/test/js/constructors.js
- src/cpp/emscripten.cpp
- src/cpp/table.cpp
- src/include/perspective/table.h
- yarn.lock
For non-arrow data types, the single pass data loader can now upgrade column types to `string` if they have been mis-inferred as any `Number`.  Also fixes source map generation and debug build bugs encountered during debugging.
> String column promotion

- .travis.yml
This PR does two things:
- the Mac image on travis hangs occasionally. Since several of us are developing full time on MacBooks anyway, we can allow this one to fail. 
- Makes travis fail fast, so we dont waste resources when people need to iterate on PRs.
> Allow mac failures on travis, have travis fail fast

- packages/perspective-viewer-highcharts/test/js/slow.spec.js
- packages/perspective-viewer-highcharts/test/results/results.json
- packages/perspective-viewer-hypergrid/test/js/slow.spec.js
- packages/perspective-viewer-hypergrid/test/results/results.json
- packages/perspective-viewer/src/js/viewer.js
- packages/perspective-viewer/test/js/mutation_tests.js
- packages/perspective-viewer/test/js/simple_tests.js
- packages/perspective-viewer/test/js/slow.spec.js
- packages/perspective-viewer/test/results/results.json
- packages/perspective/src/js/api.js
- packages/perspective/src/js/perspective.js
- packages/perspective/test/js/clear.js
- packages/perspective/test/js/perspective.spec.js
- src/cpp/emscripten.cpp
Adds a `replace()` and `clear()` method to the `perspective.table()` API, as well as symmetric methods to the `<perspective-viewer>` web component.
> Add `replace()` and `clear()` to table

- packages/perspective-viewer/test/js/computed_columns.spec.js
- packages/perspective-viewer/test/js/simple_tests.js
- packages/perspective/src/js/perspective.js
Previously we allowed for 2 types of sort syntax to be passed through configs:
- `[["column", "asc"]]`: a 2D array with a column name and a direction string
- `["column"]`: an array of column names
This PR deprecates the latter format in our tests and uses the clearer, first format.
> Make sort syntax consistent in tests

- cpp/perspective/CMakeLists.txt
- cpp/perspective/src/cpp/base.cpp
- cpp/perspective/src/cpp/emscripten.cpp
- cpp/perspective/src/include/perspective/emscripten.h
- package.json
- packages/perspective-webpack-plugin/index.js
- packages/perspective-webpack-plugin/package.json
- packages/perspective/bench/js/bench.js
- packages/perspective/bench/js/browser_runtime.js
- packages/perspective/src/js/api.js
- packages/perspective/src/js/perspective.js
- packages/perspective/test/js/constructors.js
- packages/perspective/test/js/perspective.spec.js
- packages/perspective/test/js/pivots.js
- packages/perspective/test/js/to_format.js
- yarn.lock
* Adds `to_arrow()` method to `view()`, which generates an `ArrayBuffer` serialized Arrow.
* Re-enables asm.js test suite.
* Fixes `psp_abort()` to trigger in production mode, and fixes abort errors.
* Upgrades `@apache-arrow/es5-esm` to 0.4.0.
* Fixes `view()` without aggregate specified to return correct schema for (default) aggregate types.
> Write arrows

- cpp/perspective/src/cpp/view.cpp
- cpp/perspective/src/include/perspective/view.h
- packages/perspective-viewer-hypergrid/test/js/superstore.spec.js
- packages/perspective-viewer-hypergrid/test/results/results.json
- packages/perspective/src/js/perspective.js
- packages/perspective/test/js/pivots.js
- View should no longer be able to expand for indices past the number of row pivots.
- Add tests to confirm expand works as intend
- Refactor view.cpp to explicitly specialize `expand()`, `collapse()`, and `set_depth()`
> Fix regression on view expand

- packages/perspective/src/js/perspective.js
- packages/perspective/test/js/constructors.js
Fixes bug which, due to a mis-configured `papaparse`, caused CSV columns declared as strings to sometimes suffer a string->integer->string conversion during parsing, causing leading 0's to be dropped.
> CSV integer parse bug

- cpp/perspective/CMakeLists.txt
- cpp/perspective/src/cpp/config.cpp
- cpp/perspective/src/cpp/context_grouped_pkey.cpp
- cpp/perspective/src/cpp/context_one.cpp
- cpp/perspective/src/cpp/context_two.cpp
- cpp/perspective/src/cpp/context_zero.cpp
- cpp/perspective/src/cpp/data_slice.cpp
- cpp/perspective/src/cpp/emscripten.cpp
- cpp/perspective/src/cpp/get_data_extents.cpp
- cpp/perspective/src/cpp/view.cpp
- cpp/perspective/src/include/perspective/binding.h
- cpp/perspective/src/include/perspective/config.h
- cpp/perspective/src/include/perspective/data_slice.h
- cpp/perspective/src/include/perspective/get_data_extents.h
- cpp/perspective/src/include/perspective/view.h
- packages/perspective/bench/js/bench.js
- packages/perspective/src/js/perspective.js
- python/perspective/src/python.cpp
This PR begins to abstract the process of getting data out of perspective for use in visualizations/serialization. Right now, we create an intermediate array inside `emscripten.cpp` that contains the data extracted from the context. The end goal of the PR is to eliminate that intermediate structure—and the logic surrounding it—so as to make the data output API portable and trivial to implement in binding languages.
`t_data_slice` is a class that contains the underlying slice of data and associated metadata, which allows us to eventually remove the intermediate logic of `get_data` in `emscripten.cpp`. 
_Changes_
- Adds `t_data_slice` class
- Adds `is_column_only` to context construction
- Moves `get_column_extent` to independent class
Making the PR so we can discuss and get these changes …
> Add t_data_slice for data output

- cpp/perspective/src/cpp/config.cpp
- cpp/perspective/src/cpp/data_slice.cpp
- cpp/perspective/src/cpp/emscripten.cpp
- cpp/perspective/src/cpp/view.cpp
- cpp/perspective/src/include/perspective/binding.h
- cpp/perspective/src/include/perspective/config.h
- cpp/perspective/src/include/perspective/data_slice.h
- cpp/perspective/src/include/perspective/view.h
- packages/perspective/src/js/perspective.js
- packages/perspective/test/js/to_format.js
This PR implements the new data_slice API for zero and one-sided views. Benchmarking shows a consistent 10-15% improvement in calls to `to_json`, but I'd love to have that validated on other machines.
Changes:
- `t_data_slice` allows for data extraction with bounds checking; this solves an issue with `perspective-hypergrid` calling `get_columns` with row indices that were larger than the number of rows within the engine. The use of `at()` instead of `operator[]`, IIRC, should prevent undefined behavior from occurring when we index into the underlying slice. @texodus @timkpaine please look over this closely if possible.
- `perspective.js` now pulls column names and row paths from the data slice, instead of making calls to the underlying C++ view.
- Shared pointers are used for the …
> Implement t_data_slice API for data extraction from 0 & 1-sided views

- packages/perspective/src/js/perspective.js
- packages/perspective/test/js/updates.js
As it says on the tin.  This changes the default `on_update` API to invoke its callback function with no arguments.  The previous behavior, which called the callback with the modified rows (but only worked correctly for 0-sided contexts, and performs poorly) can be preserved via
```javascript
view.on_update(callback, {mode: "rows"});
```
Future updates will use the new `mode` optional parameter to implement a more granular update delta API, as well as improve the delta calculation performance penalty.
> `on_update` delta calculations are now lazy

- package.json
- packages/perspective-viewer-d3fc/package.json
- packages/perspective-viewer-d3fc/test/js/beforeEachSpec.js
- packages/perspective-viewer-d3fc/test/js/integration/bar.spec.js
- packages/perspective-viewer-d3fc/test/js/integration/line.spec.js
- packages/perspective-viewer-d3fc/test/js/integration/scatter.spec.js
- packages/perspective-viewer-d3fc/test/js/transform.js
- packages/perspective-viewer-d3fc/test/js/unit/group_and_stack.spec.js
- yarn.lock
Added support for Jest unit tests w/babel to the `perspective-viewer-d3fc` plugin, with a [stolen test implementation from the D3FC PoC repo](https://github.com/DevAndyLee/perspective-viewer-d3fc/blob/master/test/js/data/groupAndStackData.spec.js)
> D3FC unit test

- cpp/perspective/src/cpp/context_two.cpp
- packages/perspective/test/js/pivots.js
Fixes an issue which caused expand/collapse on rows in a 2-sided pivot, to also collapse column at the same depth.
> Fixed expand/collapse on 2-sided pivots

- cpp/perspective/src/cpp/view.cpp
- packages/perspective-viewer-hypergrid/test/js/regressions.spec.js
- packages/perspective-viewer-hypergrid/test/results/results.json
- packages/perspective/test/js/constructors.js
This PR fixes the persistent issue of an extra empty row on column-only views—the `num_rows` method is edited in the C++ to ignore the aggregate row for column-only views.
- Regression tests are added in the engine as well as in the Hypergrid plugin.
> Fix issue #522: row count is correct on column-only views

- packages/perspective-viewer-hypergrid/src/js/PerspectiveDataModel.js
- packages/perspective/src/js/perspective.js
- packages/perspective/test/js/to_format.js
Fixes Hypergrid drawing before cache has been filled.
Also fixes #525
> Fixed Hypergrid scroll stuttering

- cpp/perspective/src/cpp/data_slice.cpp
- cpp/perspective/src/cpp/emscripten.cpp
- cpp/perspective/src/cpp/view.cpp
- cpp/perspective/src/include/perspective/data_slice.h
- cpp/perspective/src/include/perspective/view.h
- packages/perspective-viewer/src/js/utils.js
- packages/perspective-viewer/test/js/simple_tests.js
- packages/perspective/src/js/perspective.js
- packages/perspective/test/js/pivots.js
- packages/perspective/test/js/to_format.js
This PR implements the `t_data_slice` API in use for 0 and 1-sided contexts, and fully integrates it into `perspective.js` and 2-sided contexts. It correctly skips header rows for sorted 2-sided contexts, and provides a unified `get(row_index, col_index)` API. This allows data serialization to be easily implemented and extensible.
- Data slice works for 2-sided views
- `t_data_slice` and `View` are documented in the header files
- additional tests to prevent regression
> Fully implement data slice API

- cpp/perspective/src/cpp/data_slice.cpp
- cpp/perspective/src/cpp/view.cpp
- cpp/perspective/src/include/perspective/data_slice.h
- cpp/perspective/src/include/perspective/view.h
- packages/perspective/src/js/perspective.js
- packages/perspective/test/js/to_format.js
Previously, the engine emitted a header row—containing all the data—for column-only views, which we sliced out in JS. This PR creates offsets inside `View` and `t_data_slice` in order to allow us to skip these rows in the engine.
> Remove header rows for column-only views

- cpp/perspective/src/cpp/aggspec.cpp
- cpp/perspective/src/cpp/context_one.cpp
- cpp/perspective/src/cpp/context_two.cpp
- cpp/perspective/src/cpp/data_slice.cpp
- cpp/perspective/src/cpp/emscripten.cpp
- cpp/perspective/src/cpp/view.cpp
- cpp/perspective/src/include/perspective/aggspec.h
- cpp/perspective/src/include/perspective/context_one.h
- cpp/perspective/src/include/perspective/context_two.h
- cpp/perspective/src/include/perspective/data_slice.h
- cpp/perspective/src/include/perspective/emscripten.h
- cpp/perspective/src/include/perspective/view.h
- packages/perspective-viewer-hypergrid/src/js/hypergrid.js
- packages/perspective/src/js/perspective.js
- packages/perspective/test/js/pivots.js
This fixes formatting for headers of `column-pivots`, like e.g. `datetime`.
`View.column_names()` now returns `std::vector<std::vector<t_tscalar>>`, and string rendering of these types is now handled in Javascript.
> Refactored data_slice to return t_tscalar

- packages/perspective-viewer/src/js/viewer.js
To match the other plugin calls, I believe these methods should also use the chart node as the context.
> Called save and restore with the correct context

- packages/perspective-viewer-hypergrid/src/js/hypergrid.js
Fixed hypergrid issue which caused hover themes to bleed when multiple themes are used on the same page
> Hypergrid hover theme fix

- docs/md/usage.md
- examples/git_history/chained.html
- examples/git_history/server.js
- packages/perspective-cli/src/html/index.html
- packages/perspective-cli/src/js/index.js
- packages/perspective/src/js/api.js
- packages/perspective/src/js/perspective.node.js
- packages/perspective/src/js/perspective.parallel.js
* Added support for `view()` as well as `table()` hosting on remote perspective servers, and relevent API modifications to support this - `server.open()` is now `server.host_table()` or `server.host_view()`, and `worker.open()` is now `worker.open_table()` or `worker.open_view()`.
* Added support for the `to_arrow()` method to work with remote perspective's `WebSocket` API.
* Update `perspective-cli` and documentation to reflect these changes.
> Remote arrow

- packages/perspective-jupyterlab/src/ts/widget.ts
- packages/perspective-phosphor/package.json
- packages/perspective-phosphor/src/ts/widget.ts
- packages/perspective-viewer/index.d.ts
- Enhancements to perspective-python to support d3fc charts
- add filter configuration
- add plugin configuration
> JupyterLab enhancements

- cmake/hopscotch.txt.in
- cpp/perspective/CMakeLists.txt
- cpp/perspective/src/cpp/column.cpp
- cpp/perspective/src/cpp/context_grouped_pkey.cpp
- cpp/perspective/src/cpp/context_two.cpp
- cpp/perspective/src/cpp/context_zero.cpp
- cpp/perspective/src/cpp/emscripten.cpp
- cpp/perspective/src/cpp/flat_traversal.cpp
- cpp/perspective/src/cpp/sparse_tree.cpp
- cpp/perspective/src/cpp/sym_table.cpp
- cpp/perspective/src/cpp/tracing.cpp
- cpp/perspective/src/cpp/tracing_impl_linux.cpp
- cpp/perspective/src/cpp/tracing_impl_osx.cpp
- cpp/perspective/src/cpp/tree_context_common.cpp
- cpp/perspective/src/cpp/vocab.cpp
- cpp/perspective/src/include/perspective/column.h
- cpp/perspective/src/include/perspective/flat_traversal.h
- cpp/perspective/src/include/perspective/gnode_state.h
- cpp/perspective/src/include/perspective/scalar.h
- cpp/perspective/src/include/perspective/sym_table.h
- cpp/perspective/src/include/perspective/vocab.h
- packages/perspective/bench/js/bench.js
- packages/perspective/bench/js/browser_runtime.js
- packages/perspective/src/js/perspective.js
- scripts/test.js
This PR contains a number of fixes applied as a result of some runtime profiling of the `table.update()` mechanism:
* Removed `std::unordered_map` in favor of `tsl::hopscotch_map`, which improves primary key lookup performance, and overall update processing time is improved by 50%.
* Added throttling to this method.  This means that `on_update()` is no longer called 1:1 with calls to `update()` (though the final `on_update()` will always be consistent with `table` state).  As a result, `update()` calls will no longer stack up and overwhelm other API calls, which leads to drastic improvement in perceived performance, and much smarter interleaving of `update()` and other calls which reflect the `view()` to the `<perspective-viewer>` element.
Additionally, a few other enhancements have been …
> Performance overhaul for `table.update()`

- packages/perspective-viewer-hypergrid/src/js/hypergrid.js
Fixes styling issue in `restyleElement()` method
> Fixed grid styling

- packages/perspective-phosphor/src/less/index.less
- packages/perspective-phosphor/src/ts/widget.ts
- packages/perspective-viewer/index.d.ts
This does 3 things
- Fixes CSS ugliness in phosphor/jlab:
- Adds restyle to type definitions for `perspective-viewer`
- Uses 1 and 2 to reenable dark mode:
~~Though it looks like the wrench is there in dark mode for some reason...~~
> add restyle to type definitions, fix dark mode in jlab, fix CSS issue

- cpp/perspective/src/cpp/context_one.cpp
- cpp/perspective/src/cpp/context_two.cpp
- cpp/perspective/src/cpp/context_zero.cpp
- cpp/perspective/src/cpp/flat_traversal.cpp
- cpp/perspective/src/cpp/step_delta.cpp
- cpp/perspective/src/cpp/view.cpp
- cpp/perspective/src/include/perspective/context_common_decls.h
- cpp/perspective/src/include/perspective/context_zero.h
- cpp/perspective/src/include/perspective/flat_traversal.h
- cpp/perspective/src/include/perspective/gnode.h
- cpp/perspective/src/include/perspective/gnode_state.h
- cpp/perspective/src/include/perspective/step_delta.h
- cpp/perspective/src/include/perspective/view.h
- packages/perspective/bench/js/bench.js
- packages/perspective/bench/js/browser_runtime.js
- packages/perspective/src/js/perspective.js
- packages/perspective/test/js/delta.js
- packages/perspective/test/js/updates.js
This PR fixes my previous implementation of calculating updated row indices:
- 0-sided contexts save changed primary keys to a set, and when `get_row_delta` is called, transforms the primary keys to row indices and returns the changed rows.
- `get_row_delta` no longer supports the `bidx` and `eidx` options, and will return deltas for all rows on default.
- `get_row_delta` in the `View` C++ class transforms the hopscotch set into a vector for interoperability with Emscripten and Javascript.
- New tests have been added for row delta that test row addition, deletion, and non-contiguous updates.
- Fix prettify errors in benchmark suite, and replace `localhost` URL with the Docker host URL.
> Row delta supports addition, delete, non-contiguous updates

- packages/perspective-viewer-d3fc/src/js/tooltip/selectionData.js
We previously showing the "mainValue" number, without subtracting "baseValue".
This affects Area and Column/Bar charts when there are both multiple aggregate values, and a split-by.
> Fixed tooltip value when split_values and multiple main values

- cpp/perspective/src/cpp/context_one.cpp
- cpp/perspective/src/cpp/context_two.cpp
- cpp/perspective/src/cpp/context_zero.cpp
- cpp/perspective/src/cpp/data_slice.cpp
- cpp/perspective/src/cpp/emscripten.cpp
- cpp/perspective/src/cpp/flat_traversal.cpp
- cpp/perspective/src/cpp/step_delta.cpp
- cpp/perspective/src/cpp/view.cpp
- cpp/perspective/src/include/perspective/context_common_decls.h
- cpp/perspective/src/include/perspective/data_slice.h
- cpp/perspective/src/include/perspective/flat_traversal.h
- cpp/perspective/src/include/perspective/step_delta.h
- cpp/perspective/src/include/perspective/view.h
- packages/perspective/src/js/API/host.js
- packages/perspective/src/js/perspective.js
- packages/perspective/test/js/constructors.js
- packages/perspective/test/js/delta.js
- packages/perspective/test/js/to_format.js
When calling `view.on_update` with the `modes` parameter set to `row`, the callback receives an arrow-serialized version of the data from the rows that were updated. 
- `on_update` mode parameters have been changed to `cell` and `row`
- new `get_data` methods have been added to each context allowing for data from certain row indices to be returned.
- `to_arrow` and `col_to_js_typed_array` now take `options.data_slice,` which specifies a custom `t_data_slice` object from which they will serialize.
- `fill_col_bool` now respects `undefined` and `null` values for arrow-serialized booleans.
- `t_data_slice` has a new constructor which specifies a vector of row indices
- `process_subscribe` in `host.js` now transfers arrow data and respects the arguments that are in its caller. This enables …
> Row deltas return arrow-serialized data

- packages/perspective-viewer/src/less/viewer.less
Fixed "drop" zones on `<perspective-viewer>` to have much wider borders.
> Made drag/drop zones more generous

- cpp/perspective/CMakeLists.txt
- packages/perspective/src/js/perspective.node.js
- packages/perspective/src/js/perspective.wasm.js
- scripts/build.js
Removes a hacky step of the build which wraps the JS output from Emscripten in a function.
> Use MODULARIZE emscripten option instead of a custom one

- packages/perspective-cli/babel.config.js
- packages/perspective-viewer-d3fc/babel.config.js
- packages/perspective-viewer-highcharts/babel.config.js
- packages/perspective-viewer-hypergrid/babel.config.js
- packages/perspective-viewer/babel.config.js
- packages/perspective/babel.config.js
- packages/perspective/src/config/perspective.node.config.js
Now that we no longer build ASM.JS, remove polyfills for WASM-incompatible browsers.
> Update Babel `preset-env`

- packages/perspective/src/js/API/client.js
- packages/perspective/src/js/perspective.node.js
- packages/perspective/test/js/internal.js
- packages/perspective/test/js/sync_load.spec.js
Fixes wasm module loading in Node.js, which was made asynchronous, without taking advantage of the message queuing code already in-place for the browser.
> Fixed async loading of node.js module

- examples/webpack/webpack.config.js
When developing locally via yarn workspaces, `@finos/perspective` is in `~/packages`;  but without building yarn workspaces (from the top of the repo), it is in `~/node_modules`. 
Fixes #638
> Fixed webpack config error in webpack example

- cpp/perspective/CMakeLists.txt
Remove typo in `CMakeLists` that broke debug builds.
> Fix debug builds

- .gitignore
- packages/perspective-viewer-d3fc/package.json
- packages/perspective-viewer/package.json
- packages/perspective-viewer/src/js/computed_column.js
- packages/perspective-viewer/src/js/viewer/dom_element.js
- packages/perspective-viewer/test/js/beforeEachSpec.js
- packages/perspective-viewer/test/js/jest.unit.config.js
- packages/perspective-viewer/test/js/transform.js
- packages/perspective-viewer/test/js/unit/dom_element.spec.js
Fix autocomplete error when filtering string column w/null values
* Factor out a function for filtering out null values before feeding
them into the autocomplete choices
* Add unit testing config to perspective-viewer package
* Add a unit test to cover this bugfix
Fixes issue: https://github.com/finos/perspective/issues/668
> Fix exception for filter labels

- packages/perspective-jupyterlab/package.json
Adds a build in the `version` script, which `lerna publish` will run _after_ updating version numbers but _before_ pushing to the remote. This should update the disted Jupyterlab with the right version of Perspective. 
See comment on [Lerna issue #1275](https://github.com/lerna/lerna/issues/1275#issuecomment-367057638) for explanation of version lifecycle hook as it relates to Lerna.
> Fix #616: perspective-jupyterlab versioning

- cmake/ordered-map.txt.in
- cpp/perspective/CMakeLists.txt
- cpp/perspective/src/cpp/aggspec.cpp
- cpp/perspective/src/cpp/config.cpp
- cpp/perspective/src/cpp/emscripten.cpp
- cpp/perspective/src/cpp/filter.cpp
- cpp/perspective/src/cpp/flat_traversal.cpp
- cpp/perspective/src/cpp/sort_specification.cpp
- cpp/perspective/src/cpp/view.cpp
- cpp/perspective/src/cpp/view_config.cpp
- cpp/perspective/src/include/perspective/aggspec.h
- cpp/perspective/src/include/perspective/binding.h
- cpp/perspective/src/include/perspective/config.h
- cpp/perspective/src/include/perspective/emscripten.h
- cpp/perspective/src/include/perspective/filter.h
- cpp/perspective/src/include/perspective/slice.h
- cpp/perspective/src/include/perspective/sort_specification.h
- cpp/perspective/src/include/perspective/view.h
- cpp/perspective/src/include/perspective/view_config.h
- cpp/perspective/test/cpp/simple.cpp
- packages/perspective/src/js/emscripten.js
- packages/perspective/src/js/perspective.js
- packages/perspective/test/js/filters.js
This PR builds on top of the `Table` class in C++, defining `t_view_config`: a unified declaration of what a view configuration object looks like, codified in C++ and then implemented in the binding language. 
By storing configuration variables (pivots, aggregates, filters, sorts, etc.) as primitive values, we can implement `view_config` in binding languages without having to construct abstractions that are only used in the engine (such as `t_aggspec` and `t_fterm`). This also encapsulates the primitive-to-abstraction conversion code inside `t_view_config`, reducing the amount of binding code required to construct a view.
- Adds `t_view_config` and associated logic
- Use `t_view_config` for all `View` objects, instead of `t_config`
- refactors `make_view` and `make_context` into templated …
> Add view config class in C++

- packages/perspective/src/js/config/index.js
Removed extraneous object copy in perspective/config, which is called in tight loops and is expected to be memoized.
> Fix performance regression

- packages/perspective-viewer-hypergrid/src/js/perspective-plugin.js
- packages/perspective-viewer-hypergrid/test/js/hypergrid.spec.js
- packages/perspective-viewer-hypergrid/test/js/regressions.spec.js
- packages/perspective-viewer-hypergrid/test/js/superstore.spec.js
- packages/perspective-viewer-hypergrid/test/js/utils.js
- packages/perspective-viewer-hypergrid/test/results/results.json
When the default `@finos/perspective-viewer-hypergrid` plugin is selected and an empty dataset is loaded (or when the element's `load()` method is called with a schema), Hypergrid's default click event handlers were not previously registered correctly, causing click events to not fire until the plugin was de-and-re-selected.
> `perspective-click` fix

- cpp/perspective/src/cpp/context_zero.cpp
- cpp/perspective/src/cpp/flat_traversal.cpp
- cpp/perspective/src/cpp/multi_sort.cpp
- cpp/perspective/src/cpp/storage.cpp
- cpp/perspective/src/include/perspective/multi_sort.h
This change improves CPU utilization for processing updates on 0-sided contexts by ~20x.  It is currently only implemented for WASM.
* Rewrote flat_traversal to take advantage of sorted-ness
* Removed min/max calculation
* Removed `memset(0)` for gnode ports
> 0-sided Performance Fix

- cpp/perspective/CMakeLists.txt
- cpp/perspective/src/cpp/emscripten.cpp
- cpp/perspective/src/cpp/utils.cpp
- docker/emsdk/Dockerfile
- docs/i18n/en.json
- docs/static/css/material.dark.css
- package.json
- packages/perspective-bench/bench/versions.js
- packages/perspective-bench/src/js/bench.js
- packages/perspective-bench/src/js/browser_runtime.js
- packages/perspective-viewer-hypergrid/test/js/hypergrid.spec.js
- packages/perspective-webpack-plugin/index.js
- packages/perspective/package.json
- packages/perspective/src/config/common.config.js
- packages/perspective/src/js/perspective.node.js
Updates perspective to Emscripten 1.38.42-upstream.
> Emsdk upstream

- cpp/perspective/src/cpp/emscripten.cpp
- cpp/perspective/src/cpp/gnode.cpp
- cpp/perspective/src/cpp/table.cpp
- cpp/perspective/src/include/perspective/base.h
- cpp/perspective/src/include/perspective/binding.h
- cpp/perspective/src/include/perspective/table.h
- cpp/perspective/test/cpp/simple.cpp
- packages/perspective/src/js/data_accessor/index.js
- packages/perspective/src/js/perspective.js
- packages/perspective/test/js/constructors.js
- packages/perspective/test/js/updates.js
This PR refactors the workings of the `Table` class and ports over some more functionality from JS to C++. Most importantly, the `limit_index`/`offset` property is now calculated within the `Table` class, which removes another chunk of state-dependent JS code. 
- Remove `GNODE_TYPE_IMPLICIT_PKEYED` which is not being used in the production codebase, and conflicts with features already present.
- Additional documentation added in JS and C++ for the table
> Calculate row offset in C++, refactor Table, remove implicit primary key mode

- cpp/perspective/src/cpp/base.cpp
- cpp/perspective/src/cpp/column.cpp
- cpp/perspective/src/cpp/data_table.cpp
- cpp/perspective/src/cpp/emscripten.cpp
- cpp/perspective/src/cpp/gnode.cpp
- cpp/perspective/src/cpp/gnode_state.cpp
- cpp/perspective/src/cpp/table.cpp
- cpp/perspective/src/include/perspective/binding.h
- cpp/perspective/src/include/perspective/data_table.h
- cpp/perspective/src/include/perspective/table.h
- examples/simple/schema.html
- examples/simple/test.html
- packages/perspective-viewer-hypergrid/test/js/superstore.spec.js
- packages/perspective/README.md
- packages/perspective/src/js/perspective.js
- packages/perspective/test/js/filters.js
Added support for generating & reading the special `__INDEX__`column, which allows access to this field even when an explicit `index` was not declared with the `table`.
> `index` column support

- packages/perspective-jupyterlab/src/less/index.less
- packages/perspective-jupyterlab/src/ts/widget.ts
- packages/perspective-phosphor/src/ts/widget.ts
fixes #694 without breaking in normal view
top: perspective in `ipywidgets.HBox`
bottom: normal
> Allow for perspective in ipywidgets layouts

- docs/static/css/material.dark.css
- packages/perspective-viewer-d3fc/test/results/results.json
- packages/perspective-viewer/src/js/computed_column.js
- packages/perspective-viewer/src/js/row.js
- packages/perspective-viewer/src/js/utils.js
- packages/perspective-viewer/src/js/viewer.js
- packages/perspective-viewer/src/js/viewer/action_element.js
- packages/perspective-viewer/src/js/viewer/dom_element.js
- packages/perspective-viewer/src/js/viewer/dragdrop.js
- packages/perspective-viewer/src/js/viewer/perspective_element.js
- packages/perspective-viewer/src/js/viewer/state_element.js
- packages/perspective-viewer/src/less/default.less
- packages/perspective-viewer/test/js/computed_columns.spec.js
A late-summer cleaning of the `<perspective-viewer>` web component:
* Supports missing attributes now, and auto replace empty `[]` and `{}` attributes.
* Removes default shadowing aggregates.
* Supports boolean attributes for `settings` and `updating`.
* Removed `render_time`.
* Fixes serialization of state from `save()`.
This will be a breaking API change for most developers.
> `perspective-viewer` cleanup

- cpp/perspective/src/cpp/base.cpp
- cpp/perspective/src/cpp/emscripten.cpp
- cpp/perspective/src/cpp/table.cpp
- cpp/perspective/src/cpp/view.cpp
- cpp/perspective/src/cpp/view_config.cpp
- cpp/perspective/src/include/perspective/base.h
- cpp/perspective/src/include/perspective/binding.h
- cpp/perspective/src/include/perspective/table.h
- cpp/perspective/src/include/perspective/view_config.h
- packages/perspective-viewer-hypergrid/test/js/regressions.spec.js
- packages/perspective/test/js/filters.js
- Removes unnecessary string copies in `emscripten.cpp`
- Use `std::move` when possible in constructors for `Table`, `View`, and `t_view_config`
- Clarify purpose of `filter_op` in the view config, and refactor base methods to accept "or" as a valid filter op
- clean up filter parsing in `emscripten.cpp`
> Refactor C++

- cpp/perspective/src/cpp/emscripten.cpp
- packages/perspective-viewer-d3fc/src/js/charts/candlestick.js
- packages/perspective-viewer-d3fc/src/js/charts/ohlc.js
- packages/perspective-viewer-d3fc/src/js/charts/xy-scatter.js
- packages/perspective-viewer-hypergrid/src/js/PerspectiveDataModel.js
- packages/perspective-viewer-hypergrid/src/js/editors.js
- packages/perspective-viewer-hypergrid/src/js/hypergrid.js
- packages/perspective-viewer-hypergrid/src/js/perspective-plugin.js
- packages/perspective-viewer-hypergrid/src/js/styles.js
- packages/perspective-viewer-hypergrid/src/less/hypergrid.less
- packages/perspective-viewer-hypergrid/test/html/editable.html
- packages/perspective-viewer-hypergrid/test/js/editing.spec.js
- packages/perspective-viewer-hypergrid/test/js/utils.js
- packages/perspective-viewer/src/js/computed_column.js
- packages/perspective-viewer/src/js/viewer.js
- packages/perspective-viewer/src/js/viewer/perspective_element.js
Adds the `editable` attribute to `<perspective-viewer>`, which allows cells to be edited.  Edits are treated as `update()` on the underlying `table`.
> Editing for `@finos/perspective-viewer-hypergrid`

- examples/simple/superstore-hypergrid.html
- packages/perspective-viewer-hypergrid/src/js/PerspectiveDataModel.js
- packages/perspective-viewer-hypergrid/src/js/editors.js
- packages/perspective-viewer-hypergrid/src/js/hypergrid.js
- packages/perspective-viewer-hypergrid/src/js/perspective-plugin.js
- packages/perspective-viewer-hypergrid/src/js/psp-to-hypergrid.js
- packages/perspective-viewer-hypergrid/src/js/styles.js
- packages/perspective-viewer-hypergrid/src/less/hypergrid.less
- packages/perspective-viewer-hypergrid/test/js/editing.spec.js
- packages/perspective-viewer-hypergrid/test/results/results.json
- packages/perspective-viewer/src/js/viewer/dom_element.js
- scripts/test_js.js
Makes editing more excel-like;  single-click for selection and LF on save.
Also supports index pinning, so real-time data sets are now stable to edit as well.
> Type-on-edit

- cpp/perspective/src/cpp/base.cpp
- cpp/perspective/src/cpp/emscripten.cpp
- cpp/perspective/src/cpp/gnode.cpp
- cpp/perspective/src/cpp/pool.cpp
- cpp/perspective/src/cpp/table.cpp
- cpp/perspective/src/include/perspective/base.h
- cpp/perspective/src/include/perspective/binding.h
- cpp/perspective/src/include/perspective/gnode.h
- cpp/perspective/src/include/perspective/pool.h
- cpp/perspective/src/include/perspective/table.h
- packages/perspective/test/js/constructors.js
- packages/perspective/test/js/updates.js
- python/table/perspective/include/perspective/python/fill.h
- python/table/perspective/src/fill.cpp
This PR refactors logic around constructing computed columns in order to move operations to the `t_gnode`'s `_process` method. 
Instead of constructing computed columns before the table is sent to `_process()`, use the metadata of the `_process` method to allow for partial updates (implicit and explicit index) on underlying columns for computed columns, which automatically propagates changes to computed columns. 
Previous iterations would recalculate each computed column for the total number of rows on the table; this allows computed column recalculation to happen ONLY for rows that were updated within `_process()`.
> Allow partial updates on computed column source columns

- cpp/perspective/src/cpp/table.cpp
- packages/perspective/test/js/updates.js
This PR removes the `abort()` we previously added for updates using implicit index, thus updates using `__INDEX__` (which always shadows the primary key) now work on indexed tables.
> Enable update with __INDEX__ on explicit index column

- docker/puppeteer/Dockerfile
- package.json
- packages/perspective-test/jest.all.config.js
- packages/perspective-test/jest.config.js
- packages/perspective-test/src/js/index.js
- packages/perspective-test/src/js/reporter.js
- packages/perspective/src/js/perspective.node.js
- scripts/setup.js
- scripts/test_js.js
- yarn.lock
Adds screencap images to test failures for quick debugging.
> Test suite failure feedback

- packages/perspective-viewer/src/js/viewer/dom_element.js
- packages/perspective-viewer/src/js/viewer/perspective_element.js
- packages/perspective/src/js/api/table_api.js
- packages/perspective/src/js/perspective.js
- python/perspective/perspective/table/table.py
Because computed columns is not yet implemented in the Python API, make sure the viewer does not render the computation sidebar when `Table.compute()` returns false.
> add compute() to dynamically show/hide sidebar computation panel

- packages/perspective/src/js/api/dispatch.js
- packages/perspective/src/js/perspective.js
- packages/perspective/test/js/delete.js
- packages/perspective/test/js/updates.js
- Remove errant `only` in perspective.js tests
- Make sure correct callback indices are removed in global cache
- Test remove updates
> Fix update bugs

- packages/perspective/src/js/api/client.js
Rewriting client as an ES6 class to allow for easier compatibility with Typescript in `perspective-jupyterlab` widget.
> ES6 Client API

- packages/perspective-viewer-hypergrid/src/js/hypergrid.js
- packages/perspective-viewer-hypergrid/src/js/psp-to-hypergrid.js
Index support for `to_*` methods can generate extremely large payloads, so we now turn this feature off for pivoted grids where many index keys may be present, greatly improving pivot performance on large datasets.
> Fixed grid performance when pivoted

- package.json
- packages/perspective-cli/package.json
- packages/perspective-test/package.json
- packages/perspective-viewer-d3fc/package.json
- packages/perspective-viewer-highcharts/package.json
- packages/perspective-viewer-hypergrid/package.json
- packages/perspective-viewer/package.json
- packages/perspective/package.json
- yarn.lock
Rebased #757 on top of emscripten update fixes.
> Add core-js@2 dependency that is required by transpiled outputs of Babel

- python/perspective/perspective/table/view.py
- python/perspective/perspective/tests/table/test_to_format.py
This PR adds and tests `to_csv` for the perspective-python API. The method itself uses `pandas.DataFrame.to_csv`, so it includes the index columns that come as part of dataframe construction.
> Add `to_csv` to Python API

- packages/perspective-test/src/js/index.js
- packages/perspective-test/src/js/reporter.js
- packages/perspective-viewer-hypergrid/src/js/PerspectiveDataModel.js
- packages/perspective-viewer-hypergrid/src/js/hypergrid.js
- packages/perspective-viewer-hypergrid/src/js/perspective-plugin.js
- packages/perspective-viewer-hypergrid/test/js/superstore.spec.js
- packages/perspective-viewer-hypergrid/test/js/utils.js
- packages/perspective-viewer/src/js/viewer.js
- packages/perspective-viewer/src/js/viewer/action_element.js
- packages/perspective-viewer/src/js/viewer/perspective_element.js
Fixes for `@finos/perspective-viewer-hypergrid`, which in sum greatly improve the user experience of using this plugin in the presence of slow interaciton with the core engine (e.g., when the engine is running on a remote server rather than a WebWorker).
* Fixed the plugin not appearing when the `plugin` attribute is toggled via `setAttribute()`.
* Fixed the viewer flashing when a hover event is triggered before the page can be loaded, e.g. due to large or frequent updates.
* Fixed various timing-related `console.error()`s.
> Hypergrid renderer fixes

- examples/remote/index.html
- packages/perspective-jupyterlab/src/ts/view.ts
- packages/perspective-jupyterlab/src/ts/widget.ts
- packages/perspective-phosphor/src/ts/widget.ts
- packages/perspective-viewer-hypergrid/src/js/editors.js
- python/perspective/examples/perspective_tornado_server.py
- python/perspective/examples/streaming.py
- python/perspective/perspective/core/__init__.py
- python/perspective/perspective/core/data/__init__.py
- python/perspective/perspective/core/manager.py
- python/perspective/perspective/core/session.py
- python/perspective/perspective/core/tornado_handler.py
- python/perspective/perspective/core/validate.py
- python/perspective/perspective/core/viewer.py
- python/perspective/perspective/core/viewer_traitlets.py
- python/perspective/perspective/core/widget.py
- python/perspective/perspective/table/__init__.py
- python/perspective/perspective/table/_accessor.py
- python/perspective/perspective/table/_data_formatter.py
- python/perspective/perspective/table/_date_validator.py
- python/perspective/perspective/table/_utils.py
- python/perspective/perspective/table/table.py
- python/perspective/perspective/table/view.py
- python/perspective/perspective/tests/core/test_manager.py
- python/perspective/perspective/tests/core/test_validate.py
- python/perspective/perspective/tests/core/test_viewer.py
- python/perspective/perspective/tests/core/test_widget.py
- python/perspective/perspective/tests/table/test_manager.py
This PR cleans up the integration of Perspective with web servers in Python:
- Adds PerspectiveTornadoHandler, which encapsulates the manager and messaging abstractions for use within Tornado.
- Adds PerspectiveSession, which encapsulates the state of a single websocket connection and removes the wrangling around `client_id` we have on the JS side.
- Fixes a bug with date editing in hypergrid
- Does a little cleanup in the python source
> Add tornado handler for perspective-python

- packages/perspective-viewer-hypergrid/src/less/hypergrid.less
- packages/perspective/src/js/perspective.parallel.js
Removes an outdated safeguard around wasm loading for ios devices, and fixes a CSS shadow dom bug.
> Fixed ios compatibility

- cpp/perspective/src/cpp/arrow.cpp
- cpp/perspective/src/include/perspective/arrow.h
- docker/python/Dockerfile
FIxes a few parsing issues for the new arrow parsing code:
* Adds support for the `Decimal` column type
* Adds support for the `Null` column type
* Adds support for `RecordBatchStream`
> Arrow fixes

- packages/perspective-jupyterlab/src/ts/view.ts
- python/perspective/perspective/core/widget.py
This PR allows for multiple output views on the same Jupyter widget - all operations are shared between the widget instances, so making a change to pivots, filter etc. in one rendered instance will change the other.
> Multiple views on JLab plugin

- cpp/perspective/CMakeLists.txt
- python/perspective/.bumpversion.cfg
- python/perspective/MANIFEST.in
- python/perspective/README.md
- python/perspective/requirements.txt
- python/perspective/setup.py
This PR allows us to build a portable wheel distribution for OSX:
- Our binaries depend on @rpath, which is set relative to the build location of the binary. This causes a problem when distributing to PyPi/installing from pip. In `setup.py`, we adjust the install names of the built binary to reference `@loader_path`, i.e. relative to the actual location of the binary download.
- Pin pyarrow in our requirements. This means that `TBB` is the only system requirement that needs to be installed from brew/build from source.
- Fix bumpversion config
- Fix manifest - graft source files and not tests
> Adjust setup.py for MacOS wheel dist

- package.json
- python/perspective/.bumpversion.cfg
- scripts/version_python.js
This PR adds `version_python.js` to the `version` script, which will run after Lerna increases the version number but before pushing to the remote.
> Link `lerna version` to `bumpversion`

- packages/perspective-viewer-hypergrid/package.json
- packages/perspective-viewer-hypergrid/src/js/PerspectiveDataModel.js
- packages/perspective-viewer-hypergrid/src/js/editors.js
- packages/perspective-viewer-hypergrid/src/js/hypergrid.js
- packages/perspective-viewer-hypergrid/src/js/perspective-plugin.js
- packages/perspective-viewer-hypergrid/src/js/psp-to-hypergrid.js
- packages/perspective-viewer/package.json
- packages/perspective-viewer/src/js/polyfill.js
- packages/perspective-viewer/src/js/viewer.js
- packages/perspective-viewer/src/js/viewer/dom_element.js
- yarn.lock
Fixes a few iphone/ios specific issues:
* `@finos/perspective-viewer-hypergrid` touch scroll is implemented by forking hypergrid (to [`faux-hypergrid`](https://github.com/texodus/faux-hypergrid)) and merging [hypergrid/807](https://github.com/fin-hypergrid/core/pull/807) @AmirF27 .
* Fixed mobile drag/drop UI by [forking](https://github.com/timruffles/mobile-drag-drop/pulls) the polyfill inline.
> Mobile fixes

- cpp/perspective/CMakeLists.txt
- cpp/perspective/src/cpp/arrow.cpp
- cpp/perspective/src/cpp/base.cpp
- cpp/perspective/src/cpp/data_table.cpp
- cpp/perspective/src/cpp/emscripten.cpp
- cpp/perspective/src/include/perspective/arrow.h
- cpp/perspective/src/include/perspective/binding.h
- cpp/perspective/src/include/perspective/raw_types.h
- python/perspective/perspective/core/data/__init__.py
- python/perspective/perspective/core/data/np.py
- python/perspective/perspective/core/data/pd.py
- python/perspective/perspective/include/perspective/python.h
- python/perspective/perspective/include/perspective/python/fill.h
- python/perspective/perspective/include/perspective/python/numpy.h
- python/perspective/perspective/src/fill.cpp
- python/perspective/perspective/src/numpy.cpp
- python/perspective/perspective/src/table.cpp
- python/perspective/perspective/src/utils.cpp
- python/perspective/perspective/table/_accessor.py
- python/perspective/perspective/table/_date_validator.py
- python/perspective/perspective/table/table.py
- python/perspective/perspective/tests/table/test_table.py
- python/perspective/perspective/tests/table/test_table_numpy.py
- python/perspective/perspective/tests/table/test_table_pandas.py
- python/perspective/perspective/tests/table/test_update.py
- scripts/setup.js
This PR adds a separate load path for Pandas dataframe and numpy arrays (dictionaries of numpy arrays, numpy structured arrays, and numpy record arrays. 
- It will try to copy all arrays of integral/float/bool type, and fill other types through iteration.
- Arrays of `dtype=object` will always be iteratively filled using the `marshal` method, which coerces data into the correct format. 
- Support for mixed dictionaries of numpy arrays and lists has been deprecated: datasets should be fully composed of `numpy.ndarray` or `list`, but not both.
- Adds support for numpy structured arrays.
- Adds and fully tests support for all numpy datetime types from nanosecond (`datetime64[ns]`) to year (`datetime64[Y]`).
- Adds support for loading timestamps (in seconds or milliseconds since epoch) into …
> Dataframe/Numpy Array Loader

- packages/perspective-jupyterlab/src/ts/client.ts
- packages/perspective-jupyterlab/src/ts/view.ts
- packages/perspective-phosphor/src/ts/widget.ts
- packages/perspective-viewer/index.d.ts
- python/perspective/perspective/core/manager.py
- python/perspective/perspective/core/widget.py
- python/perspective/perspective/tests/core/test_widget.py
- scripts/build_python.js
- scripts/install_python.js
This PR fixes some remaining issues with the Python plugin:
- `on_update` now works in Python 2 after fixing a bug due to different implementations of `functools.partial` between Python 3 and Python 2
- `update` has been implemented for widgets running in client-only mode
- remove all build artifacts for python on each run of `yarn build`
> Add `update` for widget in client mode, fix `on_update` in Python 2

- cpp/perspective/src/cpp/context_two.cpp
- cpp/perspective/src/include/perspective/context_two.h
- packages/perspective/test/js/clear.js
> Two sided sort fixes

- cpp/perspective/CMakeLists.txt
- cpp/perspective/src/cpp/arrow.cpp
- python/perspective/perspective/table/view.py
- python/perspective/perspective/tests/table/test_table_arrow.py
Fix for correct integer index type, resulting in working dictionary columns when read in Python, as reported by @sc1f
> Fixed Python Arrow loading bug

- python/perspective/perspective/core/widget.py
- python/perspective/perspective/tests/core/test_widget.py
This PR allows widgets to be constructed with schemas when using the client-only flag. Previously, type objects were not serialized properly, and schema construction failed.
> Allow client mode widget to be constructed with schema

- cpp/perspective/src/cpp/emscripten.cpp
- packages/perspective-jupyterlab/src/ts/view.ts
- packages/perspective-phosphor/src/ts/widget.ts
- packages/perspective-viewer/index.d.ts
- packages/perspective-viewer/src/js/viewer.js
- python/perspective/perspective/core/__init__.py
- python/perspective/perspective/core/viewer.py
- python/perspective/perspective/core/widget.py
- python/perspective/perspective/src/fill.cpp
- python/perspective/perspective/table/table.py
- python/perspective/perspective/tests/core/test_viewer.py
- python/perspective/perspective/tests/core/test_widget.py
- python/perspective/perspective/tests/table/test_table.py
Add support for pandas and numpy data structures into client mode widget - previously these weren't getting serialized properly.
Additionally, add `clear()` and `replace()` to the viewer, as well as remove column promotion logic from updates - it will cause an error.
> Client mode supports dataframes, np.ndarray, structured and recarray

- python/perspective/perspective/table/table.py
Updates previously used the `names` property of the table, which may be of a different order than the schema of the `t_gnode`. Remove the use of `names` and replace with `get_columns()` from the gnode schema.
> Fix misordered columns in update

- python/perspective/perspective/src/accessor.cpp
- python/perspective/perspective/src/fill.cpp
- python/perspective/perspective/src/numpy.cpp
- python/perspective/perspective/src/utils.cpp
- python/perspective/perspective/table/_accessor.py
- python/perspective/perspective/tests/table/test_table.py
- python/perspective/perspective/tests/table/test_table_infer.py
- python/perspective/perspective/tests/table/test_table_numpy.py
- python/perspective/perspective/tests/table/test_table_pandas.py
This PR changes our inference check to infer int32s in python 2 and int64 in python 3. Additionally, it allows `long` and `unicode` to be used in schemas; `long` maps to int64, and `unicode` maps to string. 
Actual storage semantics of the values are not changed, so the limit for numeric types remains at 64 bits. Passing in a value that overflows int64 is undefined behavior.
Additionally wraps the call to `iter` to generate more meaningful errors when assessing the type of a dataset.
> Default to int64 in Python3, add `long` and `unicode` to schema and type inference

- README.md
- cpp/perspective/src/cpp/scalar.cpp
- packages/perspective-phosphor/src/ts/widget.ts
- packages/perspective-viewer/index.d.ts
- python/perspective/perspective/manager/manager.py
- python/perspective/perspective/table/_accessor.py
- python/perspective/perspective/table/table.py
- python/perspective/perspective/tests/table/test_table.py
- python/perspective/perspective/tests/table/test_table_infer.py
- python/perspective/perspective/tests/table/test_table_numpy.py
- python/perspective/perspective/tests/table/test_table_pandas.py
- python/perspective/perspective/tests/table/test_update.py
- python/perspective/perspective/tests/table/test_update_numpy.py
- python/perspective/perspective/tests/table/test_view.py
- python/perspective/perspective/widget/widget.py
- Fix widget resize by calling `notifyResize` properly
- Fix typing for Perspective Viewer by making table options optional
- Fix exception thrown when string booleans ("True", "False") were passed into Perspective
- use [`distutils.util.strtobool`](https://docs.python.org/2/distutils/apiref.html#distutils.util.strtobool) to parse truthy/falsy values
- Make sure column pivots on booleans return `true` or `false` as their column name, not 0/1
> Widget fixes for resizing, TS typings, boolean columns

- python/perspective/perspective/tests/core/test_widget_pandas.py
- python/perspective/perspective/widget/widget.py
When passing in `pandas.MultiIndex` to `PerspectiveWidget`, the parsed columns and pivots take precedence over all `kwargs` passed in by the user. This PR prefers user input for widgets created from dataframe for `columns`, `row_pivots`, and `column_pivots`.
> Preserve user columns and pivots in widget

- packages/perspective-jupyterlab/package.json
- packages/perspective-jupyterlab/src/config/plugin.config.js
- packages/perspective-jupyterlab/src/less/index.less
- packages/perspective-jupyterlab/src/ts/index.ts
- packages/perspective-jupyterlab/src/ts/plugin.ts
- packages/perspective-jupyterlab/src/ts/renderer.ts
- packages/perspective-jupyterlab/src/ts/view.ts
- packages/perspective-phosphor/package.json
- python/perspective/perspective/viewer/viewer.py
- python/perspective/perspective/viewer/viewer_traitlets.py
- yarn.lock
Initial cut at a CSV/JSON viewer in jupyterlab
Standalone CSV/JSON viewer:
- Can parse records-oriented JSON or CVS, available from the right click menus for `Open With`
- Shows error for datatypes can't parse
- Grabs light/dark theme from environment
- Changes when theme is changed
Updates for `PerspectiveWidget`:
- If you don't pass in `dark=True` or `dark=False`, it will pick it up from the environment
> CSV/JSON renderer in JupyterLab

- packages/perspective/src/js/perspective.node.js
Fixes #841 
* Removes the empty `view()` which kept hosted `table` alive.  `<perspective-viewer>` no longer deletes it's `table` when it is [itself deleted](https://github.com/finos/perspective/blob/eaabd8b39349fc39cb23f4891b56430fa8fec993/packages/perspective-viewer/src/js/viewer/perspective_element.js#L458), so this is not default deleted (though it can still be explicitly deleted remotely - probably something to change later).
* Adds `on_delete` callbacks for both, unhosting objects when they are deleted.
* Adds `eject_table()` and `eject_view()` methods.
> Node.js `table` unpin

- packages/perspective-viewer/src/js/viewer.js
Simple fix to regression in standalone `<perspective-viewer>` resize behavior
> Fixed resize behavior

- python/perspective/perspective/core/_version.py
- scripts/version_python.js
This PR changes the versioning script to use the correct value for `rc`, as well as adding the changed Python version files to Git so that `lerna publish` can pick them up.
> Update versioning script for Python

- package.json
- python/perspective/bench/__init__.py
- python/perspective/bench/bench.py
- python/perspective/bench/benchmark.html
- python/perspective/bench/perspective_benchmark.py
- python/perspective/package.json
- python/perspective/perspective/__init__.py
- python/perspective/perspective/libpsp.py
- python/perspective/perspective/manager/manager.py
- python/perspective/perspective/table/__init__.py
- python/perspective/perspective/table/_accessor.py
- python/perspective/perspective/table/_data_formatter.py
- python/perspective/perspective/table/_date_validator.py
- python/perspective/perspective/table/_utils.py
- python/perspective/perspective/table/table.py
- python/perspective/perspective/table/view.py
- python/perspective/perspective/tests/client/test_client.py
- python/perspective/perspective/tests/conftest.py
- python/perspective/perspective/tests/table/test_table.py
- python/perspective/perspective/tests/table/test_view.py
- python/perspective/perspective/tests/widget/test_widget.py
- python/perspective/perspective/tests/widget/test_widget_pandas.py
- python/perspective/perspective/viewer/viewer.py
- python/perspective/perspective/widget/widget.py
- scripts/build_python.js
- scripts/test_python.js
This PR adds a primitive benchmark suite for `perspective-python`, which follows the convention set by the Javascript benchmark suite - it runs operations for Table construction from different datasets, view construction with different pivot settings, and serializing data in all formats from each of those views. Benchmark results are written to a `perspective.Table` which is hosted via Tornado when the suite finishes (or when Ctrl-C is used to exit the script).
Additionally, this PR refactors the module loading semantic for `perspective-python`: when the C++ runtime is not present, a reasonable error message is logged, and symbols dependent on the C++ binding will not be exported in the module. `PerspectiveWidget` in client mode becomes the only usable symbol, and `Table`, …
> Add benchmark suite for Python, Refactor module loading for environments where C++ cannot be built

- cpp/perspective/src/cpp/arrow_loader.cpp
- cpp/perspective/src/cpp/arrow_writer.cpp
- cpp/perspective/src/cpp/base.cpp
- cpp/perspective/src/cpp/schema.cpp
- cpp/perspective/src/cpp/table.cpp
- cpp/perspective/src/cpp/view.cpp
- python/perspective/perspective/src/numpy.cpp
- python/perspective/perspective/tests/table/test_table_arrow.py
- python/perspective/perspective/tests/table/test_update_arrow.py
This PR makes the error messages from the C++ engine more helpful to users, especially where column names are involved - the offending column name is now included in the error message.
> Improved error messages from C++

- python/perspective/.bumpversion.cfg
This PR changes 'candidate' to 'rc' in bumpversion.cfg, ensuring that the values used for versioning Python are finally correct.
> Python versioning fix

- python/perspective/perspective/src/utils.cpp
- python/perspective/perspective/table/_date_validator.py
- python/perspective/perspective/tests/table/test_table_datetime.py
- python/perspective/perspective/tests/table/test_table_numpy.py
- python/perspective/perspective/tests/table/test_update.py
- python/perspective/perspective/widget/widget.py
This PR implements and tests `perspective-python`'s time zone semantics, and offers an explanation to how Perspective handles time zones.
In the browser use case, time zones do not pose a problem as all times are localized to the browser's time zone. When running `perspective-python` on the server, however, the server may not be in the same time zone as the client, and time zone handling must be defined. 
Currently, `perspective-python` makes the assumption that all `datetime` and `Timestamp` objects are defined in _local time_, and the `tzinfo` attribute is ignored. Internally, the C++ engine stores datetime values as Unix timestamps in milliseconds since epoch, and the [conversion](https://github.com/finos/perspective/blob/master/python/perspective/perspective/table/_date_validator.py#L9 …
> Time zone awareness in perspective-python

- python/perspective/perspective/manager/manager.py
This PR fixes a silent breakage with `on_update` callbacks in PerspectiveManager: previously, `on_update` with no args silently failed because I was accessing an element not in the args list. This fixes the issue by checking the length of `args` before attempting to read it.
> Fix `on_update` callbacks in Python

- README.md
- docs/core/Footer.js
- docs/i18n/en.json
- docs/md/concepts.md
- docs/md/installation.md
- docs/md/js.md
- docs/md/python.md
- docs/pages/en/index.js
- docs/sidebars.json
- docs/siteConfig.js
- docs/static/css/concepts/index.css
- docs/static/css/custom.css
- docs/static/js/concepts/index.js
- examples/simple/superstore-arrow.html
- examples/simple/superstore-hypergrid.html
- packages/perspective-viewer/README.md
- packages/perspective-viewer/src/js/viewer.js
- packages/perspective/README.md
- packages/perspective/src/js/perspective.js
- python/perspective/docs/perspective.table.rst
This PR adds and edits several pieces of useful documentation, as well as styling improvements to Perspective's [website](https://perspective.finos.org).
- Adds a "Conceptual Overview", which is a language-agnostic look at Perspective's core concepts, explaining how `Table`, `View`, and various `View` options work. This guide helps to fill in the gaps in our API documentation/user guide about Perspective's concepts, and moves them to one centralized location.
- Restructure the installation guide, JS user guide, and Python user guide, adding content where necessary.
- Restyle the Perspective website with new fonts and code highlighting
- Regenerate READMEs for `perspective`, `perspective-viewer` and `perspective-python`
> Improve Perspective Documentation

- packages/perspective-viewer/index.d.ts
Incredibly contrived way to force Typescript and React to play nicely with `<perspective-viewer>`.
> Fixed React types.

- packages/perspective-viewer-hypergrid/src/js/styles.js
- packages/perspective-viewer/src/themes/material.less
This PR allows the hypergrid selection styling on the tree column to fallback to the same style as  the rest of the grid if it's not explicitly set
> Fix selection styling on `@finos/perspective-viewer-hypergrid`

- docs/md/installation.md
- python/perspective/README.md
- python/perspective/setup.py
This PR edits the Python README to include instructions for installing `pyarrow`, and edits `setup.py` for Pypi to read the README properly as markdown instead of RST.
> Update Python README

- python/perspective/perspective/tests/viewer/test_viewer.py
- python/perspective/perspective/viewer/viewer.py
Implements `save` and `restore` on the PerspectiveViewer class, useful for widget introspection and reconstruction.
> implement save/restore on viewer configuration

- cpp/perspective/src/cpp/computed_function.cpp
- packages/perspective-viewer-hypergrid/src/js/perspective-plugin.js
- packages/perspective/test/js/computed.js
This PR fixes a bug in the `week_bucket` computed function for date and datetime columns, replacing the calculation for week bucket with a more robust version from the `date.h` library.
> Fix #898 - week bucket overflows

- packages/perspective-viewer-hypergrid/src/js/PerspectiveDataModel.js
- packages/perspective-viewer-hypergrid/src/js/hypergrid.js
- packages/perspective-viewer-hypergrid/src/js/perspective-plugin.js
- packages/perspective-viewer-hypergrid/test/js/selection.spec.js
- packages/perspective-viewer-hypergrid/test/results/linux.docker.json
This PR makes the `perspective-viewer-hypergrid` selection state save/restore compatible. 
If a row is selected and `save` is called on the `perspective-viewer`, the config returned will have `plugin_config` with the selected row index. Similarly to restore a selection state, you can call `restore` with the selected row index set on the `plugin_config` to set the selection state of the grid e.g.
`viewer.restore({plugin_config: {selected: "row_index"}})`
This PR also binds the `perspective-select` event to the `fin-row-selection-changed` event instead of the `cellClicked` callback. This allows selection events from arrow keys to be captured.
\
> Make `perspective-viewer-hypergrid` selection state save/restore compatible

- package.json
- yarn.lock
Cleans up duplicate `yarn.lock` entries by tightening some dependency ranges, as discussed in #906
> Remove yarn dependency duplication.

- examples/workspace/src/index.js
- packages/perspective-workspace/src/js/workspace/commands.js
- packages/perspective-workspace/src/js/workspace/discrete.js
- packages/perspective-workspace/src/js/workspace/dockpanel.js
- packages/perspective-workspace/src/js/workspace/menu.js
- packages/perspective-workspace/src/js/workspace/widget.js
- packages/perspective-workspace/src/js/workspace/workspace.js
- packages/perspective-workspace/src/less/dockpanel.less
- packages/perspective-workspace/src/less/menu.less
- packages/perspective-workspace/src/less/tabbar.less
- packages/perspective-workspace/src/less/viewer.less
- packages/perspective-workspace/src/less/widget.less
- packages/perspective-workspace/src/less/workspace.less
- packages/perspective-workspace/src/theme/material.less
- packages/perspective-workspace/src/theme/vaporwave.less
- packages/perspective-workspace/test/js/integration/restore.spec.js
- packages/perspective-workspace/test/js/unit/workspace.spec.js
This PR adds a new `workspace-layout-update` event  to `perspective-workspace`that is fired whenever the user modifies the layout or any of the `perspective-viewers`.
This PR also contains css class names cleanup which should help differentiate between `@phosphor` and `perspective-workspace` class selectors
> Add 'workspace-layout-update' event and css class selector names cleanup 

- cpp/perspective/src/cpp/computed_function.cpp
- packages/perspective-viewer-hypergrid/src/js/perspective-plugin.js
- packages/perspective/test/js/computed.js
- python/perspective/perspective/src/numpy.cpp
- python/perspective/perspective/src/table.cpp
- python/perspective/perspective/src/view.cpp
- python/perspective/perspective/table/_accessor.py
- python/perspective/perspective/tests/table/test_table_numpy.py
- python/perspective/perspective/tests/table/test_table_pandas.py
- python/perspective/perspective/tests/table/test_view.py
- python/perspective/perspective/tornado_handler/tornado_handler.py
This PR provides several fixes for issues with `PerspectivePython`:
- When passing in a `pandas.DataFrame`, Perspective will read the `columns` property and load the dataframe in the specified order. Perspective will continue to call `.keys()` for datasets composed of Python `dict` and `list` values, and the canonical way to determine column order should be through creating a `View` with the `columns` kwarg set. This change simply makes Perspective's column layout more symmetrical with that of the provided DataFrame.
- When creating a `View`, columns included in `aggregates` but not in `columns` will not have their aggregates applied. This fixes issue #904, which occurred because the order of `.keys()` in `aggregates `!=` the order of `columns`.
- Computed columns will write `null` to the …
> Fix column ordering in Python, null handling for computed columns

- azure-pipelines.yml
- package.json
- packages/perspective-test/jest.all.config.js
- scripts/build_python.js
- yarn.lock
Adds `jest` and `pytest` `junit` output, and publish these results to Azure Devops for [pretty build analytics](https://dev.azure.com/finosfoundation/perspective/_build/results?buildId=18&view=ms.vss-test-web.build-test-results-tab).
> Added Azure compatible reporting for tests

- cpp/perspective/src/cpp/view_config.cpp
- packages/perspective-viewer-d3fc/src/js/axis/ordinalAxis.js
- packages/perspective-workspace/src/js/workspace/workspace.js
* Fixes a regression in #901 which eliminated an event dispatch.
* Fixes a D3FC plugin bug which caused `null` groups to not work on `ordinalAxis`.
* Fixes a sort-ordering bug when an aggregate is specified to override a non-displayed sort column.
> Event regression fix

- packages/perspective-workspace/src/js/workspace/workspace.js
- packages/perspective-workspace/test/js/integration/restore.spec.js
- packages/perspective-workspace/test/results/linux.docker.json
This PR fixes a bug where `workspace` generated non-unique `slot` names. 
This bug was evident while restoring previously saved layouts with generated viewer slot names. While the layouts restored fine, subsequent `duplicate` calls generated non-unique slot names and rendered incorrectly.
> Fix `perspective-workspace` non-unique generated slotid bug

- examples/workspace/src/index.html
- examples/workspace/src/index.js
- examples/workspace/webpack.config.js
- packages/perspective-workspace/src/js/index.js
This PR fixes a bug where `perspective-workspace` fails during page load.
The error only happens when `perspective-workspace` is declared in the html (see `workspace` example)
> Fix `perspective-workspace` initialize bug

- packages/perspective-workspace/package.json
- packages/perspective-workspace/src/js/workspace/tabbar.js
- packages/perspective-workspace/src/js/workspace/widget.js
- packages/perspective-workspace/src/js/workspace/workspace.js
This PR fixes a bug when you duplicate an untitled widget.
> Fix widget title in `perspective-workspace`

- azure-pipelines.yml
- python/perspective/perspective/src/numpy.cpp
- python/perspective/perspective/table/view.py
- python/perspective/perspective/tests/table/test_to_format.py
> Deal with np.int_ on Windows, handle missing __INDEX__

- python/perspective/README.md
- Removes tbb and requirements.txt from install docs
- Adds CMake and C++ compiler as dependencies
> Fix #945: Improve Python install docs

- packages/perspective-workspace/src/js/workspace/workspace.js
- packages/perspective-workspace/test/js/unit/__mocks__/@finos/perspective-viewer.js
- packages/perspective-workspace/test/js/unit/tables.spec.js
This PR fixes a bug in `perspective-workspace` where trying to delete a table threw a `Maximum call stack size exceeded` error
> Fix tables `delete` bug in `perspective-workspace`

- cpp/perspective/CMakeLists.txt
- python/perspective/MANIFEST.in
- python/perspective/setup.py
This should fix:
- #937 
May also help fix:
- #928 
Fixes (unrelated):
- #952 
Don't know how possible it is to test this so i've added an extensive comment about the two library copies
> Bugfix sdist

- cpp/perspective/src/cpp/computed.cpp
- cpp/perspective/src/cpp/emscripten.cpp
- examples/simple/streaming.js
- packages/perspective/src/js/perspective.js
- packages/perspective/test/js/computed.js
When a computed column is added, a new `Table` is created with the computed column, and Perspective internally invalidates and cleans up the old `Table`. 
However, if updates were queued on the old `Table` and then called for process, the state between the old `Table` and the new `Table` (both of which have the computed column) may fall out of sync and cause errors at random.
This PR adds a call to `call_process` before creating the computed column, ensuring that all queued updates are processed before the old `Table` is invalidated.
It also reverses a change on the `streaming.html` example, by reducing the tick rate to something approaching sanity and adding a `date` column for full type coverage.
> Fully clear queued updates before adding a new computed column

- python/perspective/perspective/manager/manager.py
This PR fixes a small issue with `PerspectiveManager`, which treated `str` return values as `bytes` and attempted to pass them with the `binary` kwarg set to True. This broke the copy and download features in JupyterLab when running a Python 2 kernel, specifically when calling `to_csv` using the widget.
> PerspectiveManager no longer treats `str` as `bytes` in Python 2

- docs/md/development.md
Removing these instructions as they are repeated further down the page.
`brew install flatc` returning `Error: No available formula with the name "flatc"`
> Remove duplicate brew instructions

- examples/remote-express-typescript/assets/index.css
- examples/remote-express-typescript/assets/index.html
- examples/remote-express-typescript/package.json
- examples/remote-express-typescript/src/server.ts
- examples/remote-express-typescript/tsconfig.json
- package.json
- packages/perspective/index.d.ts
- yarn.lock
This PR adds typings for `WebSocketServer`, `WebSocketManager` and other nodejs components. Also included a typescript nodejs example
Fixes #971
> Update typings to include nodejs only components 

- README.md
- examples/simple/superstore.html
- packages/perspective-viewer-datagrid/babel-plugin-transform-tagged-literal.js
- packages/perspective-viewer-datagrid/babel.config.js
- packages/perspective-viewer-datagrid/src/js/datagrid.js
- packages/perspective-viewer-datagrid/src/js/events.js
- packages/perspective-viewer-datagrid/src/js/scroll_panel.js
- packages/perspective-viewer-datagrid/src/js/table.js
- packages/perspective-viewer-datagrid/src/js/tbody.js
- packages/perspective-viewer-datagrid/src/js/thead.js
- packages/perspective-viewer-datagrid/src/js/tree_row_header.js
- packages/perspective-viewer-datagrid/src/js/utils.js
- packages/perspective-viewer-datagrid/src/js/view_model.js
- packages/perspective-viewer-datagrid/src/less/material.less
- packages/perspective-viewer-datagrid/test/results/linux.docker.json
- packages/perspective-viewer/src/js/viewer.js
Adds type-aware formatting and customization to tree headers.
Also cleans up DOM initialization methods in `scroll_panel.js` and `view_model.js` (now `tree_row_header.js`);  these now use `innerHTML` and template literal strings, but with a custom babel plugin `babel-plugin-transform-tagged-literal.js` which strips format whitespace, which would otherwise be ignored by the minifier (Terser).
> `@finos/perspective-viewer-datagrid` Tree Formatting

- cpp/perspective/CMakeLists.txt
- package.json
- scripts/_wheel_python.js
This PR adds an entry to `INSTALL_RPATH ` that allows the binary to look for PyArrow in a directory relative to `libbinding.so`. 
I ran into this problem when trying to push a Manylinux 2010 wheel of Perspective onto a Heroku dyno, which stores its Python packages in `/app/.heroku/`. Perspective was only looking for `pyarrow` using the path of `pyarrow` supplied to it from the machine that _built_ the wheel, which was different from the machine that the wheel was installed to.
Adding the new entry to `INSTALL_RPATH` makes the assumption that both `perspective-python` and `pyarrow` are installed to the same site-packages folder. This change is only useful for installing from wheel; if a user builds Perspective from source, the path to `pyarrow` has to be correct for the build to succeed. …
> Look for PyArrow relative to Perspective in @rpath

- cpp/perspective/src/cpp/view_config.cpp
- packages/perspective/test/js/sort.js
- python/perspective/examples/remote.html
This PR fixes an issue where the incorrect `count` aggregate was used to sort hidden columns used as row/column pivots. Seen in the [Perspective COVID example](https://bl.ocks.org/sc1f/raw/6a04603d60967d3356a6156cb5399884/):
Because the `count` of each unique item in the column was used - and not the values of each unique item - row/column headers were displayed in the incorrect order. This PR fixes that issue in `t_view_config` and adds tests that assert the correct behavior:
> Fix incorrect sort order when hidden, pivoted columns are sorted

- python/perspective/examples/perspective_manager_lock.html
- python/perspective/examples/perspective_manager_lock.py
- python/perspective/perspective/manager/manager.py
- python/perspective/perspective/tests/manager/test_manager.py
This PR adds the `lock` attribute to `PerspectiveManager`, which will reject the following remote messages that can mutate the state of `Table`s and `View`s under management:
- `table`
- `table.update`
- `table.clear`
- `table.replace`
- `table.reset`
- `table.delete`
`PerspectiveManager`s exposed over the internet should be locked, either by calling `.lock()` or initializing with `lock=True`. This PR also includes tests and a compact example demonstrating message rejection when the manager is locked.
> Add `lock` to PerspectiveManager

- python/perspective/bench/bench.py
- python/perspective/bench/perspective_benchmark.py
- python/perspective/bench/run_perspective_benchmark.py
This PR improves the Python benchmarks by adding tests for calls to `update`, which is now benchmarked for both JSON and `pandas.DataFrame` when 10 views of various pivots are created and forced to be notified on each update. The benchmark measures the amount of time it takes to call `update` and then `Table.size()`, which forces processing of the update before returning a value.
> Update Python benchmarks to include results for `update` calls

- cpp/perspective/src/cpp/base.cpp
- python/perspective/perspective/core/data/__init__.py
- python/perspective/perspective/core/data/np.py
- python/perspective/perspective/include/perspective/python/numpy.h
- python/perspective/perspective/src/numpy.cpp
- python/perspective/perspective/table/_accessor.py
- python/perspective/perspective/table/table.py
- python/perspective/perspective/tests/table/test_table_numpy.py
This PR speeds up `perspective-python`'s numpy loading by adding a code path for a very common requirement - when a column is typed as an integer and updated with a `numpy.float64` array, the array is not trivially copyable into the column's underlying memory, and must be filled iteratively.
This slows down update speeds for dataframes/numpy arrays dramatically, and is an extremely common case given that most numpy arrays are defined as `float64`, and that users may prefer the truncation of unnecessary decimal points. By converting the `float64` array to `int64` before the C++ numpy loader attempts to load the update dataset, the array is made copyable and thus can be loaded with a massive (4-6x) speed increase over iterative fills.
Converting arrays from float to int maintains order and …
> When updating tables typed as `int` with `float64` numpy arrays, copy instead of filling iteratively

- packages/perspective-viewer-datagrid/src/js/scroll_panel.js
- packages/perspective-viewer-datagrid/src/js/table.js
- packages/perspective-viewer-datagrid/src/js/tbody.js
- packages/perspective-viewer-datagrid/src/less/container.less
- packages/perspective-viewer-datagrid/src/less/material.less
- packages/perspective-viewer/src/less/viewer.less
Assorted fixes for `@finos/perspective-viewer-datagrid`s scrolling, and adds OSX-style overlay scrollbars to all `<perspective-viewer>` scrollable content, for sad Windows users.
Fixes #602
> Datagrid virtual scroll fixes and `-webkit-scrollbar` CSS

- .gitignore
- cpp/perspective/CMakeLists.txt
- cpp/perspective/src/cpp/config.cpp
- cpp/perspective/src/cpp/context_zero.cpp
- cpp/perspective/src/cpp/emscripten.cpp
- cpp/perspective/src/cpp/gnode.cpp
- cpp/perspective/src/include/perspective/utils.h
- docker/emsdk/Dockerfile
- packages/perspective-bench/src/js/bench.js
Rebased & updated version of #958, moved to a branch on this repo, with updated `dockerfile` for new images and a further upgrade to emscripten 1.39.12.  Per this version's release notes, `MAXIMUM_MEMORY` has been set to enable unsigned pointers & 4gb+ heaps for Emscripten.
Alas, this version still does not pass Perspective's test suite, so cannot currently be merged.
> Update to emsdk 1.39.12 and remove 2gb MAXIMUM_MEMORY

- python/perspective/perspective/manager/manager.py
- python/perspective/perspective/table/_date_validator.py
- python/perspective/perspective/tests/manager/test_manager.py
- python/perspective/perspective/tests/table/test_table_arrow.py
- python/perspective/perspective/tests/table/test_table_datetime.py
- python/perspective/perspective/tests/table/test_table_infer.py
This PR fixes a few small bugs in `perspective-python`:
- `NaN`, `Infinity`, and `-Infinity` are no longer serialized into JSON by `PerspectiveManager`, and any remote calls into `PerspectiveManager` that returns a result with `NaN` inside will be rejected on the client-side. The server will not raise an Exception, but the exception will be visible inside the client browser console. 
Perspective's data loading and model treats `None` or `null` as invalid values, and the Javascript value `undefined` as a value for "nothing exists in this cell". To the extent possible, Perspective will strip and treat `NaN`s as `None` (in Python) or `null` (in Javascript). 
A case where `NaN`s cannot be coerced to `None` is in Arrows with columns that contain `NaN` values but do not have the `null_count` or …
> Fix minor bugs in Perspective datetime + NaN handling

- packages/perspective-bench/package.json
- packages/perspective-viewer-d3fc/package.json
- packages/perspective-viewer-datagrid/package.json
- packages/perspective-viewer-highcharts/package.json
- packages/perspective-viewer-hypergrid/package.json
- packages/perspective-viewer/package.json
- packages/perspective-workspace/package.json
- packages/perspective/package.json
Adds support for [JSDelivr](https://jsdelivr.com) metadata, such that links like [https://cdn.jsdelivr.net/npm/@finos/perspective-viewer](https://cdn.jsdelivr.net/npm/@finos/perspective-viewer) point to the CDN version of Perspective, rather than the CJS version.
> Adds jsdelivr package.json metadata

- cpp/perspective/src/cpp/data_table.cpp
- cpp/perspective/src/cpp/emscripten.cpp
- python/perspective/perspective/src/table.cpp
- python/perspective/perspective/tests/table/test_update_arrow.py
This PR reproduces and fixes a segmentation fault with arrow updates and string reallocation - previously, the `psp_okey` column was being duplicated incorrectly on an Arrow update, and this turned out to be the cause of a few different segfaults that became trivially reproducible (and has been reproduced and tested in the Python tests).
Removing the incorrect duplication fixes the tests and seems to (for now) prevented any further segfaults related to this issue.
> Remove duplicate `psp_okey` column from arrow updates

- packages/perspective-viewer/src/js/computed_expressions/lexer.js
> Restore firefox support by removing captrue group from regex pattern

- packages/perspective-test/src/js/index.js
- packages/perspective-viewer-datagrid/src/js/datagrid.js
- packages/perspective-viewer-datagrid/src/js/events.js
- packages/perspective-viewer-datagrid/src/js/index.js
- packages/perspective-viewer-datagrid/src/js/scroll_panel.js
- packages/perspective-viewer-datagrid/src/js/table.js
- packages/perspective-viewer-datagrid/src/js/tbody.js
- packages/perspective-viewer-datagrid/src/js/thead.js
- packages/perspective-viewer-datagrid/src/less/container.less
- packages/perspective-viewer-datagrid/src/less/material.less
- packages/perspective-viewer-datagrid/test/js/scrolling.spec.js
- packages/perspective-viewer-datagrid/test/results/linux.docker.json
- packages/perspective-viewer/src/html/viewer.html
- packages/perspective-webpack-plugin/README.md
- packages/perspective-workspace/src/js/workspace/workspace.js
Reorganizes `<perspective-datagrid>` DOM structure thusly:
```html
<perspective-viewer>
<perspective-datagrid>
<table></table>
</perspective-datagrid>
</perspective-viewer>
```
.. with `perspective-datagrid` element itself acting as the scroll container.  This means you should:
* Listen to `scroll` events from this element
* Call its `scrollTop` to move.
* Use it to access methods like `get_tds()`.
> Styleable scroll-area for `@finos/perspective-viewer-datagrid`

- docs/md/js.md
On the documentation page:
It says:
Perspective offers these plugin modules: @finos/perspective-viewer-d3fc A custom high-performance data-grid component based on HTML <table>.
Expected Result:
Perspective offers these plugin modules: @finos/perspective-viewer-datagrid A custom high-performance data-grid component based on HTML <table>.
Resolves #1056
> Fixed typo on documentation page

- packages/perspective-viewer/src/js/computed_expressions/lexer.js
- packages/perspective-viewer/src/js/computed_expressions/widget.js
This PR fixes a regression in a regular expression pattern that used a named capturing group. It was previously fixed by @telamonian, but I accidentally re-introduced it by using the old broken regex expression in a different place while building the autocomplete.
> Fix regression in regex for Firefox

- .eslintrc.json
- docs/i18n/en.json
- docs/md/concepts.md
- docs/md/development.md
- docs/md/installation.md
- docs/md/js.md
- docs/md/python.md
- docs/static/css/material.dark.css
- examples/simple/superstore.html
- package.json
- packages/perspective-viewer/README.md
- packages/perspective-viewer/src/js/viewer.js
- packages/perspective/README.md
- packages/perspective/src/js/perspective.js
- python/perspective/docs/perspective.core.rst
- python/perspective/perspective/manager/manager.py
- python/perspective/perspective/table/table.py
- python/perspective/perspective/table/view.py
- python/perspective/perspective/tornado_handler/tornado_handler.py
- python/perspective/perspective/viewer/viewer.py
- yarn.lock
This PR adds `eslint-plugin-markdown` and applies auto-formatting fixes to Javascript code blocks in our markdown documentation.
Additionally it fixes some formatting issues with the Python documentation, adds `PerspectiveTornadoHandler` to the Python documentation, as well as fixes typos, makes improvements & adds examples to both JS and Python docs.
> Run ESLint on documentation + minor documentation improvements

- .eslintrc.json
- .gitattributes
I've added a rule to catch the CRLF formatting in the ESlint config. However, according to https://eslint.org/docs/rules/linebreak-style the problem would appear to lie at least partly in the way git automatically converts the formatting on windows machines (although it's possibly coming from the windows based code editors. to quote:
If you use git, you may want to add a line to your .gitattributes file to prevent git from converting linebreaks in .js files:
*.js text eol=lf
So I've added that line to the .gitattributes as well.
Please note that this pull request doesn't change all the existing files with CLRF end of line sequences, but should help for future changes. If you'd like me to submit an additional pull request for existing files or work it into this one please let me know.
> Fix for CRLF issue 

- azure-pipelines.yml
- cmake/arrow/CMakeLists.txt
- cpp/perspective/CMakeLists.txt
- cpp/perspective/src/cpp/arrow_loader.cpp
- cpp/perspective/src/cpp/computed.cpp
- cpp/perspective/src/cpp/scalar.cpp
- python/perspective/perspective/src/utils.cpp
- python/perspective/perspective/tests/conftest.py
- python/perspective/perspective/tests/table/test_table_arrow.py
- python/perspective/perspective/tests/table/test_table_datetime.py
- python/perspective/perspective/tests/table/test_update_arrow.py
- python/perspective/perspective/tests/table/test_view.py
- scripts/build_python.js
- scripts/script_utils.js
- scripts/test_python.js
This PR cleans up the Python build by removing vestigial code in CMakeLists and refactoring build scripts, as well as fixes to datetime handling:
- Streamlines CMakeLists & Python build/test scripts
* Removes boost.filesystem from required dependencies
* makes `find_package(Boost)` **required** for Python build
* tests the selected `python` command before running, and defaults to `python` if the selected command (`python3.7`) etc. is not found
* Refactors `test_python.js`
- Fixes #1084 - the full set of type interactions when updating `Table` with an arrow is now mapped out and tested.
- Replaces `put_time` with `strftime` using a 64-char string buffer
* The maximum datestring that can be printed (10000-01-01 12:34:56:999999) is 27 chars, so this can be optimized a little further probably …
> Cleans up CMakeLists & Python build scripts, fixes datetime string rendering

- examples/workspace-editing/README.md
- examples/workspace-editing/package.json
- examples/workspace-editing/src/index.html
- examples/workspace-editing/src/index.js
- examples/workspace-editing/src/index.less
- examples/workspace-editing/webpack.config.js
- packages/perspective-viewer-hypergrid/src/js/editors.js
- python/perspective/examples/client_server_edits.py
This PR adds `examples/workspace-editing`, which implements the `client_server_editing` example from `perspective-python` in a `perspective-workspace`. It is designed to be run in parallel with `client_server_editing.py` in the Python examples folder, and provides a simple, self-contained and annotated demonstration of Perspective's client/server editing capabilities.
This PR also fixes an issue in the Hypergrid plugin that was preventing edits from being tracked when using a remote server and in `perspective-workspace`.
> Add client/server editing example, fix hypergrid to allow editing in workspace

- packages/perspective/src/js/perspective.js
- packages/perspective/test/js/to_format.js
- python/perspective/perspective/table/_data_formatter.py
- python/perspective/perspective/tests/table/test_to_format.py
This PR prevents `to_format` from being called with float start/end row and column indices, and unifies behavior across Javascript and Python bindings. This fixes an issue with `perspective-datagrid` where float start/end row indices were being sent to a `perspective-python` Table, and rejected by a C++ function whose parameters were integers.
For `start_row` and `start_col`, `floor` is called - so requesting a start row of `0.3` would start at `0`, and not at `1`. For `end_row` and `end_col`, `ceil` is called so that an end row of `1.2` would return `2`, and not 1. This means that the data window should never be smaller than requested by the plugin.
> Explicitly floor start row/col and ceil end row/col

- docs/md/js.md
- examples/simple/index.html
- examples/simple/superstore.html
- package.json
- packages/perspective-jupyterlab/package.json
- packages/perspective-viewer-highcharts/package.json
- packages/perspective-viewer-highcharts/src/config/lite.config.js
- packages/perspective-viewer-highcharts/src/js/highcharts/base.js
- packages/perspective-viewer-highcharts/src/js/highcharts/draw.js
- packages/perspective-viewer-highcharts/src/js/highcharts/externals.js
- packages/perspective-viewer-highcharts/src/js/lite.js
- yarn.lock
Adds a new entry point, `@finos/perspective-viewer-highcharts/lite`, which allows importing this plugin without invoking module side effects prevalent in Highcharts, allowing this plugin to be embedded easily alongside sloppier implementations which also rely on these modules - explained in detail [here](https://github.com/highcharts/highcharts/issues/7729).  In order to use `@finos/perspective-viewer-highcharts/lite`, these extension module effects will need to be imported and applied, in the correct order:
```javascript
import highcharts from "highcharts";
import highchartsMore from "highcharts/highcharts-more";
import heatmap from "highcharts/modules/heatmap";
import boost from "highcharts/modules/boost";
import treemap from "highcharts/modules/treemap";
import sunburst from …
```
> `perspective-viewer-highcharts-lite`

- packages/perspective-webpack-plugin/src/js/utils.js
Updates Perspective's cross-origin Web Worker and Wasm loading logic to use [`document.currentScript`](https://developer.mozilla.org/en-US/docs/Web/API/Document/currentScript).  In the before times, the long-long ago, we supported a browser called Internet Explorer 8, which led to some highly questionable logic for determining the path of these assets, throwing an `Error` and parsing the stack trace ...
I expect this will fix issues #1139 and possibly #1128 - but I can't say for sure until 0.5.3 is released, as the specific interplay of this issue was only detected due to how `unpkg.com` resolves `browser` alias fields in `package.json`.
> Fix path resolution for cross-origin assets

- cpp/perspective/src/cpp/arrow_loader.cpp
- cpp/perspective/src/cpp/emscripten.cpp
- cpp/perspective/src/include/perspective/arrow_loader.h
- packages/perspective-viewer-d3fc/src/js/charts/treemap.js
- packages/perspective-viewer/test/js/regressions.spec.js
- packages/perspective/test/js/updates.js
- python/perspective/perspective/src/table.cpp
- python/perspective/perspective/tests/table/test_update_arrow.py
This PR implements and tests the ability for tables to be updated with arrows that have more/less columns than the table's schema - i.e. the table's schema will always be respected when reading through the arrow binary. If a column exists in the arrow binary but does not in the schema, it will be skipped, and vice versa - if a column exists in the schema and not in the arrow binary, it will not be filled. Additionally, this PR fixes an issue where an integer index column would cause an error when it was updated with an arrow - index columns will not be promoted, and filled through iteration instead.
> Enable updates from arrows that have more/less columns than the Table schema

- docs/md/development.md
Changed the Emscripten version in the developer guide markdown (development.md) from 1.38.47 to 1.39.13.  Updated the version number for reference and the script used to install the Emscripten SDK.  Related to issue #1121 .
> Updated development.md to show correct Emscripten version.

- cpp/perspective/src/cpp/gnode.cpp
- cpp/perspective/src/include/perspective/gnode.h
- packages/perspective/test/js/computed.js
- packages/perspective/test/js/computed/functionality.js
- packages/perspective/test/js/pivots.js
- python/perspective/perspective/tests/core/test_aggregates.py
- python/perspective/perspective/tests/table/test_view.py
- python/perspective/perspective/viewer/validate.py
- python/perspective/perspective/viewer/viewer_traitlets.py
This PR fixes a regression in gnode `_process_table`, which would notify contexts with a new update dataset before updating the master table maintained by the gnode state. This caused a problem with certain aggregates such as mean and avg, which read from gnode state.
The problem emanates from a specific code path - a table is created with a schema, and a pivoted view with a mean/avg/etc. aggregate is created, and _then_ update is called. If the table is not updated again/a new context is not created, the aggregate values return null as they have been notified with a stale version of the gnode state. In the viewer, it was easy to miss this bug - making any UI changes would create a fresh context, which would make the issue disappear as the contexts were re-synchronized to the latest gnode …
> Fix issue where contexts were being notified before gnode state was updated

- packages/perspective-jupyterlab/src/config/plugin.config.js
- packages/perspective-jupyterlab/src/config/webpack.config.js
- packages/perspective-jupyterlab/src/ts/index.ts
- packages/perspective-viewer-d3fc/src/js/charts/charts.js
- packages/perspective-viewer-highcharts/src/js/highcharts/highcharts.js
This PR fixes issues #1129 and #1130 by matching the order of the plugins between Highcharts and d3fc: 
_Highcharts_
_d3fc_
Additionally, this PR removes the use of `perspective-viewer-hypergrid` and `perspective-viewer-highcharts` plugins from `PerspectiveWidget` in JupyterLab, and replaces them with `perspective-viewer-datagrid` and `perspective-viewer-d3fc`.
> Fix #1129 and #1130, remove Highcharts and Hypergrid from PerspectiveWidget

- python/perspective/perspective/include/perspective/python.h
- python/perspective/perspective/include/perspective/python/utils.h
- python/perspective/perspective/libpsp.py
- python/perspective/perspective/src/utils.cpp
- python/perspective/perspective/tests/core/test_threadpool.py
For Python, adds the method `perspective.set_threadpool_size(nthreads)`, which allows overriding the TBB thread pool size up to `tbb::task_scheduler_init::default_num_threads()`, which can be reset by calling this method with `None` or `-1`.  Also adds an ineffectual ("smoke") test to validate that invoking this method does not otherwise crash.  Fixes #1145
> Adds `set_threadpool_size()`

- packages/perspective-viewer-d3fc/src/js/data/treeData.js
- packages/perspective-viewer-d3fc/src/js/series/sunburst/sunburstClick.js
- packages/perspective-viewer-d3fc/src/js/series/sunburst/sunburstLabel.js
- packages/perspective-viewer-d3fc/src/js/series/sunburst/sunburstSeries.js
- packages/perspective-viewer-d3fc/src/js/series/treemap/treemapSeries.js
- packages/perspective-viewer-d3fc/src/js/series/treemap/treemapTransitions.js
- packages/perspective-viewer-d3fc/src/js/tooltip/selectionData.js
- packages/perspective-viewer-d3fc/test/js/integration/sunburst.spec.js
- packages/perspective-viewer-d3fc/test/js/integration/treemap.spec.js
- packages/perspective-viewer-d3fc/test/js/unit/tooltip/generateHTML.spec.js
- packages/perspective-viewer-d3fc/test/results/linux.docker.json
#1144 reports an issue where date labels were not correctly formatted in the d3fc package. Treedata has been modified to add a new attribute `label` which is a properly formatted value. 
JS tests added to check dates are displayed with consistent format for Treemap and Sunburst. Additionally a test was updated to check for a consistent format which was used in the highcharts package.
> fix(perspective-viewer-d3fc): show formatted dates on treemap and sunburst (1144)

- cpp/perspective/src/cpp/view.cpp
- python/perspective/perspective/table/_data_formatter.py
- python/perspective/perspective/tests/table/test_to_format.py
Retrieving data from a `View` can be controlled via the `start_row`/`end_row` and `start_col`/`end_col` arguments to `to_json`, which are parsed in a similar fashion to Python's `range` - inclusive of `start` and stopping at `end - 1`. 
Invalid data windows - where `start > end` or `start == end` - are handled by returning empty data. However, in the special case of two-sided sorted views, it did not correctly handle invalid data windows while constructing a column indices vector, and would segfault or throw a ValueError.
This does not raise an issue with the viewer/plugins - the data window requested by `perspective-viewer` will be valid, even if the viewport is extremely small. However, this interferes with a Websocket testing suite I'm currently building, which randomly generates data …
> Fix segfault and errors on 2-sided sorted views when data window is invalid

- .github/PULL_REQUEST_TEMPLATE/Bugfix.md
- .github/PULL_REQUEST_TEMPLATE/Documentation.md
- .github/PULL_REQUEST_TEMPLATE/Feature.md
I've added new PR templates for three categories:
- Bugfix: fixes towards reported bugs on our Issues page
- Documentation: additions/edits to API or Docusaurus documentation
- Feature: A new feature addition to Perspective
@texodus I've added them in the same form as our issue templates, so we should be able to get the same sort of selector window that happens with issue templates - the GitHub docs are a little unclear about whether PR templates will work in the same way with the nice picker. If it doesn't work, however, happy to coalesce into one template.
> Adds PR templates for bugfix, documentation, and feature

- cpp/perspective/src/cpp/context_zero.cpp
- cpp/perspective/src/cpp/view.cpp
- cpp/perspective/src/include/perspective/context_zero.h
- packages/perspective-bench/bench/perspective.benchmark.js
- packages/perspective-bench/bench/versions.js
- packages/perspective-bench/src/js/browser_runtime.js
- packages/perspective/src/js/perspective.js
- packages/perspective/test/js/computed/deltas.js
- packages/perspective/test/js/delta.js
- python/perspective/perspective/tests/table/test_view.py
#1159 reported an issue where row deltas were empty in tables after their first update from schema. This was due to the `notify` calls for first and subsequent updates being on different code paths (with different invocations of `notify`), and the line that added the primary key to be tracked as a changed row was missing. This PR fixes the issue, and adds a litany of tests in Javascript and Python.
Additionally, this PR fixes a previously overlooked issue - though we enable delta calculation based on whether they are used in on_update or not, 0-sided contexts would always calculate step and row deltas regardless of whether they were enabled or not. This seemed to be a default - `get_deltas_enabled` would always return `true`, and `set_deltas_enabled` would be a no-op for zero sided …
> Fixes #1159 - deltas are now generated on first update for 0-sided contexts

- examples/remote-workspace/src/index.js
- packages/perspective-viewer/src/config/umd.config.js
- packages/perspective-viewer/src/less/viewer.less
- packages/perspective-workspace/src/less/menu.less
- packages/perspective-workspace/src/less/tabbar.less
- packages/perspective/src/js/api/server.js
* Fixes #1013 
* Lightens scrollbar styling.
* Fixes `perspective-workspace` context menu color when invoked over global filter (e.g. in dark theme).
* Fixes a theme quirk that causes `perspective-workspace` tab bars to flash when the context menu is invoked.
* Fixes node.js `remote-workspace` example.
> `perspective-workspace` CSS fixes

- packages/perspective-viewer-datagrid/package.json
- packages/perspective-viewer-datagrid/src/js/plugin.js
- packages/perspective-viewer-datagrid/src/js/sorting.js
- packages/perspective-viewer-datagrid/src/less/regular_table.less
- packages/perspective-viewer-datagrid/test/results/linux.docker.json
- packages/perspective-workspace/test/results/linux.docker.json
- yarn.lock
This PR fixes the click-to-sort feature of `@finos/perspective-viewer-datagrid` to use the API of the `<perspective-viewer>` element in which it is embedded to create a new `View()`, rather than invoking one directly, using coordinated `regular-table` fix from version `0.1.1`.
> Fix `perspective-viewer-datagrid` sorting

- cpp/perspective/src/cpp/computed_function.cpp
- examples/promo/script.js
- examples/promo/src/index.js
- examples/promo/webpack.config.js
- packages/perspective/src/js/perspective.js
* Fixes the `promo` example project to use the `perspective-workspace` 0.5.2 API.
* Fixes the `second_bucket` computed function, which did not call `floor()`, as well as the `promo` example project which relied upon this behavior.
> `promo` example project update and computed function fix

- packages/perspective-viewer/src/js/row.js
- packages/perspective-viewer/src/js/viewer/dragdrop.js
Fixes a long-time issue which caused drag/drop elements on a `<perspective-viewer>` element to sometimes become _stuck_ in a `dragover` state.
> Fix sticky dragdrop on `perspective-viewer`

- cpp/perspective/CMakeLists.txt
https://blog.tim-smith.us/2015/09/python-extension-modules-os-x/
> Remove linking against python

- docs/md/python.md
- examples/tornado-python/server.py
- examples/tornado-streaming-python/server.py
- packages/perspective/src/js/api/client.js
- python/perspective/bench/giltest.py
- python/perspective/perspective/client/client.py
- python/perspective/perspective/client/dispatch.py
- python/perspective/perspective/include/perspective/python.h
- python/perspective/perspective/include/perspective/python/utils.h
- python/perspective/perspective/manager/manager.py
- python/perspective/perspective/manager/manager_internal.py
- python/perspective/perspective/src/serialization.cpp
- python/perspective/perspective/src/table.cpp
- python/perspective/perspective/src/utils.cpp
- python/perspective/perspective/src/view.cpp
- python/perspective/perspective/tests/core/test_async.py
- python/perspective/perspective/tests/manager/test_manager.py
- python/perspective/perspective/tornado_handler/tornado_client.py
- python/perspective/perspective/tornado_handler/tornado_handler.py
- scripts/bench.js
Adds `set_loop_callback()` public method to the `PerspectiveManager` class, which takes as an argument a loop-queueing function, such as asyncio `call_soon()` and Tornado `add_callback()`.  Once invoked, Perspective will presume to be owned by the calling thread, and will release the Python GIL for the bulk of reading/writing Apache Arrow data, as well as calculating
new `View` contexts.  There are some new restrictions in this mode, namely that Perspective is no longer thread safe, covered in the documentation.
> GIL release for perspective-python Async mode

- cpp/perspective/CMakeLists.txt
- cpp/perspective/src/cpp/gnode.cpp
- cpp/perspective/src/cpp/pool.cpp
- cpp/perspective/src/cpp/pyutils.cpp
- cpp/perspective/src/cpp/view.cpp
- cpp/perspective/src/include/perspective/gnode.h
- cpp/perspective/src/include/perspective/pool.h
- cpp/perspective/src/include/perspective/pyutils.h
- cpp/perspective/src/include/perspective/view.h
- python/perspective/perspective/include/perspective/python.h
- python/perspective/perspective/include/perspective/python/serialization.h
- python/perspective/perspective/include/perspective/python/table.h
- python/perspective/perspective/include/perspective/python/utils.h
- python/perspective/perspective/include/perspective/python/view.h
- python/perspective/perspective/manager/manager.py
- python/perspective/perspective/manager/manager_internal.py
- python/perspective/perspective/src/serialization.cpp
- python/perspective/perspective/src/table.cpp
- python/perspective/perspective/src/utils.cpp
- python/perspective/perspective/src/view.cpp
- python/perspective/perspective/tests/core/test_async.py
Releases the Python GIL during `Table()` calls, as well as `table.update()`, `table.remove()` and anything else which triggers the internal `gnode._process()` method for calculating conflated updates.
Additionally, `test_async.py` has been rewritten to test `PerspectiveManager()` on parallel threads, carefully preserving calling thread state.
> Release GIL for `Table` methods

- examples/tornado-python/server.py
- packages/perspective-jupyterlab/src/ts/client.ts
- packages/perspective-jupyterlab/src/ts/view.ts
- packages/perspective-jupyterlab/test/js/unit/view.spec.js
- packages/perspective/src/js/perspective.node.js
- packages/perspective/src/js/websocket.js
- packages/perspective/test/js/remote.spec.js
- python/perspective/perspective/manager/manager.py
- python/perspective/perspective/manager/manager_internal.py
- python/perspective/perspective/tests/tornado_handler/test_tornado_handler.py
- python/perspective/perspective/tests/tornado_handler/test_tornado_handler_chunked.py
- python/perspective/perspective/tornado_handler/tornado_client.py
- python/perspective/perspective/tornado_handler/tornado_handler.py
- python/perspective/perspective/widget/widget.py
This PR implements chunked sending/chunked loading of binaries in Perspective's websocket implementations in both Python and Javascript. Apache Arrow binaries above a certain size will be sent to the Perspective client in chunks, which prevents the Websocket from locking on a particularly large binary and closing due to a timeout, as once that binary is on the wire all heartbeat messages/other messages are blocked from being sent/received. 
The default chunk threshold is configured to be 200MB, and arrows will be transported in 50MB chunks. In Python, these settings can be altered in the `PerspectiveManager` constructor by initializing a new `PerspectiveManager` with `chunk_threshold` and `chunk_size`, which are defined in bytes:
```python
manager = PerspectiveManager(
chunk_threshold=500 …
```
> Send large arrow binaries as chunks, add client-level Websocket heartbeat

- packages/perspective/package.json
- scripts/build_js.js
- scripts/clean.js
A small QoL developer improvement to store `build` and `release` CMake artifacts in separate directories, such that a perspective developer can switch build settings without rebuilding the entirety of the project from scratch.
> Separate 'release' and 'debug' builds

- azure-pipelines.yml
- python/perspective/perspective/tornado_handler/tornado_handler.py
- python/perspective/setup.py
`tornado.locks` is not included in the `__init__.py` of older Tornado versions, and this causes an issue when hosting Perspective servers as we don't explicitly import `tornado.locks`. This patch makes the import explicit and pins a version of Tornado for our Python 2 builds.
> Explicitly import `tornado.locks`

- packages/perspective/src/js/api/table_api.js
- packages/perspective/src/js/perspective.js
- packages/perspective/test/js/clear.js
- packages/perspective/test/js/constructors.js
- packages/perspective/test/js/updates.js
- python/perspective/perspective/client/table_api.py
- python/perspective/perspective/table/table.py
- python/perspective/perspective/table/view.py
- python/perspective/perspective/tests/manager/test_manager.py
- python/perspective/perspective/tests/table/test_table.py
- python/perspective/perspective/tests/table/test_view.py
- python/perspective/perspective/tests/widget/test_widget.py
- python/perspective/perspective/widget/widget.py
This PR adds `get_index()` and `get_limit()`, which allows for Table consumers to access the value of user-provided index columns or limits, or `null` if not set by the user. This is useful in the distributed Perspective use case, as clients need to mirror the Table exactly:
```javascript
const remote_table = websocket.open_table("table");
const remote_view = remote_table.view();
const arrow = await remote_view.to_arrow();
const index = await remote_table.get_index();
const client_table = worker.table(arrow, {index: index});
```
Additionally, this PR does a little internal cleanup of Perspective core code in both Javascript and Python, and adds a large amount of new tests.
> Add `get_index()` and `get_limit()` to the public API, internal code cleanup

- python/perspective/perspective/widget/widget.py
The `editable` attribute on non-server mode PerspectiveWidget was broken because `binary_length` was not removed before passing the message to the manager.
When Tornado batching and other wire API upgrades were added, we moved parsing of `binary_length` flags to the manager instead of the tornado handler. The widget did not follow suit with this change, which means it was passing `binary_length` to the manager even though the two-part message (regular, and binary) was already composed properly, which caused strange effects down the line, namely `update` was being called with the manager's JSON message instead of the dataset.
This fixes the issue, so that `editable` in `PerspectiveWidget` should be working as intended.
> Fix distributed editing in PerspectiveWidget

- azure-pipelines.yml
This PR fixes the Windows build on Azure by updating the version of boost to 1.72, which is the only pre-installed version after [this PR](https://github.com/actions/virtual-environments/issues/1847) on `virtual-environments`.
Keeping a link to the [software installed on WIndows 2016 image](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2016-Readme.md) for future reference.
**@texodus please merge this first and make sure builds work for subsequent PRs.**
> Update Azure Windows boost to 1.72

- python/perspective/perspective/tests/client_mode/test_client_mode.py
- python/perspective/perspective/widget/widget.py
This PR fixes the issue reported in #1241 - `date` and `datetime` values are now serialized properly to the widget front-end in client mode, and the serialization is now consistent between the `list`, `dict`, `numpy.array` and `pandas.DataFrame` formats.
Previously, we relied on the Widget comm serializer to convert values before passing them to the widget front-end, however this would break on `date` values and render an error. It would also convert `datetime` values to a default representation with microseconds, which could not be parsed as a string by the front-end.
This PR introspects all data in client mode in order to serialize date/datetime values to string using a format that is guaranteed to be compatible with Perspective's JS front-end, with the caveat that microseconds are …
> Fix #1241 - date and datetime values in client mode are parsed properly

- packages/perspective-viewer-datagrid/src/js/click.js
- packages/perspective-viewer-datagrid/src/js/getCellConfig.js
- packages/perspective-viewer-datagrid/src/js/plugin.js
- packages/perspective-viewer-datagrid/src/js/row_selection.js
- packages/perspective-viewer-datagrid/test/js/superstore.spec.js
- packages/perspective-viewer-datagrid/test/results/linux.docker.json
Fixes #1076 
This PR adds the perspective-click event to perspective-viewer-datagrid as specified in [the docs](https://perspective.finos.org/docs/md/js.html#click-events).
> Add perspective-click event to grid

- packages/perspective-viewer/test/js/render_warning_tests.js
- packages/perspective/test/js/pivots.js
Fixes [this test](https://dev.azure.com/finosfoundation/perspective/_build/results?buildId=1750&view=logs&j=430750e5-873f-5cdb-f7d1-334fffa69fc8&t=e9a709ee-98dc-5d78-ab76-09541ac9f110&l=1427), which flaps due to not awaiting the application of the `View()` before attempting to click the render warning dismissal.
> Fix flapping tests for render warnings

- packages/perspective-webpack-plugin/package.json
Fix: version conflict that makes `npm install` failed
Reason: perspective-webpack-plugin@0.5.6 require depends on perspective@0.4.2
Bug reproduction:
```
dependencies: {
"@finos/perspective": "^0.5.6",
"@finos/perspective-webpack-plugin": "^0.5.6",
}
```
```bash
> npm install
npm ERR! Could not resolve dependency:
npm ERR! peer @finos/perspective@"^0.4.2" from @finos/perspective-webpack-plugin@0.5.6
npm ERR! node_modules/@finos/perspective-webpack-plugin
npm ERR!   @finos/perspective-webpack-plugin@"^0.5.6" from the root project
```
> Fix: version conflict that makes `npm install` failed

- README.md
- docs/README.md
- docs/core/Footer.js
- docs/md/concepts.md
- docs/md/development.md
- docs/md/installation.md
- docs/md/js.md
- docs/md/python.md
- docs/sidebars.json
Hello,
I am submitting a few spelling and grammar revisions to the Perspective documentation; fixes were primarily made to the .md files in /docs.
Main issues:
- JavaScript capitalization typo: Javascript to JavaScript (fixed across all docs)
- Consistency fixes: timezone and time zone (fixed to time zone), webworker and Web Worker (fixed to Web Worker), perspective and Perspective (fixed to Perspective), etc.
- Other various capitalization errors
- Some variables fixed to monospace font
- Added reference links to Boost and Cmake
- Misplaced commas
> Spelling and grammar fixes in doc

- docs/md/installation.md
- docs/md/js.md
- docs/static/js/animation.js
- packages/perspective-bench/src/html/benchmark.html
- packages/perspective-viewer/src/js/viewer.js
- packages/perspective-viewer/src/js/viewer/dom_element.js
This PR removes the last traces of `viewer.load(data)` and replaces them with `viewer.load(table)`, most notable in the installation and JS user guide documentation, but also in the script that powers the website's animated Perspective Viewer. 
Additionally, I removed an unused and undocumented API that allows the user to set a "data" attribute on `perspective-viewer` - since the viewer only loads tables, this API (which I don't see any usage of nor documentation about, and the last work done on it seems to be in a commit from [November 2018](https://github.com/finos/perspective/commit/2416733dab4b8cf2cbd7421b68205cce69208824)) can fully be removed.
> Cleanup docs and examples to viewer.load(table)

- python/perspective/perspective/src/table.cpp
This PR fixes a small issue in Perspective's arrow loading code in Python - previously, the pointer to the malloc'd section for the arrow binary was never explicitly free'd (as it was in Javascript). This leads to the memory allocated for the binary leaking after the arrow is loaded into Perspective.
With testing using `psutil` and 25 updates using `superstore.arrow`, comparing memory usage with/without free() shows a significant impact:
_Without free()_:
- starting `rss`: 115539968 bytes
- ending `rss`: 302710784 bytes
_With free()_:
- starting `rss`: 113532928 bytes
- ending `rss`: 245538816 bytes
Memory usage grows much more slowly when `free()` is added, demonstrating the leak.
> free() pointer to arrow binary in Python

- cpp/perspective/src/cpp/base.cpp
- cpp/perspective/src/cpp/emscripten.cpp
- cpp/perspective/src/cpp/table.cpp
- cpp/perspective/src/cpp/view_config.cpp
- cpp/perspective/src/include/perspective/table.h
- cpp/perspective/src/include/perspective/view_config.h
- packages/perspective-bench/bench/perspective.benchmark.js
- packages/perspective-bench/bench/versions.js
- packages/perspective-bench/src/html/benchmark.html
- packages/perspective-viewer/src/html/expression_editor.html
- packages/perspective-viewer/src/js/computed_expressions/widget.js
- packages/perspective-viewer/src/js/viewer/dom_element.js
- packages/perspective-viewer/test/js/computed_expressions.spec.js
- packages/perspective-viewer/test/results/linux.docker.json
- packages/perspective/test/js/computed/expressions.js
- packages/perspective/test/js/computed/functionality.js
- python/perspective/perspective/manager/manager_internal.py
- python/perspective/perspective/src/view.cpp
- python/perspective/perspective/tests/table/test_exception.py
- python/perspective/perspective/tests/table/test_view.py
- python/perspective/perspective/tests/table/test_view_computed.py
This PR makes several bug-fixes on the View creation and computed column features of the Perspective engine.
Most notably, it introduces full validation of view configurations for invalid columns, i.e. a column that is not present in the table. While this is not an issue for most Perspective users, restoring a configuration that has invalid columns, for example, can cause issues that were previously difficult to debug. Now, all configuration options on the view are validated, and if an invalid column is specified, `abort()` is called in Javascript or a `PerspectiveCppException` will be thrown in Python with a specific error message detailing the invalid column name and where it was found.
Additionally, this PR fixes several edge cases with computed column state:
- Previously, one could …
> Validate view config in engine, fix computed column state bugs

- python/perspective/scripts/test_wheels.sh
This PR fixes #1244.
The `test_wheels` script now uses the correct version of pip according to the Python interpreter rather than the `pip` defined in `$PATH`. This caused a [failure] on the 0.6.0 mega-build; even though pip was upgraded, the test script called the wrong version of `pip` and caused the wheel import to fail.
> Fix #1244: make test_wheels script use python -m pip

- cpp/perspective/src/cpp/base.cpp
- cpp/perspective/src/include/perspective/multi_sort.h
- cpp/perspective/src/include/perspective/traversal.h
- docs/md/development.md
- packages/perspective-bench/bench/perspective.benchmark.js
- packages/perspective-bench/bench/versions.js
- packages/perspective/test/js/sort.js
- python/perspective/perspective/tests/table/test_view.py
- scripts/bench.js
> Fix for sorting via `avg` aggregated column.

- packages/perspective/test/js/updates.js
- python/perspective/perspective/table/_accessor.py
- python/perspective/perspective/tests/table/test_update.py
- python/perspective/perspective/tests/table/test_update_arrow.py
Fixes #1268 by refactoring the data loading path for dict-shaped datasets.
There are some inconsistencies between how `None` values are handled in JS and in Python. In JS, `null` and `undefined` in a dataset mean different things in a partial update:
```javascript
table = perspective.table({a: [1, 2, 3, 4], b: ["a", "b", "c", "d"], c: [10, 20, 30, 40]}, {index: "a"})
table.update({a: [3], c: [100]}) // "b" is `undefined` here, so values in `b` are not modified.
```
`undefined` resolves to a no-op, so values that are `undefined` will not be modified or overwritten. However, if the value is replaced with null:
```javascript
table.update({a: [3], b: [null], c: [100]}) // "b" is explicitly "null", which will unset the value at "b" for pkey `3` and set it to null.
```
To remedy this, the …
> Fix partial updates in Python using dicts

- docs/md/development.md
- docs/md/python.md
- docs/static/css/custom.css
- docs/static/css/material.dark.css
- docs/static/js/animation.js
- package.json
- packages/perspective-jupyterlab/package.json
- packages/perspective/src/js/perspective.js
- scripts/jlab_link.js
- scripts/script_utils.js
This PR fixes #1299 by adding `yarn jlab_link`, which uses `yarn link` to force Jupyterlab to pull `@finos-perspective*` packages from a local development directory instead of from NPM. As of `v0.6.0`, developers are no longer able to see their local directory changes to packages other than `@perspective-jupyterlab` in Jupyterlab, as Jupyterlab is pulling these packages from NPM during `jupyter lab build`. We used to inline the entirety of Perspective into the Jupyterlab plugin, but this is inefficient for dists and not a great development practice.
Using `yarn jlab_link`, developers are now able to see their local changes inside the Jupyterlab plugin, and the dist has not been changed to inline Perspective. Instead, developers should `yarn link` all Perspective packages inside the …
> Add `jlab_link` script to link local changes into development Jupyterlab

- packages/perspective-webpack-plugin/package.json
This PR removes webpack as a peerDependency for `@finos/perspective-webpack-plugin`
IMO, a peer dependency (or dependency) should only be included if it's actually required by the source code. (For the same reason, `file-loader` and `worker-loader` _should_ be included because they're implicitly required.) Keeping this peerDependency makes it so that the consuming package has to declare webpack as a dependency, even if they're only passing the plugin to a tool that transitively uses webpack.
> Remove webpack as a peerDependency for the webpack plugin

- cpp/perspective/src/cpp/context_zero.cpp
- packages/perspective/test/js/filters.js
This puts back a return statement that was erroneously removed in t_ctx0::notify, which caused filtered contexts to fail when updates were read out. I've added a test for this issue and verified the breakage before the fix was applied.
> Fix missing return in ctx0::notify

- packages/perspective-viewer-datagrid/package.json
- packages/perspective-viewer-datagrid/src/js/plugin.js
- packages/perspective-viewer-datagrid/src/js/regular_table_handlers.js
- packages/perspective/src/config/common.config.js
- yarn.lock
Upgrades the `regular-table` dependency to `0.2.1` from `0.1.5` [changelog](https://github.com/jpmorganchase/regular-table/blob/master/CHANGELOG.md#v015-2020-09-21), mainly adding support for incremental rendering and the `invalidate()` API for dimension-altering styles.
In implementing the change, I've also pulled the source from `perspective.md` into `@finos/perspective-viewer-datagird` directly and simplified it a bit to trade performance for readability.  I've also moved the style callbacks to use `perspective.config.js`  - this will add back formatting support for types but not yet custom types (ala #1301), which I'll have to fix in a future PR when we figure out how to unify formatting between JavaScript and Python.
> Update regular-table to 0.2.1

- python/perspective/perspective/widget/widget.py
This PR fixes #1324 by using the full version in `_model_module_version` and `_view_module_version`, which should fix the scenario described in the issue.
Before, the version strings were `~{MAJOR}.{MINOR}`, so `~0.5`, `~0.6` etc. Now, the version strings are `~{MAJOR}.{MINOR}.{PATCH}`, so the exact version of Perspective as specified in the root `package.json`: `~0.6.2`, etc. With the tilde this should resolve to `0.6.2 < 0.7.0`.
> Fix #1324: use ~major.minor.patch in PerspectiveWidget versioning

- .gitignore
- cpp/perspective/package.json
- package.json
- scripts/install_emsdk.js
- scripts/run_emsdk.js
- yarn.lock
This PR replaces `emsdk-npm` fork with an inlined script of the same nature, only this one installs Emscripten under the Project root's `.emsdk` directory, rather than deep within `node_modules` where it is removed on every install.  It also conveniently fixes a regression in this module, which even surreptitious amendment to the already-forked `emsdk-npm` failed to fix due to ... mystery reasons.  Azure reports the [cache miss](https://dev.azure.com/finosfoundation/perspective/_build/results?buildId=2176&view=logs&j=430750e5-873f-5cdb-f7d1-334fffa69fc8&t=57225e1f-43e2-5ff6-cc86-707b9e1bb780), but then continues using the [removed flag](https://dev.azure.com/finosfoundation/perspective/_build/results?buildId=2176&view=logs&j=430750e5-873f-5cdb-f7d1-334fffa69fc8&t=d698da02-2f77-5ae1-6a6a-85 …
> Replace `emsdk-npm` with simple script

- packages/perspective-viewer-d3fc/src/less/chart.less
- packages/perspective-viewer/src/themes/material.less
Fixes a CSS issue with `@finos/perspective-viewer-d3fc` which causes terser to generate malformed unicode (I think ..) in the Y label for multi-Y-axis charts.  Regardless of the cause, these should not be unicode in the Material Theme which is all that Perspective has now, so this PR parameterizes these values  with  `--d3fc-y1-label--*` custom CSS rules.
EDIT
`cssnano` is the cluprit, not `terser` ... _this_ _time_ ...
> Fix D3FC label font bug

- packages/perspective/test/js/timezone/timezone.spec.js
In our suite of timezone tests, we set the timezone manually and assert that `getTimezoneOffset` is 300 (for EST). However, during Daylight Savings time (which started on Sunday, March 14th) the timezone offset is 240, and our tests did not take that into account. This PR fixes the issue and now should work for both DST and non-DST times.
> Fix timezone tests to take DST into account

- azure-pipelines.yml
- docker/python/manylinux2010/Dockerfile
- docker/python/manylinux2014/Dockerfile
- python/perspective/setup.py
- scripts/_wheel_python.js
Fixes #1334, adds py39 now that brew defaults this on OSX.
> Deprecate py27 (linux), add py39 (osx)

- docs/md/python.md
- python/perspective/perspective/manager/manager.py
- python/perspective/perspective/tests/core/test_async.py
- python/perspective/perspective/tests/manager/test_manager.py
This PR adds two methods to the `PerspectiveManager` API:
`call_loop(fn, *args, **kwargs)`: calls `fn` on the `loop_callback` of the manager, or raises a `PerspectiveError` if the loop callback is not set.
This allows users to make calls on the Perspective thread without having to deal with the `_loop_callback` property of the manager, which is ostensibly private but (until now) lacked a public API.
`get_table_names()`: Returns a list of the tables hosted on the manager by name.
A common use case is to query the managers' private `_tables` and `_views` dictionaries for users to find out which Tables/Views are hosted on a server, which is especially useful in a server-client context where the consumers of the Perspective server may be different than the author of the server. …
> Add `call_loop` and `get_table_names`

- package.json
- scripts/repl.js
This PR adds `yarn repl`, which will launch a bash shell inside our docker images for better debugging of our Python build when trying to build Linux builds/wheels locally. `yarn repl` can be used with the same options to `yarn build` and `yarn _wheel_python`, i.e. `--manylinux2010`, `--manylinux2014`, etc.
> Adds `yarn repl` to launch a shell inside our docker images

- packages/perspective/src/js/api/client.js
- packages/perspective/src/js/api/server.js
- packages/perspective/src/js/api/table_api.js
- packages/perspective/src/js/api/view_api.js
- python/perspective/perspective/manager/manager_internal.py
#1289 was a breaking change for the Perspective API, as it made Table and View constructors `async` by returning a `Promise` to the Table or View instance instead of the instance itself. Internally, the constructors would wait on the server (across the websocket or a web worker) to return a message that signaled successful Table/View creation. However, when running a Perspective client that is newer than the Perspective server, older versions of the server (i.e. all released versions right now, as the async table/view changes are not in a tagged release yet) will not return the acknowledgement message and thus Table and View constructors will block forever.
To maintain backwards compatibility, this PR adds a simple feature flag implementation on both the client and server, which allows …
> Backwards compatibility for table() and view()

- packages/perspective-webpack-plugin/index.js
- packages/perspective/src/config/common.config.js
- packages/perspective/src/config/perspective.inline.config.js
Fixes asset cross-origin loading to work correctly with new rust-based wasm packages.
> Fix cross-origin webpack defaults

- docs/md/installation.md
- docs/md/js.md
- docs/md/python.md
- docs/static/js/animation.js
- examples/blocks/src/csv/csv.js
- examples/blocks/src/dataset/index.html
- examples/blocks/src/editable/index.html
- examples/blocks/src/iex/index.js
- examples/blocks/src/mandelbrot/index.html
- examples/blocks/src/ohlc/index.html
- examples/blocks/src/streaming/streaming.js
- examples/blocks/src/workspace/workspace.js
- examples/git-history/chained.html
- examples/git-history/index.html
- examples/remote-express-typescript/assets/index.html
- examples/remote-express/index.html
- examples/tornado-python/client_server_editing.html
- examples/tornado-python/index.html
- examples/tornado-python/server_mode.html
- examples/tornado-streaming-python/index.html
- examples/webpack-cross-origin/src/index.js
- packages/perspective-bench/src/html/benchmark.html
- packages/perspective-cli/src/html/index.html
- packages/perspective-viewer-datagrid/package.json
- packages/perspective-viewer/package.json
- packages/perspective-viewer/src/js/viewer.js
- packages/perspective/src/js/perspective.node.js
- python/perspective/bench/runtime/benchmark_hosted.html
- yarn.lock
Removes `webcomponentsjs`, as there is little possibility there still exists a browser which both supports WebAssembly and not Web Components.  This saves ~100k overall on `perspective-workspace`, but if necessary projects may import this manually still to replicate previous behavior:
```javascript
import "@webcomponents/webcompoentsjs";
```
This change however deprecates all examples which used the `WebComponentsReady` event, which is no longer fired if the polyfill is not imported, causing this PR to be a breaking change.  Instead of `WebComponentsReady`, you may use the `DOMContentLoaded` event.
> Remove webcomponentsjs

- docs/md/python.md
- packages/perspective-jupyterlab/src/ts/psp_widget.ts
- packages/perspective-jupyterlab/src/ts/renderer.ts
This is a simple modification that turns on editing for our JupyterLab mime renderer plugin (the thing that lets you right click on a `csv`, `json`, or `arrow` and visualize in perspective). As a result, we now have a pivotable, sortable, filterable, **editable** csv/json/arrow viewer.
> Enable editing to mime renderer in JupyterLab

- cpp/perspective/src/cpp/aggregate.cpp
- cpp/perspective/src/cpp/gnode_state.cpp
- cpp/perspective/src/cpp/sparse_tree.cpp
- cpp/perspective/src/include/perspective/aggregate.h
- cpp/perspective/src/include/perspective/gnode_state.h
- packages/perspective/test/js/pivot_nulls.js
Fixed the `last` aggregate to preserve null values, mirroring the behavior of `last_by_index`.  It is possible to generally implement null-awareness for all aggregate types, but many (sum) cannot produce `null` and the change is non-trivial, so this PR only applies this logic to `last`.  This change may slightly impact performance of this aggregate type in theory, but the benchmark suite does not show any perceivable regression.
Fixes #1389
> Fix `last` aggregate to preserve status

- docker/docs/Dockerfile
- docker/python/manylinux2010/Dockerfile
- docker/python/manylinux2014/Dockerfile
- docs/md/installation.md
- docs/md/js.md
- scripts/install_tools.js
As of May 1, Bintray has been [sunset](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/) which causes our `install_tools.js` to fail when trying to install Boost.
This PR removes all Bintray links and replaces them with a link to the Boost artefact in JFrog, from the link provided on the Boost [website](https://www.boost.org/users/history/version_1_71_0.html). Dockerfiles have also been updated to use the JFrog link to prevent any build issues.
Additionally, it fixes the outdated docs mentioned in #1409 by removing Unpkg alias links and replacing them with direct links to the /dist/umd folder.
> Install Boost from JFrog, fix outdated docs from #1409

- packages/perspective-viewer-d3fc/src/js/charts/sunburst.js
- packages/perspective-viewer-d3fc/src/js/charts/treemap.js
- packages/perspective-viewer-d3fc/src/js/data/treeData.js
- packages/perspective-viewer-d3fc/src/js/plugin/plugin.js
- packages/perspective-viewer-d3fc/src/js/series/seriesColors.js
- packages/perspective-viewer-d3fc/src/js/series/sunburst/sunburstArc.js
- packages/perspective-viewer-d3fc/src/js/series/sunburst/sunburstColor.js
- packages/perspective-viewer-d3fc/src/js/series/sunburst/sunburstLabel.js
- packages/perspective-viewer-d3fc/src/js/series/treemap/treemapColor.js
- packages/perspective-viewer-d3fc/src/js/series/treemap/treemapSeries.js
- packages/perspective-viewer-d3fc/src/less/chart.less
- packages/perspective-viewer-d3fc/test/js/unit/data/testTreeData.js
- packages/perspective-viewer-d3fc/test/js/unit/data/treeData.spec.js
- packages/perspective-viewer-d3fc/test/js/unit/tooltip/generateHTML.spec.js
This PR adds support for `"string"` typed columns in the `Color` position in "Treemap" and "Sunburst" D3FC plugins, assigning each unique string in the column color from the series palette.
In addition, the `Sunburst" chart type has been re-vamped:
* Re-styled to a more _pie_-like appearance (as opposed to donut), without a center cutout.
* Radius calculation has been changed to take up the full width of the panel (as opposed to constant)
* Pivot depth limit of 2 has been removed.
* Parent sunburst levels are now pulled from aggregate rows (as opposed to spontaneously re-calculated).
> Color-by-string for Treemap/Sunburst

- packages/perspective-viewer-d3fc/src/js/plugin/template.js
- packages/perspective-viewer-datagrid/src/less/regular_table.less
- packages/perspective-viewer/src/themes/material.dark.less
* Fix non-leaf aggregate cache bug in d3fc which caused sunburst charts to render incorrect parent values.
* Fix strange chrome border rendering glitch in datagrid, which caused Gridcell elemenets with non-matching rowspan (or colspan) to miscalculate shared border widths.
> Fix styling bugs from CSS minification

- packages/perspective-cli/src/js/index.js
Fixes #1405, which is another incomplete regression from #1289
> Fix CLI `async` regression

- packages/perspective-viewer/src/js/utils.js
- packages/perspective-viewer/test/js/unit/throttle_promise.spec.js
- packages/perspective-workspace/src/theme/material.less
Fixes a bug in `<perspective-viewer>` which caused de-bounced UI events to fire two (rather than one) render call.
> Double-render fix

- cpp/perspective/src/cpp/view_config.cpp
- cpp/perspective/src/include/perspective/view_config.h
- packages/perspective-viewer-datagrid/src/js/regular_table_handlers.js
- packages/perspective-viewer-datagrid/test/js/superstore.spec.js
- packages/perspective-viewer-datagrid/test/results/linux.docker.json
- packages/perspective/src/js/config/constants.js
- packages/perspective/test/js/expressions/functionality.js
- packages/perspective/test/js/pivots.js
- packages/perspective/test/js/sort.js
- python/perspective/perspective/tests/table/test_view.py
This PR fixes a bug where column names that could be parsed as numbers (like the expression `1234`) did not respond correctly to column ordering and would be the first column in a pivoted view:
This was due to the way that aggregates were parsed in the C++, which happened in three separate iterations:
1. Iterate through the `columns` array, and generate default aggregates for all columns _not_ in the aggregate map
2. Iterate through the `aggregate` map (using the order generated by `Object.keys()`), and apply specified aggregates for all aggregate columns _in_ the columns array
3. Generate aggregates for hidden sort columns.
I'm not sure exactly _why_ I wrote the parsing logic the way that I did (in 2019, IIRC), but the issue it causes is simple: by ignore the column order when parsing …
> Parse aggregates in column order

- cpp/perspective/src/cpp/sparse_tree.cpp
- packages/perspective/src/js/config/constants.js
- packages/perspective/test/js/pivots.js
- python/perspective/perspective/core/aggregate.py
Updated fork of #1394
Currently uses `strlen` but this should really use the `t_vocab` extents to calculate length, however this is difficult to access currently from `sparse_tree`.
I've also removed the trailing `", "` semantically.
> Expose `join` aggregate

- docs/package.json
- packages/perspective-bench/bench/perspective.benchmark.js
- packages/perspective-bench/bench/versions.js
- packages/perspective-bench/src/js/bench.js
- packages/perspective-bench/src/js/browser_runtime.js
- packages/perspective/src/js/perspective.js
This PR fixes the currently broken benchmark suite:
- Remove versions before 0.5.0 from benchmarks, as the benchmarking results between such large version bounds is uninformative and maintenance of code that calls deprecated APIs makes the benchmarking code unwieldy and hard to read.
- Re-enables expression column tests, and fixes the broken expressions that prevented certain tests from running/created errors
- Fixes benchmark suite errors
> Fix benchmarks and remove versions pre 0.5.0 from benchmarking

- packages/perspective-viewer/src/themes/material.dark.less
- packages/perspective-workspace/src/theme/material.dark.less
- packages/perspective-workspace/src/theme/material.less
- rust/perspective-vieux/src/rust/components/expression_editor.rs
- rust/perspective-vieux/src/rust/custom_elements/expression_editor.rs
- rust/perspective-vieux/src/rust/custom_elements/vieux.rs
- rust/perspective-vieux/src/rust/exprtk.rs
Adds theme support via the `--monaco-editor--theme` CSS variable, as well as supports for Perspective's `material-dark` theme.
> Add theme support to monaco

- cpp/perspective/CMakeLists.txt
- cpp/perspective/src/cpp/computed_expression.cpp
- cpp/perspective/src/cpp/computed_function.cpp
- cpp/perspective/src/cpp/config.cpp
- cpp/perspective/src/cpp/context_grouped_pkey.cpp
- cpp/perspective/src/cpp/context_one.cpp
- cpp/perspective/src/cpp/context_two.cpp
- cpp/perspective/src/cpp/context_zero.cpp
- cpp/perspective/src/cpp/emscripten.cpp
- cpp/perspective/src/cpp/expression_tables.cpp
- cpp/perspective/src/cpp/time.cpp
- cpp/perspective/src/cpp/view.cpp
- cpp/perspective/src/cpp/view_config.cpp
- cpp/perspective/src/include/perspective/computed_expression.h
- cpp/perspective/src/include/perspective/computed_function.h
- cpp/perspective/src/include/perspective/config.h
- cpp/perspective/src/include/perspective/expression_tables.h
- cpp/perspective/src/include/perspective/time.h
- cpp/perspective/src/include/perspective/view.h
- cpp/perspective/src/include/perspective/view_config.h
- examples/workspace/src/index.js
- packages/perspective/test/js/expressions.js
- packages/perspective/test/js/expressions/conversions.js
- python/perspective/perspective/include/perspective/python.h
- python/perspective/perspective/src/view.cpp
- python/perspective/perspective/tests/table/test_view_expression.py
- rust/perspective-vieux/src/rust/exprtk.rs
This PR adds a set of type conversion functions to the expression language, which will allow users to quickly clean/coerce their data within Perspective if it is inferred as the wrong format:
- `integer(x)`: converts a column or scalar of any type to an integer. In `Perspective.js`, integers are 32-bit, thus values that overflow/underflow will be output as `null`.
- `float(x)`: converts a column or scalar of any type to a float.
- `string(x)`: converts a column or scalar of any type into a string. `date` values are output using the format `YYYY-MM-DD`, and `datetime` values are output using the format `YYYY-MM-DD HH:MM:SS`. Conversion of floats to strings can lose precision.
- `date(year, month, day)`: given a year, month (1-12), and day, create a new `date` value. This allows for parsing …
> Add integer, float, string, date, and datetime conversion functions

- cmake/arrow/CMakeLists.txt
- cpp/perspective/CMakeLists.txt
- cpp/perspective/src/cpp/arrow_csv.cpp
- cpp/perspective/src/cpp/arrow_loader.cpp
- cpp/perspective/src/cpp/column.cpp
- cpp/perspective/src/cpp/emscripten.cpp
- cpp/perspective/src/include/perspective/arrow_loader.h
- cpp/perspective/src/include/perspective/column.h
- packages/perspective/test/js/constructors.js
- python/perspective/perspective/include/perspective/python/table.h
- python/perspective/perspective/src/table.cpp
- python/perspective/perspective/table/table.py
- python/perspective/perspective/tests/core/test_async.py
- python/perspective/perspective/tests/table/test_table.py
- python/perspective/perspective/tests/table/test_table_pandas.py
- python/perspective/perspective/tests/table/test_update.py
This PR enables direct loading of CSV strings inside `perspective-python` using the Apache Arrow-based loader used in `perspective.js`. The CSV loader uses the version of `reader.cc` shipped with Apache Arrow, and not the custom `single_threaded_reader.cpp` which is implemented for the WASM binding. During the loading of CSVs, as is the case with loading regular Arrow binaries, the GIL is released by the C++ binding.
- Enables and tests load & update of CSV strings in Python library
- Unifies CMake build of Arrow CSV reader files
- Fixes a bug in Python where parsing a CSV with a null column, such as `"x,y\n1,"` would cause a segfault when trying to read into an invalid `null_bitmap_data` pointer.
> Read CSV strings in perspective-python

- azure-pipelines.yml
- scripts/_wheel_python.js
This PR adds a wheel build for Windows (tested locally to make sure it installed), and limits wheel generation on Azure Pipelines to tagged and scheduled builds only. This is especially important on Windows builds as the wheel build adds another 15-20 minutes to the entire build. Additionally, the PR also removes the MacOS Python 3.7 build from the general rotation, and limits our per-commit builds to the following:
- WebAssembly
- ManyLinux2010 Python 3.7
- Windows Python 3.7
- MacOS Catalina Python 3.9
> Build Windows wheel, limit wheel builds to scheduled and tagged builds

- python/perspective/perspective/tests/client_mode/test_client_mode.py
- python/perspective/perspective/widget/widget.py
This PR removes the use of `ipywidgets.Widget.on_displayed` from `PerspectiveWidget`, which makes `PerspectiveWidget` compatible with ipywidget >= 8.0.0.
This API was originally used for an esoteric feature: on the widget, in client mode, if the user called `widget.update` before the widget was displayed, the updates were not cached and thus silently dropped. Since the first releases of `perspective-python`, we've tremendously cleaned up our build process and now offer wheels for all platforms, which should make client mode rarely used, if at all. Thus, this feature is slated for removal to maintain our compatibility with future ipywidgets versions.
> Fixes #1340 - removes dependency on removed ipywidgets API

- cpp/perspective/src/cpp/context_grouped_pkey.cpp
- cpp/perspective/src/cpp/context_one.cpp
- cpp/perspective/src/cpp/context_two.cpp
- cpp/perspective/src/cpp/context_zero.cpp
- cpp/perspective/src/cpp/data_table.cpp
- cpp/perspective/src/cpp/expression_tables.cpp
- cpp/perspective/src/include/perspective/data_table.h
- cpp/perspective/src/include/perspective/expression_tables.h
- packages/perspective/test/js/expressions/updates.js
- python/perspective/perspective/tests/table/test_view_expression.py
This PR fixes a memory issue that was encountered on `streaming.js` and in Python, where trivial constructions of expression columns caused hard-to-debug memory errors in both Javascript and Python. After some debugging and generating a minimal repro in Python, I found the issue in the way we handle `capacity` and `size` for the expression tables that live on each context.
Specifically, during each cycle of computing the expressions, the code called `set_capacity` on each of the expression tables to match the capacity of `flattened`, and then `set_size` on each of the tables to match the size of `flattened`. However, setting the capacity of the `t_data_table` does not set the capacity of its `t_column` or `t_lstore` objects.
I added a call to `verify` for each expressions table and saw …
> Fix memory errors when streaming updates with expression columns

- binder/requirements.txt
Currently our Binder examples are broken with the following error which states that "Module `@finos/perspective-jupyterlab`, Semver range `~0.9.0` is not a valid widget":
In adding a breakpoint and checking the widget registry in JS, `@finos/perspective-jupyterlab` is not registered. This error reproduces across versions of Perspective, and could only be fixed by installing Jupyterlab `v3.0.14`. I went through the release logs and tried to find a fixed issue/enhancement pertaining to the widget registry, but did not find anything relevant. However, 3.0.14 is now no longer the newest version of Jupyterlab so this is acceptable as a fix for our public examples.
> Fix Binder by updating Jupyterlab to 3.0.14 from 3.0.9

- package.json
- packages/perspective-webpack-plugin/index.js
- packages/perspective-webpack-plugin/package.json
- Resolve loaders relative to the current package location to ensure that the `perspective` version of loaders is picked up. 
- Add required dependencies for webpack plugin, currently when installing into a repository without `string-replace-loader` builds will start failing due to the missing dependency.
> Add required dependencies for webpack plugin

- docs/js/concepts.js
- docs/js/examples.js
- docs/js/features.js
- docs/js/fonts.js
- docs/js/index.js
- docs/pages/en/index.js
- docs/siteConfig.js
- docs/static/css/custom.css
- docs/webpack.config.js
- examples/blocks/src/citibike/index.html
- examples/blocks/src/csv/index.html
- examples/blocks/src/editable/index.html
- examples/blocks/src/movies/index.html
- examples/blocks/src/olympics/index.html
- examples/blocks/src/streaming/index.html
- examples/blocks/src/superstore/index.html
- examples/blocks/src/workspace/index.html
- examples/workspace/src/index.html
- package.json
- rust/perspective-vieux/src/rust/custom_elements/vieux.rs
- rust/perspective-vieux/src/rust/renderer.rs
- yarn.lock
* Adds [`webfontloader`](https://github.com/typekit/webfontloader) font loading for `docs` and `examples` projects that use the Material themes, in order to suppress [FOUT](https://css-tricks.com/fout-foit-foft/).
* Couples `.view()` and `draw()` calls within the same transaction, such that updates which are queue-d do not render.
* Adds a throttle control to the `docs` site, so users can disable the animation if they wish (or speed it up).  Also changes hover-activate chart type buttons into click-activate.
> Preload fonts

- packages/perspective-viewer/src/js/viewer/dom_element.js
Reverts filter limiting behavior of #1282.  This behavior is not present on the #1488 branch, but in order to alleviate upgrade hurdles, this PR backports this change to `v0.10.x`.
> Remove filter limit

- packages/perspective/test/js/expressions/conversions.js
- rust/perspective-vieux/src/rust/config/view_config.rs
This fixes an issue where some aggregates (`stddev`, `var`, and `first by index`) are not working in the viewer because they were not added to the `ViewConfig` aggregate in `perspective-vieux`.
> Add new aggregates to ViewConfig enum

- rust/perspective-vieux/src/rust/config/view_config.rs
Fixes #1520 for `0.10.x` (backported from #1488)
> Fix support for array-like filter terms

- cmake/modules/FindFlatbuffers.cmake
- docs/md/development.md
- scripts/lint_python.js
- scripts/test_python.js
This PR fixes the build for `perspective-python` on Apple's M1 architecture by fixing the Flatbuffer find path to use `opt/homebrew`, the default install location for M1. We don't currently publish any M1 wheels but following the [developer documentation](https://perspective.finos.org/docs/md/development.html) will lead to a successful installation.
The developer docs are also improved in this PR to give it a more readable structure + remove deprecated docs about Python 2.
> Fix M1 (Apple Silicon) build for `perspective-python` and improve developer docs

- cpp/perspective/src/cpp/gnode.cpp
- cpp/perspective/src/cpp/gnode_state.cpp
- cpp/perspective/src/cpp/table.cpp
- cpp/perspective/src/include/perspective/gnode.h
- cpp/perspective/src/include/perspective/gnode_state.h
- packages/perspective-jupyterlab/test/jupyter/widget.spec.js
- packages/perspective-viewer-d3fc/test/js/integration/bar.spec.js
- packages/perspective-viewer-d3fc/test/js/integration/heatmap.spec.js
- packages/perspective-viewer-d3fc/test/js/integration/yscatter.spec.js
- packages/perspective-viewer-datagrid/test/js/superstore.spec.js
- packages/perspective-workspace/src/js/workspace/discrete.js
- packages/perspective/src/js/perspective.js
- packages/perspective/test/js/removes.spec.js
- packages/perspective/test/js/updates.js
This PR fixes #1505, #998, and #1225 by making changes to `t_gstate::get_pkeyed_table`, which is used to "seed" new views with the state of the underlying table. However, if the table had removed rows and a string primary key, it would enter a block of code that rebuilt the index column and did so with an offset of 0 if an empty string ("") was in the primary keys, and 1 otherwise. This caused the internal `psp_pkey` index column to be off-by-one, which does not appear as a problem visually but caused issues when filtering, as Perspective was now returning the wrong rows entirely in the filter.
By throughly testing the logic and removing the offending code block, the issue is fixed and filters after removes and updates should now return the correct rows. This behavior also only …
> Fix #1505, #998, #1225 - results after remove are correct

- rust/perspective-viewer/src/rust/components/column_selector.rs
Fixes incorrect section-collapse logic which caused column selector to malfunction, as reported by @sc1f
> Fix column section collapse with expressions

- azure-pipelines.yml
- python/perspective/scripts/build_sdist.sh
- python/perspective/scripts/test_wheels.sh
Adding another azure pipeline to product a clean, pypi-publishable `sdist` on each build (but especially on the tagged release builds).
> add some light sdist tests and upload sdist in CI

- packages/perspective-viewer-datagrid/src/js/plugin.js
- packages/perspective-viewer-datagrid/src/js/regular_table_handlers.js
- packages/perspective-viewer-datagrid/src/less/regular_table.less
Adds persistent column widths, as well as visual indicators when a column can be (or has been) resized.
> Persistent column widths

- packages/perspective-viewer-datagrid/src/js/editing.js
- packages/perspective-viewer-datagrid/src/js/regular_table_handlers.js
- packages/perspective-viewer-datagrid/src/less/regular_table.less
- packages/perspective-viewer-datagrid/test/results/results.json
- rust/perspective-viewer/src/less/viewer.less
- rust/perspective-viewer/src/themes/material-dense.dark.less
- rust/perspective-viewer/src/themes/material-dense.less
- rust/perspective-viewer/src/themes/material.less
Adds a default style for boolean-typed columns to `@finos/perspective-viewer-datagrid`, rather than just printing the stringified-value.  Editing is implemented as single-click toggle, which coincidentally makes it easy to make "pick" lists with editing and `<perspective-workspace>`.
> Boolean datagrid columns

- cpp/perspective/src/cpp/view_config.cpp
- packages/perspective/test/js/sort.js
- rust/perspective-viewer/src/themes/material.less
When a column which is in a pivot position is also selected as a sort column, but not a visible column, using the default aggregate (`count` or `sum`) will appear to arbitrarily re-order the pivot axis, since this aggregate value is not visible but the pivot value in the row or column header is.  Because of this, we always use `unique` as an aggregate when this condition is detected.  However, this check previously only checked that such a column was in _any_ pivot position, when really it should only apply to pivots on the same axis as the sort (e.g. row pivots with a hidden sort, or column pivots with a hidden column sort).  This PR addresses this issue and adds a test for the case.
> Fix hidden sort aggregate as `unique` only when sorted on the same axis

- python/perspective/scripts/test_wheels.sh
> Fix python wheel CI

- binder/requirements.txt
- packages/perspective-jupyterlab/src/js/view.js
- packages/perspective-jupyterlab/test/jupyter/widget.spec.js
- python/perspective/perspective/core/plugin.py
- python/perspective/perspective/tests/core/test_plugin.py
- python/perspective/perspective/tests/viewer/test_validate.py
- python/perspective/perspective/tests/viewer/test_viewer.py
- python/perspective/perspective/viewer/viewer.py
- python/perspective/perspective/viewer/viewer_traitlets.py
This PR fixes some issues with PerspectiveWidget:
- Updates were broken in the RC release but are now working
- Client-server editing is now working again
- Use one shared_worker for all widget instances, instead of a new worker per-instance
- Update binder to 3.1.14, as Jupyterlab 3.0.x has a Webpack issue that causes a parse error when importing the Widget front-end.
- Remove the MutationObserver on widget attributes as the attributes are no longer fixed on the front-end
As written in #1560, the goal for the widget is for a complete rewrite that cleans up both the Python and the JS side, and removes any dependency on traitlets. However, this PR fixes the regressions between the 1.0.0 RC release and our last release.
> Fix #1562, fix regressions in PerspectiveWidget

- packages/perspective-jupyterlab/src/js/model.js
- packages/perspective-jupyterlab/src/js/view.js
- python/perspective/perspective/tests/viewer/test_validate.py
- python/perspective/perspective/tests/viewer/test_viewer.py
- python/perspective/perspective/viewer/validate.py
- python/perspective/perspective/viewer/viewer.py
- python/perspective/perspective/viewer/viewer_traitlets.py
- scripts/jlab_link.js
- scripts/setup.js
Fixes an issue in the JupyterLab `PerspectiveWidget` Python class `filter` traitlet, which was set to `filters` in this class alone, causing the property to be mis-parsed on the client.  Though this API changed in `1.0.0` (or rather, where the API previously allowed either, only `filter` is now accepted), this is not technically a breaking change as it never worked in a release version after this (and there has been no release versions).  Even the docs for e.g. the class's constructor refer to this kwarg as `filter`.  Hence, I won't mark this `breaking` and will only become a minor perspective release - but worth noting this is still "breaking" in that pre `1.0.0` code still won't work without a rename.
I can't believe I have to add this, but please do not contact Perspective contributors …
> Fix JupyterLab widget `filter` traitlet

- rust/perspective-viewer/src/less/expression-editor.less
- rust/perspective-viewer/src/rust/components/column_selector.rs
- rust/perspective-viewer/src/rust/components/config_selector.rs
- rust/perspective-viewer/src/rust/components/containers/dragdrop_list.rs
- rust/perspective-viewer/src/rust/components/containers/dropdown.rs
- rust/perspective-viewer/src/rust/components/containers/split_panel.rs
- rust/perspective-viewer/src/rust/components/expression_editor.rs
- rust/perspective-viewer/src/rust/components/expression_toolbar.rs
- rust/perspective-viewer/src/rust/components/filter_item.rs
- rust/perspective-viewer/src/rust/components/pivot_item.rs
- rust/perspective-viewer/src/rust/config/aggregates.rs
- rust/perspective-viewer/src/rust/config/view_config.rs
- rust/perspective-viewer/src/rust/custom_elements/expression_editor.rs
- rust/perspective-viewer/src/rust/dragdrop.rs
- rust/perspective-viewer/src/rust/session.rs
- rust/perspective-viewer/src/rust/session/metadata.rs
- rust/perspective-viewer/src/rust/utils/js_object.rs
- rust/perspective-viewer/src/rust/utils/mod.rs
- rust/perspective-viewer/test/js/expressions.spec.js
- rust/perspective-viewer/test/results/results.json
This PR makes the Expression Editor's contents persistent, even when not saved e.g. when focus is lost.  This works even in the case where e.g. the expression column is moved while the expression is in an edited state.  A `Reset` button had also been added to reset the editor's contents to reflect the current `View` state.
> Persist edited expressions and add 'Reset' button

- cpp/perspective/src/cpp/computed_expression.cpp
- cpp/perspective/src/cpp/computed_function.cpp
- cpp/perspective/src/include/perspective/computed_expression.h
- cpp/perspective/src/include/perspective/computed_function.h
- packages/perspective/src/js/perspective.js
- packages/perspective/test/js/expressions/conversions.js
- packages/perspective/test/js/expressions/functionality.js
- packages/perspective/test/js/expressions/numeric.js
- packages/perspective/test/js/expressions/string.js
- packages/perspective/test/js/leaks.spec.js
- python/perspective/perspective/table/_utils.py
- python/perspective/perspective/tests/table/test_view_expression.py
- rust/perspective-viewer/src/rust/exprtk/language.rs
PR on top of #1596, but this one can be merged first to show all the changes - it's in a separate PR to make code review easier.
This PR adds more regex functions:
- `find(string, pattern, output_vector)`: writes the start and end-index (0-indexed) of the first match in string of the first capturing group in pattern. Values can be read from the output vector as follows: `var vec[2]; find("x", '(.*)', vec) ? vec[0] + vec[1] : null`. Returns `true` if a match was found and values were written to the output vector, and `false` otherwise.
- `substring(string, start_idx, length?)`: returns the substring of string from `start_idx` (0-indexed) with the specified `length`. If the length is not provided, returns the substring from start_idx to the end of the string, or null if the string is …
> More regex functions - find, substring, replace

- packages/perspective-viewer-d3fc/src/js/axis/chartFactory.js
- packages/perspective-viewer-d3fc/src/js/legend/legend.js
* Fixes a regression introduced in upgrading  #1599, which is now incompatible with dependency-dependency `d3-svg-legend`.  The regression manifested as un-clickable legend items.
* Fixes a regression in the way `enter()` is calculated, which honestly I'm unclear as to how it worked previously ... but is now fixed none the less.
> Fix D3 alt-axis regression

- rust/perspective-viewer/src/rust/components/filter_item.rs
- rust/perspective-viewer/src/rust/utils/datetime.rs
- rust/perspective-viewer/src/rust/utils/errors.rs
- rust/perspective-viewer/src/rust/utils/mod.rs
> Fix `datetime` filter timezone bug

- cpp/perspective/src/cpp/emscripten.cpp
- packages/perspective/test/js/constructors.js
Fixes the equivalent bug identified in #1616, but for JavaScript.
> Fix partial-updates on tables with `limit` set for javascript

- azure-pipelines.yml
- python/perspective/setup.py
> bump windows build for vc 14.2 / vs 16 2019, add macos 11 build for py3.9

- .gitattributes
im doing some work on windows for conda and dont want to leak crlf into the code, we only enforce on `.js` files rn
> [Formatting] force line-feed line endings for all text files for easier windows development

- docs/js/index.js
- packages/perspective-jupyterlab/src/js/psp_widget.js
- packages/perspective-jupyterlab/test/js/resize.spec.js
- packages/perspective-workspace/src/js/workspace/tabbar.js
- packages/perspective-workspace/src/js/workspace/widget.js
- packages/perspective-workspace/src/js/workspace/workspace.js
- rust/perspective-viewer/src/rust/custom_elements/viewer.rs
- rust/perspective-viewer/src/rust/js/mod.rs
- rust/perspective-viewer/src/rust/js/resize_observer.rs
- rust/perspective-viewer/src/rust/renderer.rs
- rust/perspective-viewer/src/ts/viewer.ts
- rust/perspective-viewer/test/js/simple_tests.js
- tools/perspective-test/src/js/index.js
Adds auto-reiszing behavior (on by default) to `<perspective-viewer>`, via an internal [`ResizeHandler`](https://developer.mozilla.org/en-US/docs/Web/API/Window/resize_event) on these elements.  As a result, `notifyResize()` is no longer needed for resizing strictly and will likely eventually be removed as it can lead to duplicate re-renders.  For now, it has been preserved and behavior modified slightly - calling `notifyResize()` when auto-sizing is enabled will log a warning and disable auto-size, unless the `force` bool argument is provided.
Auto size behavior can be disabled, reverting to the old manual resize logic via `notifyResize()` (which will not warn in this case), by calling `setAutoSize(false)`:
```javascript
elem = document.querySelector("perspective-viewer"); …
```
> Add auto-resizing to `<perspective-viewer>`

- rust/perspective-viewer/build.js
Fixes #1646 but better this time than #1649
> Remove wasm-pack artifacts which interfere with perspective packaging

- rust/perspective-viewer/src/rust/components/filter_item.rs
Fixes #1645, I believe.  I had quite a bit of trouble reproducing this as described in the bug report, but did experience some rare value-clearing related to a race condition between the cell input and focus, which this PR fixes by removing focus hooks for non-completion filters (which were never functional for these filter types).
> Fix `datetime`/`date`/`integer`/`float` filter occasionally resetting while typing

- packages/perspective-viewer-datagrid/package.json
- yarn.lock
Upgrades `regular-table` to `0.4.2`, which fixes a rendering glitch due to `position: sticky`
> Fix `position: sticky` Chrome render bug in `perspective-viewer-datagrid`

- rust/perspective-viewer/build.js
- rust/perspective-viewer/src/less/expression-editor.less
- rust/perspective-viewer/src/rust/components/containers/split_panel.rs
- rust/perspective-viewer/src/rust/components/expression_editor.rs
- rust/perspective-viewer/src/rust/js/monaco.rs
- rust/perspective-viewer/tsconfig.json
Adds simple resizing to the expression editor widget.  This PR lacks persistence and vertical/corner resizing, as well as proper anchor support, but even as a small addition helps a lot when writing complex ExprTK expressions.
> Resizable expression editor

- packages/perspective-viewer-datagrid/package.json
- packages/perspective-workspace/src/js/perspective-workspace.js
- rust/perspective-viewer/src/rust/custom_elements/viewer.rs
- rust/perspective-viewer/src/rust/renderer.rs
* Fixes `<perspective-viewer>`'s `delete()` method to be `async`, and internally acquire the draw lock.  This prevents a mid-executing call to `draw()` from losing access to the data due to an interrupting `delete()`, causing a segfault.  This may happen when, e.g., a panel-close occurs in `<perspective-workspace>` quickly after a `draw()` was triggered on that panel, before it completes.
* Fixes threshold for light DOM update trigger, which caused errors when customizations are applied to a `<perspective-viewer>` in a workspace, which is subsequently closed.
> Fix `perspective-workspace` errors

- rust/perspective-viewer/src/rust/components/status_bar.rs
- rust/perspective-viewer/src/rust/components/tests/status_bar.rs
- rust/perspective-viewer/src/rust/components/viewer.rs
- rust/perspective-viewer/src/rust/config/view_config.rs
- rust/perspective-viewer/src/rust/custom_elements/viewer.rs
- rust/perspective-viewer/src/rust/session.rs
- rust/perspective-viewer/src/ts/viewer.ts
- rust/perspective-viewer/test/js/expressions.spec.js
- rust/perspective-viewer/test/results/results.json
This PR changes the behavior of the Reset button in `<perspective-viewer>`'s `StatusBar` component to preserve `expressions`, thus only resetting the properties of the underlying `View`.  `shift+click` can be used to override this behavior and clear `expressions` as well.
`reset()` has also been changed to `reset(reset_expressions: bool)`, and will behave the same way unless `reset_expressions` is `true`.
> Preserve `expressions` on reset (shift+ to force)

- packages/perspective-viewer-d3fc/src/js/data/treeData.js
- packages/perspective-viewer-d3fc/src/js/series/treemap/treemapLabel.js
- packages/perspective-viewer-d3fc/src/js/series/treemap/treemapLevelCalculation.js
- packages/perspective-viewer-d3fc/src/js/series/treemap/treemapSeries.js
- packages/perspective-viewer-d3fc/src/js/series/treemap/treemapTransitions.js
- packages/perspective-workspace/test/js/integration/restore.spec.js
- rust/perspective-viewer/src/rust/components/config_selector.rs
- rust/perspective-viewer/src/rust/config/view_config.rs
When a `Group by` with `null` values was present in a parent group using the `"Treemap"` plugin, zooming in from that level and back out would fail to properly draw the original treemap.  This occurred only when zooming, as the bug is not related to the initial SVG render itself, but the attribute-modifying zoom-in/zoom-out code that changes visibility/position of the treemap SVG elements.  Here, group identity was checked using the column encoding `"name1|name2"` and `.split("|")`, which encodes `[null]` as an empty string and is indistinguishable from `[]`.  However, this string-encoding is only used a few times, and is generated from the correct `Array` representation _only_ for treemaps, so this PR just replaces just it with this original `Array` and removes the string-decoding for …
> Fix Treemap zoom when a group level is `null`

- cmake/arrow.txt.in
- cmake/arrow/CMakeLists.txt
- cmake/arrow/config.h
Rebased from #1636
Benchmarks look flat but its worth not letting these changes accumulate until we _need_ to upgrade.
> Upgrade Arrow to `6.0.2`

- .husky/pre-push
- cpp/perspective/build.js
- package.json
- packages/perspective/package.json
- packages/perspective/src/js/perspective.browser.js
- rust/perspective-viewer/build.js
- rust/perspective-viewer/package.json
- rust/perspective-viewer/src/ts/init.ts
- tools/perspective-build/build.js
- tools/perspective-build/wasm.js
- tools/perspective-build/worker.js
- yarn.lock
WASM assets gzip quite well when properly configured on your application's HTTP server via the `Content-Encoding: gzip` header, and you can even remove the on-the-fly gzip cost by pre-zipping the wasm and configuring your server appropriately, but
* `Content-Encoding: gzip` doesn't affect the perceived size of the perspective _inline_ (e.g. without the webpack-plugin) builds, especially in the developer's imagination (see #1655).  Also, the inlined base64 WASM payload as a string does not compress nearly as well as gzipping the original WASM.
* CDNs generally don't recognize pre-gzipped assets (as they likely shouldn't).
* Even with the build plugin, WASM assets sizes are large and perspective's build is complex enough without asking app developers to provide bespoke server support.
To …
> 80% reduction in `.wasm` asset size

- azure-pipelines.yml
- python/perspective/MANIFEST.in
- scripts/_wheel_python.js
> fix wheel build, make extension first to ensure binaries are inlined, then assemble wheel

- azure-pipelines.yml
reduce ci by only building on PRs to master branch, not building branches independent of PRs, and ommitting some paths
> Reduce CI: Turn off branch builds, only build on PRs to master

- scripts/install_tools.js
Fixes CI build failure due to [regression in `flatbuffers`](https://github.com/google/flatbuffers/commit/a42e898979cc828a35aefcc469fec896175fa8e6) (just a guess).
> Pin `flatc` to 1.12.1

- cpp/perspective/src/cpp/data_table.cpp
- python/perspective/perspective/tests/table/test_table.py
> Fix bad filter when `.update()` contains missing string column value

- packages/perspective-jupyterlab/src/js/model.js
- packages/perspective-jupyterlab/src/js/psp_widget.js
- packages/perspective-jupyterlab/src/js/renderer.js
- packages/perspective-jupyterlab/src/js/view.js
- python/perspective/perspective/viewer/viewer.py
- python/perspective/perspective/viewer/viewer_traitlets.py
- rust/perspective-viewer/src/rust/components/tests/viewer.rs
- rust/perspective-viewer/src/rust/components/viewer.rs
- rust/perspective-viewer/src/rust/config.rs
- rust/perspective-viewer/src/rust/config/view_config.rs
- rust/perspective-viewer/src/rust/custom_elements/viewer.rs
- rust/perspective-viewer/src/rust/custom_events.rs
- rust/perspective-viewer/src/rust/lib.rs
- rust/perspective-viewer/src/rust/renderer.rs
- rust/perspective-viewer/test/js/events.spec.js
This PR updates the `perspective-config-update` event fired from `<perspective-viewer>` custom element in two ways:
1) `perspective-config-update` is now fired when either the `settings` or `theme` property are changed, in addition to the other properties it fires for currently.
2) Then `event.detail` property now includes `theme`, `settings`, `plugin` and `plugin_config`, mirroring the object returned from the `.save()` method.
In addition, Python `traitlets` have been added for `settings` and `theme`, allowing them to be manipulated programmatically from the `PerspectiveWidget` JupyterLab interface.
Fixes #1499
> Add `settings` and `theme` to `perspective-config-update` DOM event and `PerspectiveWidget` python class

- rust/perspective-viewer/src/less/column-style.less
- rust/perspective-viewer/src/themes/material.less
As done with radio buttons, this PR allows `column style` checkbox icons to be provided by css variables with a native checkbox fallback. 
The original material checkbox icons have been moved to the material theme file.
> Add column-style-checkbox css variables

- python/perspective/perspective/table/table.py
- python/perspective/perspective/tests/table/test_leaks.py
- python/perspective/setup.py
- scripts/test_python.js
Address the Python `table()` memory leak identified in #1723 (but do not close this issue it tracks dictionary "leak" behavior).
> Fix python memory leak in `table()`

- packages/perspective-viewer-datagrid/src/js/plugin_menu.js
This PR resolves #1727 by firing the `perspective-config-update` event on `perspective-viewer` element.
This was tested manually. Is there a good place to add a test for this behavior?
> fix: fire config-update evnt on perspective-viewer

- docs/md/development.md
- package.json
Remove references to `docker` based `puppeteer` tests, as `docker` is no longer a requirement, nor even supported.
> Update dev docs

- packages/perspective/src/js/perspective.browser.js
- tools/perspective-build/worker.js
In 2022, there are still some contexts where Web Workers are not allowed, but (somehow) Web Assembly is.  This PR adds single-threaded mode to `@finos/perspective`, such that the Web Assembly engine will run synchronously on the main browser thread when Web Worker instantiation fails.
> Allow `@finos/perspective` to run in single-threaded mode

- azure-pipelines.yml
Suspending Windows Python builds until [they can successfully build on CI](https://dev.azure.com/finosfoundation/perspective/_build/results?buildId=4036&view=logs&j=c9b54867-f028-5773-2b8c-07b236940a16).
> Disable Windows builds

- azure-pipelines.yml
Homebrew now exclusively dists `flatbuffers@2.0.6` which is [incompatible with our arrow build](https://dev.azure.com/finosfoundation/perspective/_build/results?buildId=4064&view=logs&j=0e75fe71-fead-56f1-bee0-bc202d563d9d&t=59712ed9-8e00-5be3-1aeb-5e7d762b32ca).  I would spend more time attempting to fix this, but its already been 2 minor version JavaScript releases since a stable Python release due to #1741 (and list wouldn't hurt to add #1684 to the list).
What's one more tire on the eternally-burning apocalyptic tire-fire hellscape that is a cross-platform Python library with native extensions?
> Disable OSX Python CI

- packages/perspective-viewer-datagrid/src/js/plugin.js
> Fix tree column override width persistence in `perspective-viewer-datagrid`

- packages/perspective-workspace/build.js
- tools/perspective-build/external.js
Tree-shaking for neither `esbuild` nor `webpack` live up to the kb discount of importing the implementation source `.ts` files rather than the pre-compiled es6 `dist/` versions, ~50kb of difference in `perspective-workspace`.  However, `webpack` requires yet another custom loader for `perspective-webpack-plugin` to selectively compile the TypeScript.  Rather than add this, this PR instead inlines the `@lumino` includes in `@finos/perspective-workspce/dist/esm`.
TL;DR `@finos/perspective-workspce` works and is 50kb smaller.
> Fix `perspective-workspace` webpack compat

- packages/perspective-workspace/src/js/workspace/workspace.js
- rust/perspective-viewer/src/rust/renderer.rs
This PR adds a 500ms timeout to the settings toggle's plugin draw invocation.  Typically, opening/closing the settings menu will await a resized draw completion before removing the settings UI from the DOM, which reduces screen-shearing;  however, when the engine is very busy, this may create an unacceptable delay.  We now timeout this call, which creates some screen-shearing as the plugin later catches up and redraws at the new canvas size, but keeps the UI responsive even when the engine is under heavy load.
> Make toggle-menu more responsive under load

- packages/perspective-jupyterlab/test/jupyter/utils.js
- packages/perspective-jupyterlab/test/jupyter/widget.spec.js
I _believe_ this fixes the persistent Jupyter test failures which have plagued our CI recently, though the nature of intermittent test failures on CI means I cannot be _certain_.
Replaces an arbitrary timeout with a `waitForSelector()` that tests for the presence of an `"idle"` kernel before executing a keyboard command to run Jupyter cells.  Though I am not sure this was the source of the timeout on CI, removing this 1000ms timeout consistently failed these tests, and in non-headless mode I observed instances of the keyboard commands firing before the kernel reported `"idle"`.
> Fix jupyterlab test timeouts

- python/perspective/setup.py
CMake's ```FindPythonLibs``` is not working very well under virtualenv. We need to set ```PYTHON_LIBRARY``` and ```PYTHON_INCLUDE_DIR``` to help CMake locate the relevant directories.
PS: This new one is created because I can't change the source branch of PR  https://github.com/finos/perspective/pull/1777
> fix cmake build error when install under virtualenv

- rust/perspective-viewer/src/themes/material-dark.less
- rust/perspective-viewer/src/themes/material.less
- rust/perspective-viewer/src/themes/solarized-dark.less
In the recent release of Chrome 102, scroll events to `perspective-viewer-datagrid` behave differently; in previous versions, "inertia" scroll would trigger events, where-as in version 102.0.5005.61, there additional scroll events would frequently not fire, causing a slow, stuttering scroll experience.  This was observed in versions as far bask as perspective 1.0.0.
In testing, the previous behavior can be restored by removing the `-webkit-mask-image` CSS rules from the scroll container, which simulated fade-in on hover for the custom scrollbars.  This PR removes these rules, reverting this animation to pop-in on hover instead, restoring scroll behavior to mirror pre-102 Chrome.
> Fix scrolling in Chrome 102

- scripts/setup.js
Fixes a bug in setup.js where extra set of quotes in the execution command prevents initial build (tries to execute contents of the double quotes as a single executable). 
Before:
After:
> fix bug in setup.js where extra set of quotes prevents initial build

- .github/dependabot.yml
- .github/workflows/build.yml
- packages/perspective-viewer-d3fc/package.json
- packages/perspective-viewer-datagrid/package.json
As discussed offline, removing the default dependabot upgrading, we will upgrade manually in response to features or bug fixes we want. Also removing the full build from merges to master, we can easily trigger manually and we will still build full on tags. 
Finally, removing some unused watch commands discovered during other development.
> Remove unused watch commands from viewer-d3fc and viewer-datagrid, remove dependabot, dont trigger full build on merge to master

- cpp/perspective/src/cpp/context_grouped_pkey.cpp
- cpp/perspective/src/cpp/data_table.cpp
- cpp/perspective/src/cpp/expression_tables.cpp
- cpp/perspective/src/cpp/gnode.cpp
- cpp/perspective/src/cpp/gnode_state.cpp
- cpp/perspective/src/include/perspective/data_table.h
- cpp/perspective/src/include/perspective/expression_tables.h
- cpp/perspective/src/include/perspective/gnode.h
- cpp/perspective/src/include/perspective/parallel_for.h
- python/perspective/docs/perspective.core.rst
- python/perspective/perspective/libpsp.py
- python/perspective/perspective/tests/single_threaded/test_single_threaded.py
- scripts/test_python.js
* Fixes a deadlock condition when `set_threadpool_size(1)` was called in Python.
* Add documentation to `set_threadpool_size()` to note that it must be called before the global thread pool is instantiated.
* Removed sloppy `parallel_for()` API in C++.  Confirmed that this generates nearly identical bytecode in wasm/release, and confirmed no benchmark regressions in single- or mult- threaded runtimes.
* Cherrypick #1851
> Fix `set_threadpool_size(n)` for `n == 1`

- .github/workflows/build.yml
- azure-pipelines.yml
- python/perspective/setup.py
- scripts/build_python_azure.js
- scripts/publish_python.js
- scripts/publish_python_azure.js
- scripts/script_utils.js
This PR is a fork of [tkp/py36cleanup](https://github.com/finos/perspective/tree/tkp/py36cleanup), which does not have its own PR but I've reviewed.  I've modified the last PR to remove the Docker changes (as per previous comments).
> Remove Python 3.6 support

- .github/workflows/build.yml
- cmake/arrow/CMakeLists.txt
- cpp/perspective/CMakeLists.txt
- cpp/perspective/build.js
- cpp/perspective/src/cpp/emscripten.cpp
- package.json
- packages/perspective/build.js
- packages/perspective/src/js/perspective.js
- packages/perspective/src/js/perspective.node.js
- rust/perspective-viewer/build.js
- rust/perspective-viewer/src/rust/components/containers/select.rs
- rust/perspective-viewer/src/rust/components/containers/split_panel.rs
- rust/perspective-viewer/src/rust/components/modal.rs
- rust/perspective-viewer/src/rust/components/number_column_style.rs
- rust/perspective-viewer/src/rust/components/string_column_style.rs
- rust/perspective-viewer/src/rust/config/filters.rs
- rust/perspective-viewer/src/rust/config/sort.rs
- rust/perspective-viewer/src/rust/dragdrop.rs
- rust/perspective-viewer/src/rust/js/mimetype.rs
- rust/perspective-viewer/src/rust/js/plugin.rs
- rust/perspective-viewer/src/rust/model/columns_iter_set.rs
- rust/perspective-viewer/src/rust/model/export_method.rs
- rust/perspective-viewer/src/rust/session/view_subscription.rs
- tools/perspective-bench/package.json
- tools/perspective-bench/src/js/bench.js
- tools/perspective-build/empty.js
- tools/perspective-build/rust_wasm.js
- tools/perspective-build/worker.js
A set of internal changes which make Perspective compatible with Emscripten's `STANDALONE_WASM` output mode, and otherwise reduce the complexity/redundancy of the CI process.
* Update emscripten to `3.1.14`
* Update wasm-opt to `109`
* Remove `main()` from emscripten bindings, switch to `--no-entry` compilation mode.
* Removes double-linking (for node and browser) portion of emscripten build.
> Update `emsdk` to `3.1.14`

- .github/workflows/build.yml
- cpp/perspective/src/cpp/sparse_tree.cpp
- packages/perspective/src/js/perspective.js
- packages/perspective/test/js/expressions/invariant.js
- packages/perspective/test/js/expressions/numeric.js
- packages/perspective/test/js/pivots.js
Fix a few small memory leaks which in aggregate caused OOM and other test stability issues, as per failing master build.  This was not detected in CI as the `emsdk` cache was keyed on `yarn.lock`, while `emsdk` versions are not `yarn` dependencies.
One of these memory leaks was a string-length miscalculation in the `join` aggregate, as well as an assumption that these values already be strings;  the fix for this behavior also fixes #1786
> Fix small memory leak and validate package.json with CI cache

- .github/workflows/build.yml
- azure-pipelines.yml
Perspective/Jupyterlab tests dump random errors coincident with the release of Tornado 6.2 today.  I don't yet know if this is an existing bug in Perspective that has been exposed, or in JupyterLab or Tornado, so I have not modified the `setup.py` bounds.
I'll be looking into removing the manual dependency installation from azure as well, as IMO it is unacceptable to have CI break when dependencies change. 
```bash
Exception in callback <TaskWakeupMethWrapper object at 0x10dd9f1c0>(<Future finis... GMT\r\n\r\n'>)
handle: <Handle <TaskWakeupMethWrapper object at 0x10dd9f1c0>(<Future finis... GMT\r\n\r\n'>)>
Traceback (most recent call last):
File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/events.py", line 80, in _run …
```
> Pin `tornado` to 6.1 in CI

- packages/perspective-viewer-datagrid/src/js/regular_table_handlers.js
Fixes #1873 
Because the expand/collapse button is rendered via `::before` pseudo element, we can't declare separate hover rules for it, and the `click` handler used JavaScript to only respond to events in the appropriate region.  This PR simply removes the latter logic;  `click` now works on the entire group cell, just like the expand/collapse highlight indicator.
> Expand/collapse on entire group cell, rather than just button

- packages/perspective-viewer-datagrid/src/js/plugin.js
- packages/perspective-viewer-datagrid/src/js/plugin_menu.js
- packages/perspective-viewer-datagrid/src/js/regular_table_handlers.js
- packages/perspective-viewer-datagrid/test/js/superstore.spec.js
- rust/perspective-viewer/src/less/column-style.less
- rust/perspective-viewer/src/rust/components/number_column_style.rs
- rust/perspective-viewer/src/rust/components/tests/column_style.rs
Part of the suggested refactoring of the UX from #1875, allowing both Foreground color and Background color to be specified on numeric datagrid columns at the same time.
> Split foreground and background numeric column color modes

- packages/perspective-viewer-datagrid/src/js/regular_table_handlers.js
- rust/perspective-viewer/src/less/column-style.less
Fix gradient bounds calculation for gradient/bar numeric datagrid column styling, specifically for columns that contain negative values.  Additionally, applies rounding to 2 decimal digits for values exceeding one to make this value easier to read (though this will likely need more refinement).
> Fix gradient bounds calc

- .github/workflows/build.yml
- python/perspective/perspective/tests/table/test_view.py
Jupyterlab CI tests have been running against e.g. `@finos/perspective-viewer-datagrid` from NPM instead of locally since #1808, which is fixed by this PR
> Fix jlab tests to use local packages

- packages/perspective-webpack-plugin/index.js
Fixes a regression in `@finos/perspective-webpack-plugin` which caused unresolvable node.js imports `"fs"` and `"path"` to fail.
> Fix webpack plugin compat with emsdk single-link build

- scripts/_wheel_python.js
Adds a missing dependency that works fine for `3.9` and nothing else on Linux.
> Fix python CI builds for all linux variants

- packages/perspective-viewer-d3fc/src/js/axis/ordinalAxis.js
- packages/perspective/src/js/config/index.js
- packages/perspective/src/js/perspective.js
- packages/perspective/src/js/perspective.worker.js
- rust/perspective-viewer/build.js
- rust/perspective-viewer/src/ts/migrate.ts
- rust/perspective-viewer/test/js/migrate_viewer.spec.js
- rust/perspective-viewer/test/results/results.json
* Fixes `@finos/perspective-viewer/dist/cjs/migrate` migration script to be compatible with the `plugin_config` API changes introduced in #1889
* Fixes various issues with disparities between ES6 and babel
* Replace `global` with `globalThis`
* Fix issues with spread operator + `Set()` e.g. `[...new Set()]`
* Remove IE compat clock fix for missing emscripten API
> Add migrate support for datagrid `plugin_config` API

- .github/workflows/build.yml
- binder/postBuild
- package.json
- packages/perspective-jupyterlab/package.json
- packages/perspective-jupyterlab/src/js/index.js
- packages/perspective-viewer-openlayers/package.json
- scripts/publish_python.js
- yarn.lock
* Pin `JupyterLab` in CI to 3.4.3, as a recent release has broken the perspective master build.
* Fixes the [example link to binder](http://beta.mybinder.org/v2/gh/finos/perspective/master?urlpath=lab/tree/examples/jupyter-notebooks), which currently installs the latest `perspective-python` and `@finos/perspective-jupyterlab` packages at the time of docker container construction.  These may not always be in sync, so I've added a check which makes sure the JS matches the Python library's version.
* Fixes various broken cases in the `scripts/publish_*` scripts encountered during publishing `1.6.0`
* Fix `@finos/perspective-jupyterlab` to use `@finos/perspective-viewer-openlayers` UMD build, as jupyterlab's build seems to have trouble resolving `ol` for some reason.
> Fix publish issues

- packages/perspective/src/js/perspective.browser.js
- packages/perspective/src/js/perspective.worker.js
In some circumstances, it is useful to run Perspective without a WebWorker, e.g. when using `file://` protocol where WebWorkers are disallowed by security policy in Chrome.  The code which enabled this runtime mode was updated incorrectly #1914, which this PR fixes.
> Fix "inline mode" build

- packages/perspective-esbuild-plugin/index.js
- packages/perspective-esbuild-plugin/worker.js
- packages/perspective-jupyterlab/build.js
- packages/perspective-workspace/build.js
- rust/perspective-viewer/Cargo.toml
- rust/perspective-viewer/build.rs
- rust/perspective-viewer/src/rust/model/copy_export.rs
- rust/perspective-viewer/src/rust/model/export_app.rs
When exporting as `.html`, `<perspective-viewer>` will now:
* Import the pinned version of the host `<perspective-viewer>`, rather than `@latest`.
* Import only the set of plugins the host `<perspective-viewer>` uses, rather than the default set (makes more sense now that `@finos/perspective-viewer-openlayers` is available).
> Fix app export

- python/perspective/perspective/handlers/common.py
- python/perspective/perspective/tests/handlers/test_aiohttp_async_mode.py
- python/perspective/perspective/tests/handlers/test_starlette_async_mode.py
- python/perspective/perspective/tests/handlers/test_tornado_async_mode.py
- python/perspective/setup.py
Fixes a bug introduced in #1828.  Handler callbacks need to dispatch to the event loop from the framework in order to re-inject responses after `PerspectiveManager` is invoked, and this loop is captured by the top-level invoking thread via `get_event_loop()` (in this refactor).  However, due to a closure misapplication, this loop was exclusively being captured from the Perspective thread instead.
The impact of this can be seen in the `python-tornado-streaming` example within a few seconds of a client connecting, or in the trio of tests this PR adds.
```bash
ERROR:asyncio:Exception in callback None()
handle: <Handle cancelled>
Traceback (most recent call last):
File "~/python3.9/asyncio/events.py", line 80, in _run
self._context.run(self._callback, *self._args)
File …
```
> Fix Python bug in `async` mode

- cpp/perspective/src/cpp/emscripten.cpp
- cpp/perspective/src/cpp/view_config.cpp
- cpp/perspective/src/include/perspective/view_config.h
- python/perspective/perspective/src/context.cpp
`expressions` which are unused by `columns`/`group_by`/etc should not be calculated (but they do need to be maintained by the `View` instance as they are query-able metadata).  This is a _bug_ rather than an _enhancement_ because this behavior was a presumption of the UI already, as well as a property that was enforced by the previous iteration of `<perspective-viewer>` component (this PR moves the behavior to the `@finos/perspective` engine itself for consistency across languages/consumers).
> Don't calculate unused `expressions`

- packages/perspective-viewer-d3fc/src/js/plugin/plugin.js
- packages/perspective-workspace/test/html/index.html
- packages/perspective-workspace/test/js/integration/visibility.spec.js
- packages/perspective-workspace/test/results/results.json
Within sunburst charts, labels must be calculated (or not) depending on whether they will _physically fit_ in their respective slices, and this can only practically be done by measuring the text _after_ its been rendered.  When a sunburst chart is drawn but not visible, e.g. in the case of a `<perspective-workspace>` panel that is "unselected" but still _connected" from the perspective of the Shadow DOM, this can result in an infinite loop, as most geometry calculations e.g. `getBoundingClientRect()` will not return the correct values when they're not "visible".  This PR changes the initialization logic for charts, only rendering them fully when their `offsetParent` is non-null.
Fixes #1938 and adds a test case derived from the repro in this issue.
> Fix Sunburst chart infinite loop bug

- packages/perspective-esbuild-plugin/package.json
- rust/perspective-viewer/src/rust/custom_elements/debug_plugin.rs
- rust/perspective-viewer/src/rust/custom_elements/mod.rs
- rust/perspective-viewer/src/rust/lib.rs
- rust/perspective-viewer/src/rust/utils/custom_element.rs
- rust/perspective-viewer/src/rust/utils/futures.rs
- rust/perspective-viewer/src/ts/plugin.ts
- yarn.lock
An internal API change which allows the default (debug) plugin to be optionally defined from Rust.
> Move default plugin to WASM

- scripts/script_utils.js
I made a copy-pasta typo when writing the script, so the python README is actually the LICENSE. this fixes that.
> accidentally copying license as readme when disting python

- python/perspective/pyproject.toml
- python/perspective/setup.py
extracted from https://github.com/finos/perspective/pull/2011 which is segfaulting in 3.10
xref: https://github.com/encode/starlette/issues/1943, https://github.com/encode/starlette/issues/1945
https://www.starlette.io/#dependencies
`[httpx](https://www.python-httpx.org/) - Required if you want to use the TestClient.`
> Re-add secondary dependency as primary dependency to fix python tests

- .gitignore
- packages/perspective-viewer-datagrid/src/js/custom_elements/datagrid.js
- rust/perspective-viewer/src/rust/js/plugin.rs
- rust/perspective-viewer/src/rust/renderer/registry.rs
- rust/perspective-viewer/src/ts/plugin.ts
- rust/perspective-viewer/test/html/plugin-priority-order.html
- rust/perspective-viewer/test/js/plugins.spec.js
- rust/perspective-viewer/test/results/results.json
Now in environments with wonky loading (i.e. safari), the datagrid will come up first when loading all perspective plugins.
Fixes #2006
> Fix Default Plugin Order

- docs/docusaurus.config.js
I assume the link in the footer of https://perspective.finos.org/ is supposed to point to this repository, not Docusaurus'.
> Update docusaurus footer with correct link

- packages/perspective-viewer-d3fc/src/js/charts/xy-scatter.js
- packages/perspective-viewer-d3fc/src/js/series/pointSeriesCanvas.js
- packages/perspective-viewer-d3fc/test/js/integration/scatter.spec.js
- packages/perspective-viewer-d3fc/test/results/results.json
Rebased version of #2032 with test fix.  Adds `label` field to X/Y Scatter charts, allowing individual scatter points to be labelled.  Fixes #2029
> Add labels to Scatter plot points.

- packages/perspective-viewer-d3fc/package.json
- packages/perspective-viewer-d3fc/src/js/tooltip/generateHTML.js
- packages/perspective-viewer-d3fc/src/js/tooltip/selectionData.js
- packages/perspective-viewer-d3fc/test/js/unit/tooltip/generateHTML.spec.js
- packages/perspective-viewer-d3fc/test/js/unit/tooltip/selectionData.spec.js
- rust/perspective-viewer/Cargo.lock
Currently there is a bug where selection data text splitting logic will throw an error if certain values of the data (key and mainValue properties) are not "splittable". This PR aims to correct the logic surrounding this splitting of values.
redo of a [previous PR](https://github.com/finos/perspective/pull/2039)
> Fix parsing of bug related to d3fc splitting selection data (redux of #2039)

- cpp/perspective/src/cpp/computed_expression.cpp
- cpp/perspective/src/cpp/computed_function.cpp
- cpp/perspective/src/include/perspective/computed_expression.h
- cpp/perspective/src/include/perspective/computed_function.h
- examples/blocks/gists.json
- examples/blocks/src/raycasting/.block
- examples/blocks/src/raycasting/README.md
- examples/blocks/src/raycasting/index.css
- examples/blocks/src/raycasting/index.html
- examples/blocks/src/raycasting/index.js
* Adds 4 new vec3 functions to ExprTK/Perspective: `dot_product3`, `cross_product3`, `norm3` and `diff3`.
* Adds a new demo of a simple ray-casting engine written as a Perspective example similar to the existing Fractal example, as presented at OSSF NYC 2022.
> Vec3 functions for ExprTK and new example "Ray Casting"

- packages/perspective-esbuild-plugin/ignore_fonts.js
- packages/perspective-viewer-d3fc/src/js/series/pointSeriesCanvas.js
During compilation, resources from Google Fonts were being downloaded and inlined, causing sporadic failures on CI.  These resources are now skipped.
> Fix CSS compilation to not inline http resources

- .github/workflows/build.yml
- scripts/_wheel_python.js
Testing here:
https://github.com/finos/perspective/actions/runs/3804830237
`gh workflow run "Build Status" --ref tkp/armmac -f ci-include-windows=false -f ci-skip-python=false -f ci-full=true`
> Add macOS arm wheels to build matrix

- .gitignore
- .vscode/extensions.json
- .vscode/settings.json
- examples/blocks/server.js
Adds a default `.vscode` folder configured for Rust and C++ extensions, which don't really work with the default settings due to Perspective's multi-language monorepo.
> Add default .vscode project

- packages/perspective-cli/src/js/index.js
Fixes #2085 - this was a bone-headed regression that was introduced while trying to write a test to ensure this functionality worked.
> Fix regression in `perspective-cli`

- scripts/publish.js
- scripts/script_utils.js
This PR addresses a few bugs discovered in the development commands which caused:
* `PACKAGE` scope not to be respected
* Packages without `/dist` folders to not auto-publish (e.g. CLI).
* Use `npm publish` instead of `yarn publish` (the latter is both publish + version).
> Fix script errors in publish and build commands

- .github/workflows/build.yml
- cmake/modules/FindInstallDependency.cmake
- cpp/perspective/CMakeLists.txt
- python/perspective/bench/runtime/bench.py
- python/perspective/bench/runtime/perspective_benchmark.py
- python/perspective/perspective/client/websocket.py
- python/perspective/perspective/manager/manager_internal.py
- python/perspective/perspective/table/table.py
update python lints for newest black version
build: https://github.com/finos/perspective/actions/runs/4267478014
> vendor all C++ dependencies at build time, fixes #2075, closes #2076,

- packages/perspective-jupyterlab/src/js/view.js
- python/perspective/perspective/viewer/validate.py
- python/perspective/perspective/viewer/viewer.py
- python/perspective/perspective/viewer/viewer_traitlets.py
* can set title from a notebook `widget.title = "Hello world"`
* setting the view's title from the widget doesn't update python state, so doesn't persist across refreshes
> Implement `title` field in `PerspectiveWidget`

- rust/perspective-viewer/src/less/filter-item.less
- rust/perspective-viewer/src/rust/components/config_selector.rs
- rust/perspective-viewer/src/rust/components/config_selector/filter_item.rs
- rust/perspective-viewer/src/rust/custom_elements/filter_dropdown.rs
- rust/perspective-viewer/test/js/regressions.spec.js
- rust/perspective-viewer/test/results/results.json
Fixes auto-complete dropdowns for `in` and `not in` filters.  Previously, while this filter could still be manually filled with a comma-separated set, doing so by selecting items in the dropdown with the mouse or arrow keys did not respect the separator.
Fixes #1962
> Fix autocomplete behavior for `in` and `not in` filter ops

- docs/docs/development.md
This PR adds a small line to the development docs specifying that Yarn v1 must be used to build the Perspective project.
> Specify that Yarn v1 must be used in development docs.

- .github/workflows/build.yml
Followed by [Issue #2140 ](https://github.com/finos/perspective/issues/2140), I have modified the deprecated `set-output` commands into the new `GITHUB_OUTPUT` environment.
> Fixed deprecated features in GitHub actions

- docs/src/components/Demo/index.js
- docs/src/components/ExampleGallery/features.js
- docs/src/components/ExampleGallery/index.js
(Both on the front page)
- Added an aria-label to the Velocity range slider
- Added descriptions for every example's thumbnail, and surfaced them as `alt` text.
I am presently unable to build Perspective in order to validate that this documentation works correctly. I have [a discussion](https://github.com/finos/perspective/discussions/2155) open to try to get myself to a point where I can build things.
However, I wanted to submit this PR ahead of time, in case anyone wants to review or change the image descriptions that I wrote.
> A11y front page labels

- examples/python-tornado-streaming/index.html
- examples/python-tornado/client_server_editing.html
- examples/python-tornado/index.html
- examples/python-tornado/server_mode.html
- python/perspective/perspective/handlers/aiohttp.py
- python/perspective/perspective/handlers/starlette.py
- python/perspective/perspective/handlers/tornado.py
Disconnect-related errors were handled for `aiohttp` and `starlette` when waiting for the client to send a message, this PR adds that same support to tornado but also handles disconnect when trying to send outbound messages. 
**Note** While testing, I noticed the route to the themes is incorrect, this is particularly noticeable after the recent theme changes
> gracefully handle websocket errors on python side, fixes #2132

- rust/perspective-viewer/src/rust/exprtk/tokenize.rs
- rust/perspective-viewer/src/rust/exprtk/tokenize/string.rs
Fixes expression syntax highlighting to properly display escaped characters in strings.
> Fix expression editor bug with escaped characters in strings

- packages/perspective-jupyterlab/src/js/renderer.js
I think these names look a bit cleaner than the original ones.
> rename context menu names for perspective renderers in jupyterlab

- cpp/perspective/src/cpp/computed_function.cpp
- cpp/perspective/src/include/perspective/computed_function.h
- packages/perspective/test/js/expressions/common.js
- packages/perspective/test/js/expressions/datetime.spec.js
Forked from  #2206
Adds optional unit scalars to some `date`/`datetime` bucketing intervals:
* `5s`, `10s`, `15s`, `20s`, `30s`
* `5m`, `10m`, `15m`, `20m`, `30m`
* `2h`, `3h`, `4h`, `6h`, `8h`, `12h`
* `2M`, `3M`, `4M`, `6M`
* `5Y`, `10Y`
> Add scalar factors to Exprtk `bucket()`

- cpp/perspective/src/cpp/sparse_tree.cpp
- packages/perspective/test/js/expressions/numeric.spec.js
#2036 Column expr of integer column sum renders all rows as 0
BEFORE:
AFTER:
> Fix `sum` aggregate for `integer` type expression columns

- cpp/perspective/src/include/perspective/step_delta.h
- scripts/_wheel_python.js
Fix regression in Python Windows builds which prevented publishing of 2.1.0
> Fix windows python builds

- rust/perspective-viewer/src/rust/custom_elements/viewer.rs
- rust/perspective-viewer/test/js/settings.spec.js
Passing a rejected promise to `load()` on a `HTMLPerspectiveViewerElement` causes internal errors which can interfere with state update notifications.
This PR fixes the issue and adds a test which repros the behavior on 2.1.3.
> Fix a bug when calling `load()` with a rejected promise

- cpp/perspective/src/cpp/sparse_tree.cpp
- cpp/perspective/src/include/perspective/sparse_tree.h
- packages/perspective/test/js/expressions/functionality.spec.js
- python/perspective/perspective/tests/core/test_aggregates.py
Fix for issue (#1928) where median value for even-sized item list is miscalculated, see below.
> Fix median miscalculation for even-sized item list

- packages/perspective-workspace/src/themes/pro-dark.less
- packages/perspective-workspace/src/themes/pro.less
- rust/perspective-viewer/src/less/status-bar.less
- rust/perspective-viewer/src/less/viewer.less
Fixes ugly 4px vertical offset of expression panel when in a workspace.
> Fix CSS positioning of expression panel in workspace

- python/perspective/perspective/tests/table/test_table_pandas.py
- python/perspective/setup.py
I'm keen to be able to use `pandas~=2.0.0` alongside `perspective`. I couldn't see an issue for this so thought I'd initially see if it broke CI.
fixes https://github.com/finos/perspective/issues/2250
> Allow `pandas~=2.0.0` to be installed

- packages/perspective-workspace/src/js/workspace/workspace.js
- packages/perspective-workspace/src/less/dockpanel.less
- packages/perspective-workspace/test/js/restore.spec.js
- rust/perspective-viewer/Cargo.lock
- tools/perspective-test/src/js/global_startup.ts
- tools/perspective-test/src/js/global_teardown.ts
Fixes `@finos/perspective-workspace`'s `save()` method when called with the settings panel open, which previously yielded JSON which does not recreate the GUI when provided to `restore()`.
> Fix workspace `save()` w/settings

- cpp/perspective/src/cpp/arrow_csv.cpp
- packages/perspective/test/js/constructors.spec.js
Fix for isssue( #1312 ) where US locale string format ("%m/%d/%Y, %I:%M:%S %p") is parsed wrongly by emscripten compiler. eg.  "03/15/2020, 11:30:45 AM" is incorrectly parsed as "03/15/2020, 11:30:45 PM"
Before Implementation - Test Fails
After Implementations - Test Passes
> Write custom parser for us locale time string format

- packages/perspective/index.d.ts
- packages/perspective/src/js/api/table_api.js
- packages/perspective/src/js/perspective.js
- packages/perspective/test/js/updates.spec.js
- python/perspective/perspective/client/table_api.py
- python/perspective/perspective/table/table.py
- python/perspective/perspective/tests/table/test_table.py
- rust/perspective-viewer/src/rust/lib.rs
The test describes the usage.
Would it possibly be better so simply give a `get_views` method, that returns each View object? Then we could just call `table.get_views().length`. 
Either way, happy to do it.
> Add API to give number of views into table

- examples/blocks/package.json
- examples/blocks/server.mjs
This PR fixes a bug where the blocks server could not be started with the command `yarn start blocks`.
> Fix bug preventing blocks example server from starting.

- cpp/perspective/src/cpp/pool.cpp
- cpp/perspective/src/include/perspective/pyutils.h
- python/perspective/perspective/client/websocket.py
- python/perspective/perspective/handlers/common.py
- python/perspective/perspective/handlers/tornado.py
- python/perspective/perspective/include/perspective/python.h
- python/perspective/perspective/include/perspective/python/table.h
- python/perspective/perspective/src/table.cpp
- python/perspective/perspective/table/table.py
- python/perspective/perspective/table/view.py
- python/perspective/perspective/tests/handlers/test_tornado_thread_pool_executor.py
Fixes a potential Python segfault introduced in `2.3.0`, which can occur when:
* Perspective is running in async mode via a multi-threaded executor and ...
* A `Table()` is constructed via Arrow input and ...
* `Table.update()` is called with an `Arrow` by a separate thread before the previous call has resolved.
[See the included test for a repro](https://github.com/finos/perspective/blob/py-segfault-fix/python/perspective/perspective/tests/handlers/test_tornado_thread_pool_executor.py#L100), which implements a multi-threaded executor then queues 20 read/write Arrow operations at once.
> Fix python segfault in multi-threaded execution

- packages/perspective-cli/test/js/superstore.spec.js
- python/perspective/perspective/table/_state.py
- python/perspective/perspective/tests/handlers/test_tornado_thread_pool_executor.py
Fixes two tests which flapped incessantly, causing endless CI headaches.
`@finos/perspective-cli`'s test suite must start and stop a Perspective server, which causes some log spam as the browser and server are consecutively shutdown. These errors are innocuous in this case as they occur after the server is in a shutdown-prepare state, but the logging itself is important as the condition `View method cancelled` can occur in other contexts unexpectedly. Moving this initialization out of the test prevents it from failing.
https://github.com/finos/perspective/actions/runs/5427137814/jobs/9870282667
`perspective-python`'s recent multi-threading support added tests to check for concurrency race conditions, and uncovered one in CI. Debugging these failing tests uncovered that `update()` calls …
> Fix racing tests.

- packages/perspective-viewer-d3fc/src/js/charts/xy-scatter.js
- packages/perspective-viewer-d3fc/src/js/series/pointSeriesCanvas.js
- packages/perspective-viewer-d3fc/src/js/series/seriesColors.js
This PR continues the work in #2258. It needed to be rebased and tweaked. @zxy994 your commits are preserved.
> Fix XY-Scatter Plots Colors - Rebased

- packages/perspective/src/js/perspective.js
Removes empty column skip from `parse_expression_strings` in `@finos/perspective`. This allows `validate_expressions` to validate any empty columns
Fixes #2268
> Fix empty column name validation in ExprTk editor

- cpp/perspective/src/cpp/context_grouped_pkey.cpp
- cpp/perspective/src/cpp/context_one.cpp
- cpp/perspective/src/cpp/context_two.cpp
- cpp/perspective/src/cpp/context_zero.cpp
- cpp/perspective/src/cpp/expression_tables.cpp
- cpp/perspective/src/cpp/gnode.cpp
- cpp/perspective/src/include/perspective/context_common_decls.h
- cpp/perspective/src/include/perspective/expression_tables.h
- cpp/perspective/src/include/perspective/gnode.h
- python/perspective/perspective/tests/table/test_remove.py
Fixes a bug which causes expression columns to show `null` or `0` results when a `remove()` had taken place before. 
When a `View` with `expressions` is created from a `Table` that has had `remove()` applied to it, some aggregates (like `sum`) are calculated incorrectly, as in the example below. Interestingly, this issue only occurs when the `remove()` occurs _before_ the `view()`. If all `remove()` calls occur _after_ the view is created, a slightly different code path correctly calculates the expressions.
Ultimately this issue was caused by a few under-tested code paths, in which he wrong mapping was chosen deep in a giant block of data processing code., given a choice between the "original" and `remove()`-corrected indices when matching primary keys to column's row index. The repro …
> Fix expression column aggregate calculation with `group_by` after `remove()`

- rust/perspective-viewer/Cargo.lock
- rust/perspective-viewer/build.js
- rust/perspective-viewer/build.rs
- rust/perspective-viewer/src/rust/components/column_dropdown.rs
- rust/perspective-viewer/src/rust/components/filter_dropdown.rs
- rust/perspective-viewer/src/rust/components/function_dropdown.rs
- rust/perspective-viewer/src/rust/components/style/mod.rs
Refactors `build.rs` to use `OUT_DIR` env var for directing generated CSS output, which is useful for Rust importers of `perspective`.
> Fix build.rs escaping OUT_DIR

- rust/perspective-viewer/src/rust/session.rs
Fixes an issue which caused `<perspective-viewer>` to delete, then recalculate, the same view in some cases, particularly around initial-load time. With this PR, `<perspective-viewer>` now uses it's internal configuration struct's equality to determine if re-rendering should occur.
> Fix over-calculation in when loading data in `perspective-viewer`

- cpp/perspective/src/cpp/context_grouped_pkey.cpp
- cpp/perspective/src/cpp/context_one.cpp
- cpp/perspective/src/cpp/context_two.cpp
- cpp/perspective/src/cpp/context_zero.cpp
- cpp/perspective/src/cpp/expression_tables.cpp
- cpp/perspective/src/cpp/gnode.cpp
- cpp/perspective/src/cpp/gnode_state.cpp
- cpp/perspective/src/cpp/view.cpp
- cpp/perspective/src/include/perspective/context_common_decls.h
- cpp/perspective/src/include/perspective/expression_tables.h
- cpp/perspective/src/include/perspective/gnode_state.h
- tools/perspective-bench/src/js/worker.js
Fixes an issue with expression calculation which caused expressions to be (approximately) calculated twice on `View` creation, due to mis-ordering the calculation of primary key indexing of input rows. Improves performance of the inital creation of any `View` with an `expressions` field.
Adds GIL-release to the `to_columns_string()` method.
> Fix `update()` with `expressions` overcalc

- examples/react-example/tsconfig.json
- examples/react-example/webpack.config.js
- package.json
- packages/perspective-cli/package.json
- packages/perspective/package.json
- rust/perspective-viewer/package.json
- yarn.lock
Fixes support for the `moduleResolution: "bundler"` flag included in Typescript >5, which reads Perspective's `exports` metadata but requires the type definitions file `index.d.ts` to be included.
> Fix TypeScript 5 `moduleResolution: "bundler"` support

- binder/apt.txt
- binder/postBuild
- binder/requirements.txt
- binder/runtime.txt
Do not merge until I can actually test on binder, im having issues getting it to respond
https://mybinder.org/v2/gh/finos/perspective/tkp/binder?urlpath=lab/tree/examples/jupyter-notebooks
> Fix binder installation to not manage dependencies seperately

- examples/promo/webpack.config.js
- examples/workspace-editing-python/src/index.js
- examples/workspace-editing-python/src/index.less
- examples/workspace-editing-python/webpack.config.js
- examples/workspace/src/index.js
- examples/workspace/src/index.less
- examples/workspace/webpack.config.js
This PR fixes a few issues:
- web pack `contentBase` was renamed to `static`
- import of `@finos/perspective-workspace` no longer include `@finos/perspective-viewer`, so that needs to be imported separately
- same but for CSS assets
> Update webpack dev server configuration options, fixes for perspective 2.0+

- packages/perspective-viewer-datagrid/src/js/plugin/activate.js
- rust/perspective-viewer/src/less/containers/split-panel.less
- rust/perspective-viewer/src/less/viewer.less
This PR fixes a few small bugs.
- The perspective-datagrid-plugin was throwing some annoying errors when you switched between plugins. This was because we are registering an event listener on the perspective-viewer element, and it is never being unregistered. The only way we can unregister the event listener is to add a `deactivate` method to the API where we can clean up the listeners. For now, I  added a quick hack.
- Fixed some visual bugs regarding borders on the side panels. The top border should no longer shrink and the column settings panel should now go beneath the settings panel when resizing.
> fix some viewer bugs

- examples/blocks/src/file/index.html
- packages/perspective-viewer-datagrid/build.js
- packages/perspective-viewer-datagrid/src/less/pro.less
- packages/perspective-viewer-datagrid/src/less/regular_table.less
- packages/perspective-viewer-datagrid/src/less/row-hover.less
- packages/perspective-viewer-datagrid/src/less/scrollbar.less
- packages/perspective-viewer-datagrid/src/less/sub-cell-scroll.less
- rust/perspective-viewer/Cargo.lock
- rust/perspective-viewer/src/themes/monokai.less
- rust/perspective-viewer/src/themes/pro-dark.less
- rust/perspective-viewer/src/themes/solarized.less
- rust/perspective-viewer/src/themes/vaporwave.less
- tools/perspective-scripts/publish.mjs
Restyles datagrid rows to appear to cover the full plugin container width, without changing their scrolling or sizing behavior.
> Datagrid rows restyle

- rust/perspective-viewer/src/rust/components/column_settings_sidebar/style_tab.rs
- rust/perspective-viewer/src/rust/components/number_column_style.rs
- rust/perspective-viewer/src/rust/js/perspective.rs
Number style gradient values were not being populated. This uses the same code as an older version, but reimplemented in rust.
No tests were added or changed.
> fix gradient values

- cpp/perspective/src/cpp/computed_expression.cpp
- cpp/perspective/src/cpp/computed_function.cpp
- cpp/perspective/src/cpp/context_grouped_pkey.cpp
- cpp/perspective/src/cpp/context_one.cpp
- cpp/perspective/src/cpp/context_two.cpp
- cpp/perspective/src/cpp/context_zero.cpp
- cpp/perspective/src/cpp/emscripten.cpp
- cpp/perspective/src/cpp/gnode.cpp
- cpp/perspective/src/cpp/gnode_state.cpp
- cpp/perspective/src/cpp/table.cpp
- cpp/perspective/src/include/perspective/computed_expression.h
- cpp/perspective/src/include/perspective/computed_function.h
- cpp/perspective/src/include/perspective/context_common_decls.h
- cpp/perspective/src/include/perspective/gnode.h
- cpp/perspective/src/include/perspective/gnode_state.h
- cpp/perspective/src/include/perspective/raw_types.h
- packages/perspective/src/js/perspective.js
- packages/perspective/test/js/expressions/functionality.spec.js
- python/perspective/perspective/src/view.cpp
- python/perspective/perspective/table/_utils.py
- rust/perspective-viewer/src/rust/exprtk/language.rs
This adds `index()` which returns the primary key of the current row, `col('column_name')` which is essentially the same as `"column_name"` except that it takes a string literal, and `vlookup('column_name', index)` which will lookup a value in a column by primary key such that `col('a') == vlookup('a', index())`.
> Add `index()`, `col()`, and `vlookup()` to ExprTk

- rust/perspective-viewer/src/rust/custom_elements/viewer.rs
- rust/perspective-viewer/src/rust/js/intersection_observer.rs
- rust/perspective-viewer/src/rust/js/mod.rs
- rust/perspective-viewer/src/rust/model/intersection_observer.rs
- rust/perspective-viewer/src/rust/model/mod.rs
- rust/perspective-viewer/src/rust/model/resize_observer.rs
- rust/perspective-viewer/src/rust/session.rs
- rust/perspective-viewer/src/ts/viewer.ts
This PR adds a new API method to the `<perspective-viewer>` custom element, `setAutoPause()`. When enabled with `viewer.setAutoPause(true)`, the `<perspective-viewer>` will register an `IntersectionObserver` to test its own visibility, enabling a new internal "pause" state when offscreen. The new "pause" state deletes its internal `View`, freeing any resources associated with it, and doesn't recreate it until the `IntersectionObserver` changes state, so while efficient for many small-data viewers, this may not yet be the right feature for a handful of large-data viewers. A future iteration which does _not_ delete the `View` (but just supresses rendering) may be a future iteration of this feature.
> Add `setAutoPause()` method

- python/perspective/perspective/core/data/pd.py
- python/perspective/perspective/tests/table/test_table_pandas.py
Add support for StringDtype (available in Pandas >=1.0)
Fixes #1237 
AFTER
> Add support for StringDtype (fixes #1237)

- cpp/perspective/build.js
- cpp/perspective/package.json
- cpp/perspective/src/include/perspective/scalar.h
- packages/perspective/package.json
- packages/perspective/src/js/perspective.browser.js
- packages/perspective/src/js/perspective.js
- packages/perspective/src/js/perspective.node.js
- rust/perspective-viewer/Cargo.lock
- rust/perspective-viewer/Cargo.toml
- rust/perspective-viewer/package.json
- rust/perspective-viewer/src/rust/lib.rs
- rust/perspective-viewer/src/rust/utils/console_logger.rs
- rust/perspective-viewer/src/ts/init.ts
- rust/perspective-viewer/tasks/bootstrap-runtime/Cargo.toml
- rust/perspective-viewer/tasks/bootstrap-runtime/lib.rs
- rust/perspective-viewer/tasks/bootstrap/Cargo.toml
- rust/perspective-viewer/tasks/bootstrap/main.rs
- tools/perspective-scripts/sh_perspective.mjs
- yarn.lock
Moves wasm loading for `@finos/perspective` and `@finos/perspective-viewer` packages to a new Rust-based self-extracting binary. Improves Perspective asset load and compilation performance by 5x.
Old webassembly load + first render performance profile:
New:
> Self-extracting WebAssembly binaries

- packages/perspective-viewer-d3fc/src/js/charts/xy-scatter.js
- packages/perspective-viewer-d3fc/src/less/chart.less
- packages/perspective-viewer-datagrid/src/js/event_handlers/edit_click.js
- rust/perspective-viewer/src/rust/components/column_settings_sidebar/style_tab/symbol.rs
- rust/perspective-viewer/src/rust/components/column_settings_sidebar/style_tab/symbol/types.rs
- rust/perspective-viewer/src/rust/components/containers/kvpair.rs
This PR changes the X/Y Scatter plot's symbol serialization format to a dictionary. It also fixes a bug in the datagrid. (Editable bools were not toggling correctly.)
> X/Y Scatter Symbol Serialization as Dictionary

- examples/blocks/index.mjs
- examples/blocks/package.json
- examples/blocks/src/superstore/README.md
- packages/perspective-viewer-datagrid/test/js/superstore.spec.js
- rust/perspective-viewer/src/rust/custom_elements/copy_dropdown.rs
- rust/perspective-viewer/src/rust/custom_elements/export_dropdown.rs
- rust/perspective-viewer/src/rust/session.rs
- tools/perspective-scripts/sh.mjs
Also included is some style and spelling fixes.
> Fix Blocks build script execution

- packages/perspective-jupyterlab/test/jupyter/widget.spec.js
- python/perspective/perspective/viewer/viewer.py
Fixes https://github.com/finos/perspective/issues/2464
The version keyword should be ignored when restoring the widget, as it does not affect the widget itself. The version keyword is currently only used for migrations. Eventually, I would like to see automatic migrations based on version number, which will require a more sophisticated solution. This works for now :)
> Fix Jupyterlab Widget Save/Restore Symmetry

- rust/perspective-viewer/Cargo.toml
- rust/perspective-viewer/src/rust/components/containers/scroll_panel_item.rs
- rust/perspective-viewer/tasks/bundle/main.rs
This PR fixes some outstanding issues with consuming the `perspective` Rust library, which is not well tested in this repo.
* Adds back the `define_custom_elements_async` feature which is necessary when the `perspective-viewer` TypeScript loader is not present.
* Removes `release_max_level_error` feature from `tracing` which pollutes consumers who may wish to see their own `tracing` logs.
> Fix cargo features

- packages/perspective-jupyterlab/src/less/index.less
> Fix output scrolling in Jupyter when `perspective-python` is installed

- packages/perspective-viewer-datagrid/package.json
- yarn.lock
Fixes a bug which caused the datagrid to over-subscribe to the engine on scroll events, causing more calculation than necessary on sub-cell viewport scrolling. In virtual (server-only) python or node.js configurations, this PR will visibly improve scroll performance especially in the horizontal (column) axis.
> Fix datagrid scroll performance regression via `regular-table` upgrade

- examples/esbuild-example/package.json
- examples/promo/package.json
- examples/webpack-cross-origin/package.json
- examples/workspace-editing-python/package.json
- examples/workspace/package.json
- yarn.lock
The `http-server` dependency used by the `/examples` projects no longer works in Chrome because it sets the `Content-Type` header for wasm assets to `application/wasm; charset=utf-8`, which is not a valid mimetype for `WebAssembly.instantiateStreaming()`.  [Related `http-server` bug](https://github.com/http-party/http-server/issues/690)
Unsure how this regression was introduced, as it certainly worked when it was written.
> Update `http-server` examples dependency

- rust/perspective-viewer/src/less/aggregate-selector.less
- rust/perspective-viewer/src/less/column-selector.less
- rust/perspective-viewer/src/less/type-icon.less
- rust/perspective-viewer/src/rust/components/column_selector/active_column.rs
- rust/perspective-viewer/src/rust/components/column_selector/filter_column.rs
- rust/perspective-viewer/src/rust/components/column_selector/inactive_column.rs
- rust/perspective-viewer/src/rust/components/column_selector/pivot_column.rs
- rust/perspective-viewer/src/rust/components/column_selector/sort_column.rs
- rust/perspective-viewer/src/rust/components/editable_header.rs
- rust/perspective-viewer/src/rust/components/type_icon.rs
This PR (original @ada-x64) addresses inconsistent column width for the setting panel introduces partially in #2459
Fixed version of #2525
> Settings panel width is inconsistent for columns moved to `Config`

- packages/perspective-viewer-datagrid/src/js/custom_elements/datagrid.js
- packages/perspective-viewer-datagrid/src/less/mitered-headers.less
- packages/perspective-viewer-datagrid/src/less/regular_table.less
- rust/perspective-viewer/src/themes/dracula.less
- rust/perspective-viewer/src/themes/gruvbox-dark.less
- rust/perspective-viewer/src/themes/gruvbox.less
- rust/perspective-viewer/src/themes/monokai.less
- rust/perspective-viewer/src/themes/pro-dark.less
- rust/perspective-viewer/src/themes/pro.less
- rust/perspective-viewer/src/themes/solarized.less
- rust/perspective-viewer/src/themes/vaporwave.less
Moving datagrid's regular-table into shadow DOM caused some CSS regressions. These changes fix a few that we've spotted, particularly in the table header.
> A few CSS fixes for regular-table in shadow DOM

- rust/perspective-viewer/src/rust/components/column_settings_sidebar/sidebar.rs
- rust/perspective-viewer/src/rust/components/viewer.rs
- rust/perspective-viewer/test/js/column_settings/interactions.spec.ts
- tools/perspective-test/src/js/models/settings_panel.ts
Before:
https://github.com/finos/perspective/assets/41482263/444c7bce-c1a5-4e0b-b63a-2aadebaab660
After:
https://github.com/finos/perspective/assets/41482263/e21b56d6-358a-4eb3-a04e-9900c61cb09f
Column settings sidebar was dropping its session sub :facepalm:
> Bugfix - De-aggregating doesn't change column style type

- .vscode/settings.default.json
- packages/perspective-viewer-datagrid/src/less/scrollbar.less
- rust/perspective-viewer/src/less/column-settings-panel.less
- rust/perspective-viewer/src/less/column-style.less
- rust/perspective-viewer/src/less/dom/checkbox.less
- rust/perspective-viewer/src/less/expression-editor.less
- rust/perspective-viewer/src/rust/components/column_settings_sidebar/save_settings.rs
- rust/perspective-viewer/src/rust/components/column_settings_sidebar/sidebar.rs
- rust/perspective-viewer/src/rust/components/column_settings_sidebar/style_tab/column_style.rs
- rust/perspective-viewer/src/rust/components/form/color_range_selector.rs
- rust/perspective-viewer/src/rust/components/number_column_style.rs
- rust/perspective-viewer/test/js/column_settings.spec.ts
* Implements a new color selector component, featuring:
* Gradient controls thermometer previews the `linear-gradient` for the current settings.
* Contrast-appropriate auto indicator foreground.
* More ornate styling + hover styles.
Also:
* Fixes missing scrollbars in datagrid.
* Fixes expression editor error overflow causing panel resize.
* Fixes `Expression` title jitter on vertical panel resize.
* Adds VSCode default settings to build cargo in a dedicated output dir (so local builds do not cause `rust-analyzer` to rebuild the project form scratch on save).
* Removes `Styling` title from column styling sidebar.
> New color selector component

- .github/workflows/build.yml
- docs/build.js
- docs/src/components/HomepageFeatures/python.md
- docs/template.html
- docs/test/js/examples.spec.ts
- packages/perspective-viewer-d3fc/test/js/area.spec.ts
- packages/perspective-viewer-d3fc/test/js/line.spec.ts
- rust/perspective-viewer/README.md
- rust/perspective-viewer/src/ts/migrate/2-6-1.ts
- tools/perspective-test/playwright.config.ts
- tools/perspective-test/src/js/utils.ts
Currently on https://perspective.finos.org, there are broken examples on the home page. This occurs on X/Y scatter plots due to a failing migration.
Building and testing on main does not replicate the bug, as the website is running on v2.7.1 and [a fix has been added](https://github.com/finos/perspective/commit/3b648543e60805c98c0e5bb4fece03caa4341f6d) since that release.
This PR simply adds tests for the examples (one for each example, totaling 75) to ensure this doesn't happen again.
> Add Docs Tests

- cpp/perspective/src/cpp/emscripten.cpp
- cpp/perspective/src/cpp/view.cpp
- cpp/perspective/src/include/perspective/view.h
- packages/perspective-viewer-datagrid/test/js/superstore.spec.js
- packages/perspective/src/js/perspective.js
- packages/perspective/test/js/pivots.spec.js
Fixes #2544 and fixes #2306.
When `split_by` with a column of type `"date"` or `"datetime"`, the internal viewport data is returned with column paths helpfully formatted as strings (_helpfully_ due to a legacy internal format which does not properly support mixed types in column paths just yet). However, the `column_paths()` methods still returns `t_tscalar`, which _sometimes_ is the same as the string representation, but is _not_ when the type is `"date"` or `"datetime"`. This caused Datagrid column group headers to show up as POSIX timestamps, but also caused the column paths to fail lookup when populating the table itself, causing the column to appears as all `null`.
This PR changes the behavior of the `column_paths()` method to explicitly `to_string()` column path values, and adds a …
> Fix `split_by` with `date`/`datetime` columns

- packages/perspective-viewer-d3fc/src/ts/data/ohlcData.ts
Fixes regression (in #2432) which causes Candlestick and OHLC charts to now work.
This was a _dumb_ break, a refactor guided by the type checker which made all the _red_ go away in the IDE, but which _obviously_ broke the logic in question. Tests > Types.
> Fix Candlestick & OHLC charts

- python/perspective/perspective/client/base.py
- python/perspective/perspective/tests/handlers/test_starlette_handler.py
It was returning None. It now returns a future which resolves to the list of hosted table names.
> Fix get_hosted_table_names in Python client

- python/perspective/setup.py
This is a really minor bug, but causes some annoyance during our build process and is the reason we have to explicitly set `PSP_GENERATOR` in a few places.
> Fix compatibility with other MSVC versions by explicitly converting to string

- .github/workflows/build.yml
CI is currently failing due to https://github.com/pyodide/pyodide/issues/4655
This PR bumps pyodide to 0.25.1 to fix CI.
> Update to pyodide 0.25.1 for pyodide/pyodide#4655

- CONTRIBUTING.md
This PR removes the CLA language from Perspective's contributing docs, and replaces it with language reflecting the project's new DCO process. [Added by @texodus]
> Update contributing documentation for DCO

- python/perspective/perspective/src/view.cpp
Fixes a GIL scoping issue which caused intermittent failure when the `to_arrow()` method is called in Python (and any method which internally uses `to_arrow()`). Fixes #2597
> Fix intermittent `to_arrow()` error in Python

- python/perspective/perspective/manager/manager_internal.py
This PR fixes `perspective-python`'s `Table.delete()` and `View.delete()` methods, which do not resolve in their clients when awaited. While this does not leak _data_, it does leak await-ed `delete()` handlers.
> Fix `delete()` Python async call not resolving

- cpp/perspective/src/cpp/sparse_tree.cpp
This PR parallelizes column population during `group_by` tree calculation. The result is a substantial improvement to the wall-clock runtime of `View()` creation using this field, which scales with the # of cores and `View` columns. For example, in an 8-thread pool tested on with 50k rows * 20 columns dataset grouped by a `string` column, the wall clock improvements is ~2x.
> Calculate `group_by` in parallel

- packages/perspective-viewer-d3fc/src/ts/gridlines/gridlines.ts
Adds prominent highlighting of the 0 axis to scatter charts.
> Draw 0 axis prominently

- .gitignore
- packages/perspective-jupyterlab/build.mjs
- packages/perspective-jupyterlab/package.json
- packages/perspective-jupyterlab/webpack.config.js
- pnpm-lock.yaml
- rust/perspective-python/build.mjs
- rust/perspective-python/perspective.data/data/share/jupyter/labextensions/@finos/perspective-jupyterlab/install.json
- rust/perspective-python/pyproject.toml
- tools/perspective-scripts/repack_wheel.mjs
Fixes `perspective-python` prebuilt JupyterLab extension packaging for Windows, where some Node.js' `fs` module functions do not behave as they do on Linux/OSX.
> Fix Windows JupyterLab packaging

- cmake/arrow/CMakeLists.txt
- cmake/modules/FindInstallDependency.cmake
- cpp/perspective/CMakeLists.txt
Hello! And a good day to you.
This PR adds support for decompressing Arrows compressed with [Facebook's Zstd](https://github.com/facebook/zstd/). This PR does not add _compression_ into zstd.
> Zstd decompression for arrows

- rust/perspective-viewer/src/rust/model/export_app.rs
Firefox throws a warning 
> Bogus doctype.Quirky doctype. Expected “<!DOCTYPE html>”.
> fix: Doctype in html export

- rust/perspective-python/perspective/__init__.py
- rust/perspective-python/perspective/psp_cffi.py
- rust/perspective-python/perspective/tests/core/test_async.py
- rust/perspective-python/perspective/tests/server/test_server.py
- rust/perspective-python/perspective/tests/server/test_session.py
- rust/perspective-python/perspective/tests/table/test_table_pandas.py
- rust/perspective-python/perspective/viewer/viewer_traitlets.py
- rust/perspective-python/src/client/client_sync.rs
- rust/perspective-python/src/client/python.rs
- rust/perspective/src/lib.rs
* #2707 moved the C++ API from `perspective-server`, but also changed the API (from `close` to `__del__`). 
Fixes #2719
* Added `Client::terminate` to the Python client (so `Session::close` can be tested with the (only) synchronous `Client`).
* Added tests and removed test warnings.
> Fix `PerspectiveTornadoHandler` misnamed `close()`

- cpp/perspective/src/cpp/vendor/arrow_single_threaded_reader.cpp
- cpp/perspective/src/include/perspective/vendor/arrow_single_threaded_reader.h
- packages/perspective-jupyterlab/test/jupyter/widget.spec.mts
- rust/perspective-server/build/main.rs
Fixes an issue with `perspective-python`'s emscripten wheel which caused some functions to fail with missing symbol errors.
> Fix link error in emscripten wheel

- rust/perspective-client/docs/client/table.md
- rust/perspective-client/src/rust/lib.rs
- rust/perspective-client/src/rust/table.rs
- rust/perspective-js/src/rust/client.rs
- rust/perspective-js/src/rust/table.rs
- rust/perspective-js/src/rust/utils/errors.rs
- rust/perspective-js/test/js/constructors/csv.spec.ts
- rust/perspective-python/perspective/tests/table/test_table.py
- rust/perspective-python/src/client/client_sync.rs
- rust/perspective-python/src/client/python.rs
This PR extends Python and JavaScript APIs to allow `String`/`str`/`bytes`/`ArrayBuffer`/`UInt8Array` input data types for JSON Rows/Columns and CSV data, using the new `format` keyword argument to `Client::table`. This is useful several interesting performance optimizations, such as:
* Using `.arrayBuffer()` over `.text()` for `Response` objects containing CSVs (Fixes #2746).
* Reading JSON from a file or other unparsed source without deserializing.
Use it like this:
```javascript
data = '{"x": [1,2,3], "y": [4,5,6]}';
table = await client.table(data, {format: "columns"});
```
Included are tests and keyword argument docs for both Python and JavaScript.
> Allow `bytes` and `string` for JSON/CSV input data with `format` option

- cpp/perspective/src/cpp/data_table.cpp
- cpp/perspective/src/cpp/server.cpp
- cpp/perspective/src/cpp/view_config.cpp
- cpp/perspective/src/include/perspective/view_config.h
- rust/bootstrap-runtime/lib.rs
- rust/perspective-js/test/js/filters.spec.js
- rust/perspective-js/test/js/view_config.spec.js
Fixes a bug introduced In `3.0.0` and introduces two tests (one of which fails pre-fix).
In this version, the translation layer between a domain-language `ViewConfig` (Python `dict` or JavaScript `Object`) was rewritten and ported to C++, in which we neglected to accommodate for `t_tscalar`'s SSO optimization which inlines string under 13 characters. As this type is used for a filter parameter's term component, this leads to a dangling pointer error when the `get_view_config()` public method was invoked with a filter value above this limit. 
Fixes #2781
> Fix filter values for non-interned strings

- rust/perspective-viewer/src/rust/components/column_selector/config_selector.rs
- rust/perspective-viewer/src/rust/components/column_selector/filter_column.rs
- rust/perspective-viewer/src/rust/components/column_selector/pivot_column.rs
- rust/perspective-viewer/src/rust/components/column_selector/sort_column.rs
This PR fixes the issue of icons of columns defaulting to string icon instead of the right data type in issue #2580
> Column type icon matches the datatype type of the field in column selectors (where, group by, sortby, filter)

- rust/perspective-viewer/src/rust/components/form/code_editor.rs
- rust/perspective-viewer/test/js/column_settings/attributes_tab.spec.ts
I have reopened this PR after #2747 for issue #2703.
1. On the `TAB` key press, `\t` is inserted into the caret's position.
2. There is a test to confirm the behavior.
> <TAB> key press inserts '\t' character in code editor as indentation.

- cmake/toolchains/darwin-arm64.cmake
- cmake/toolchains/darwin-x86_64.cmake
- rust/perspective-server/build/psp.rs
This fixes the issue with missing LZ4 symbols in the arm64 wheel first introduced in v3.1.1.
The crux of the issue is that Arrow was building lz4 (and zstd) in a separate cmake build, and it does not specially pass on the `CMAKE_OSX_ARCHITECTURES` flag that was set when perspective-server's build script invokes cmake.
Arrow's build does forward on the value of CMAKE_TOOLCHAIN_FILE to its external dependencies, if it's set, so this commit creates two minimal toolchain files and uses them in the Mac build to set `CMAKE_OSX_ARCHITECTURES` (and a couple other variables) correctly when cross-compiling.
a good follow-up would be to see if we can enable Python tests on arm64 using a macos-14 runner, which is available for public repos: <https://docs.github.com/en/actions/using-github-hosted-runne …
> arrow: Fix cross-compiling errors on macos

- .github/workflows/build.yaml
- rust/perspective-server/build/psp.rs
This PR follows up #2798. We weren't previously testing the aarch64 wheel in CI. This adds a macos-14 runner, which is aarch64 native.
I also restored the previous dev environment behavior when PSP_ARCH is not set: instead of a fatal build error, the build just doesn't set `CMAKE_OSX_ARCHITECTURES` (et al).
-   [x] Description contains a link to the Github Issue, and any relevent Discussions, this PR applies to.
-   [x] Include new tests that fail without this PR but passes with it.
- the new tests (new test runner, really) would have failed before #2798
-   [x] Include any relevent Documentation changes related to this change.
-   [x] Verify all commits have been _signed_ in accordance with the DCO policy.
-   [x] …
> Add aarch64 Mac runners to test_python, restore PSP_ARCH dev behavior

- packages/perspective-esbuild-plugin/wasm.js
Minification sometimes adds `$` to variable names causing it to be interpreted as regex rather than literally.
> Escape esbuild plugin's symbol replacement.

- rust/perspective-python/perspective/handlers/aiohttp.py
aiohttp will throw if the handler doesn't return anything.
```python
14:11:35 aiohttp ERRO Missing return statement on request handler
Traceback (most recent call last):
File "/Users/steve/conda/envs/port/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 653, in finish_response
prepare_meth = resp.prepare
^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'prepare'
```
Fixes #2805
https://docs.aiohttp.org/en/stable/web_quickstart.html#websockets
-   [x] Description contains a link to the Github Issue, and any relevent
-   [ ] Include new tests that fail without this PR but passes with it.
-   [x] Include any relevent Documentation changes related to this change.
- …
> fix aiohttp disconnect error on websockets

- .cargo/config.toml
- .github/workflows/build.yaml
- .gitignore
- packages/perspective-jupyterlab/build.mjs
- pnpm-lock.yaml
- rust/perspective-python/Cargo.toml
- rust/perspective-python/build.mjs
- rust/perspective-python/package.json
This updates the perspective-python build to create an sdist tarball by
hand, not going through `maturin sdist`. This bypasses some issues we
have seen with Maturin mispackaging the perspective Cargo workspace in
the sdist.
Maturin is still used as the `build-backend` to build a wheel from the
sdist.  CI still uses `maturin build` to build wheels.  Local
development builds still use `maturin develop`.
The sdist now includes the .data directory so that Maturin will place it
in the wheel correctly.  Building an sdist with PSP_BUILD_SDIST=1 will
now error if it appears the jupyterlab plugin was not built into the
.data directory.
Most of the work is in generating a PKG-INFO file.  Its output matches
what's in the 3.1.2 sdist on pypi, minus a correction to fix the
`Home-page` field …
> Fix `perspective-python` sdist and add sdist tests to CI

- .github/actions/install-deps/action.yaml
- .github/workflows/build.yaml
- cmake/arrow.txt.in
- cpp/perspective/CMakeLists.txt
- cpp/perspective/src/cpp/utils.cpp
- rust/perspective-server/build/psp.rs
Follow ups for #2811 
- Make the new test_python_sdist run only on release tags
- Remove vcpkg from Windows install-deps action
- Fix some cmake issues that broke the Windows conda build
-   [x] Description contains a link to the Github Issue, and any relevent
-   [x] Include new tests that fail without this PR but passes with it.
-   [x] Include any relevent Documentation changes related to this change.
-   [x] Verify all commits have been _signed_ in accordance with the DCO policy.
-   [x] Reviewed PR commit history to remove unnecessary changes.
-   [x] Make sure your PR passes _build_, _test_ and _lint_ steps _completely_.
> CI sdist fixes, port conda patch, fix ODR violation

- packages/perspective-jupyterlab/test/jupyter/widget.spec.mts
- packages/perspective-viewer-datagrid/src/js/model/toolbar.js
This PR fixes a regression in the `PerspectiveWidget` Python extension. In `3.0.0`, selection modes were added to Perspective's datagrid component; however, we neglected to test this feature when the settings are updated for a detached (hidden) viewer. This is not a common feature typically, but is coincidentally a state of the default `PerspectiveWidget` loading workflow due to the lack of a working end-to-end async model for `perspective` and `perspective-viewer` remote calls. As a result, switching _to_ the Datagrid plugin in Jupyter will throw a runtime exception.
This PR fixes patches this behavior and adds a test for JupyterLab. However, it _does not_ resolve the underlying inconsistency which is async ordering issues imposed by the current `PerspectiveWidget` architecture. We will …
> Fix `plugin` switch 

- cpp/perspective/src/cpp/scalar.cpp
- cpp/perspective/src/cpp/sparse_tree.cpp
- packages/perspective-workspace/package.json
- pnpm-lock.yaml
- rust/perspective-js/test/js/expressions/numeric.spec.js
This PR fixes an integer-underflow bug encountered when calculating `sum` aggregates over `integer` columns which had been generated by an expression. See the included test for an example using the Perspective ExprTK `integer()` cast function.
> Fix `integer` cast expression function

- .github/workflows/build.yaml
- .gitignore
- Cargo.lock
- rust/generate-metadata/Cargo.toml
- rust/generate-metadata/main.rs
- rust/perspective-python/Cargo.toml
- rust/perspective-python/build.mjs
- rust/perspective-python/pyproject.toml
- rust/perspective-server/build/psp.rs
This adds LICENSE.md from perspective to the sdist, and uses `cargo-bundle-licenses` to bundle perspective-python's dependency licenses into LICENSE_THIRDPARTY_cargo.yml, which is also added to the sdist.
When Maturin builds a wheel, it searches the source for files named `LICENSE*` (among others) and includes them in dist-info. C++ license packaging can use this same framework: we'll generate a file in the perspective-python source tree which aggregates licenses from arrow and other bundled C++ dependencies.
Adds a basic test of the license packaging to the sdist test. Note that this doesn't test the wheels we distribute, which takes a different build path in CI.
> sdist licensing follow ups

- rust/perspective-python/perspective/__init__.py
- rust/perspective-python/perspective/tests/table/test_table.py
- rust/perspective-python/perspective/tests/test_dependencies.py
- rust/perspective-python/src/client/client_sync.rs
- rust/perspective-python/src/client/python.rs
- rust/perspective-python/src/client/table_data.rs
- rust/perspective-python/src/client/update_data.rs
- rust/perspective-python/src/lib.rs
- rust/perspective-python/src/py_err.rs
This PR adds support for using native Python types as column type specifiers, when creating a Perspective `Table` from a schema. The available types are based on the types allowed in 2.10.1:
```python
table = perspective.table({
"integer": int,
"float": float,
"string": str,
"boolean": bool,
"date": datetime.date,
"datetime": datetime.datetime,
})
```
It is worth noting that despite the use of `date` and `datetime` python types as schema specifiers for legacy support, 3.x does _not_ support `date` or `datetime` _values_ when provided to the `table` constructor function in a `dict` or `list` input type (though you may extend native `json` parsing to allow this, or use `pandas.DataFrame` to marshall these to for you, see the 3.x release notes).
This support is a convenience feature for …
> Relax `Table` schema constructor

- rust/perspective-python/docs/client/to_pandas.md
- rust/perspective-python/docs/client/to_polars.md
- rust/perspective-python/docs/lib.md
- rust/perspective-python/perspective/tests/table/test_table_polars.py
- rust/perspective-python/requirements.txt
- rust/perspective-python/src/client/client_sync.rs
- rust/perspective-python/src/client/mod.rs
- rust/perspective-python/src/client/polars.rs
- rust/perspective-python/src/client/python.rs
This is a naive rust implementation of conversion to/from polars. I describe it as “naive” as it incurs an “extra” copy of polars-wrapped arrow table to binary buffer to perspective. 
A test suite is included, copied from pandas but omitting some pandas-specific functionality, and skipping some stuff that might warrant a further look (polars converts to several arrow types that we don’t currently support). 
Some initial TODOs:
> Support input/output to/from polars via python (not native rust)

- rust/perspective-python/src/client/pandas.rs
catch the import error and re-raise with a clear message that perspective is requiring this import explicitly (its a bit confusing in a normal stack trace), fixes #2847
With this change:
> Check pyarrow import and make clear(er) error message

- cpp/perspective/src/cpp/arrow_loader.cpp
- docs/src/components/DocItem/browser.js
- examples/blocks/src/raycasting/index.js
- packages/perspective-esbuild-plugin/index.js
- packages/perspective-esbuild-plugin/wasm.js
- packages/perspective-esbuild-plugin/worker.js
- rust/perspective-python/perspective/tests/table/test_table_arrow.py
- rust/perspective-python/src/client/client_sync.rs
- rust/perspective-python/src/server/server_sync.rs
* Fixed empty Arrow `Table` constructor bug #2844
* Fixed `perspective-python` objects repr to read e.g. `<class 'perspective.PySyncServer'>` instead of `<class 'builtins.PySyncServer'>`
* Fixed minification bug with `perspective-esbuild-plugin`, and added an option `webpack_hack` which can be used to disable this problematic regex next time it decides to act up.
> Fix empty Arrow `Table` constructor

- rust/perspective-client/docs/table.md
Small docs addition describing our JSON input formats.
> Add some information on JSON input formats

- packages/perspective-workspace/src/less/menu.less
- packages/perspective-workspace/src/themes/pro-dark.less
- packages/perspective-workspace/src/themes/pro.less
- packages/perspective-workspace/src/ts/workspace/commands.ts
- packages/perspective-workspace/src/ts/workspace/tabbar.ts
- packages/perspective-workspace/src/ts/workspace/widget.ts
- packages/perspective-workspace/src/ts/workspace/workspace.ts
- rust/perspective-viewer/src/rust/custom_elements/viewer.rs
- rust/perspective-viewer/src/rust/presentation.rs
* Fix `perspective-workspace` dark theme context & bookmark menu styling.
* Fix double-render on `perspective-viewer`'s `resetThemes()` method.
> Fix workspace dark theme, theme render bug

- examples/python-starlette/server.py
- rust/perspective-python/perspective/handlers/aiohttp.py
- rust/perspective-python/perspective/handlers/starlette.py
- rust/perspective-python/perspective/handlers/tornado.py
More details discussed separately, not done in this PR so don't merge yet
Expectation:
Reality:
Only first value is used, no updating is propagated through the web server (wrong loop at time of callback)
`index.html`
```html
<html>
<head>
<script type="module" src="https://cdn.jsdelivr.net/npm/@finos/perspective/dist/cdn/perspective.js"></script>
<script type="module" src="https://cdn.jsdelivr.net/npm/@finos/perspective-viewer/dist/cdn/perspective-viewer.js"></script>
<script type="module" src="https://cdn.jsdelivr.net/npm/@finos/perspective-viewer-datagrid/dist/cdn/perspective-viewer-datagrid.js"></script>
<script type="module" src="https://cdn.jsdelivr.net/npm/@finos/perspective-viewer-d3fc/dist/cdn/perspective-viewer-d3fc.js"></script>
<link rel="stylesheet" crossorigin="anonymous" …
```
> Allow for passthrough of event loop in psp webserver handlers

- packages/perspective-viewer-d3fc/src/ts/series/treemap/treemapSeries.ts
This pull request fixes one of the Firefox issues in #2693, specifically issue #1983
I used string interpolation for the style on the rect element (for x and y) to introduce layout consistency by adding px to the `d.x0` and `d.y0` values. I realized that without this, Firefox ignored some of the values, hence the issue.
-   [x] Description contains a link to the Github Issue, and any relevent
-   [ ] Include new tests that fail without this PR but passes with it.
-   [ ] Include any relevant Documentation changes related to this change.
-   [x] Verify all commits have been _signed_ in accordance with the DCO policy.
-   [x] Reviewed PR commit history to remove unnecessary changes.
- …
> fix treemap rendering issue in firefox

- cpp/perspective/src/cpp/arrow_loader.cpp
- examples/python-tornado-streaming/server.py
- packages/perspective-workspace/src/less/menu.less
- packages/perspective-workspace/src/ts/workspace/workspace.ts
- rust/perspective-js/test/js/constructors.spec.js
Fixes #1911, supersedes #1910
Duplicate column support has _not_ been added to Perspective itself, rather duplicates will now be automatically renamed to a unique derivative (suffixed by `*`).
Only CSV and Arrow types support this. While we may be able to implement similar feature for JSON string types, there _shouldn't_ be any libraries which support this output. We'd also need to rely on non-standard convention of key order, potentially leading to some cryptic error messages if keys come out-of-order.
> Fix duplicate columns

- cpp/perspective/src/cpp/server.cpp
- cpp/perspective/src/cpp/table.cpp
- cpp/perspective/src/cpp/view.cpp
- cpp/perspective/src/include/perspective/server.h
- cpp/perspective/src/include/perspective/table.h
- cpp/perspective/src/include/perspective/view.h
- cpp/protos/perspective.proto
- rust/perspective-client/docs/table.md
- rust/perspective-client/docs/view/to_ndjson.md
- rust/perspective-client/src/rust/table.rs
- rust/perspective-client/src/rust/table_data.rs
- rust/perspective-client/src/rust/view.rs
- rust/perspective-js/src/rust/table.rs
- rust/perspective-js/src/rust/view.rs
- rust/perspective-js/test/js/constructors.spec.js
- rust/perspective-js/test/js/to_format.spec.js
- rust/perspective-python/src/client/client_sync.rs
- rust/perspective-python/src/client/python.rs
- rust/perspective-python/src/client/update_data.rs
- rust/perspective-viewer/src/rust/components/copy_dropdown.rs
- rust/perspective-viewer/src/rust/components/export_dropdown.rs
- rust/perspective-viewer/src/rust/model/copy_export.rs
- rust/perspective-viewer/src/rust/model/export_method.rs
- rust/perspective-viewer/src/rust/session.rs
* Adds [NDJSON](https://github.com/ndjson/ndjson-spec) support to the `perspective.table()` constructor, via the `format` option.
* Adds `view.to_ndjson()` serialization method.
```javascript
const table = await perspective.table(`{"x": 1}\n{"x": 2}`, {format: "ndjson"});
const view = await table.view();
const ndjson = await view.to_ndjson();
```
> Support ndjson

- cpp/perspective/src/cpp/scalar.cpp
- cpp/perspective/src/cpp/server.cpp
- cpp/perspective/src/include/perspective/scalar.h
- rust/perspective-js/test/js/filters.spec.js
Fixes #2879 #2868, adding a test based on the former's repro.
> Fix memory corruption on filter text overflow

- cpp/perspective/src/cpp/sparse_tree.cpp
- rust/perspective-client/src/rust/config/aggregates.rs
- rust/perspective-js/test/js/pivots.spec.js
> Add `min` and `max` aggregates for `date` and `datetime` columns

- cmake/arrow.txt.in
- cpp/perspective/patches/arrow_strptime.patch
- tools/perspective-bench/cross_platform_suite.mjs
- tools/perspective-bench/puppeteer_suite.mjs
- tools/perspective-bench/src/js/benchmark.mjs
- tools/perspective-bench/src/js/superstore.mjs
Tl;DR 7x performance improvement parsing non-ISO-8601 datetime strings in CSV or JSON formats.
I've been analyzing Perspective performance using this [NYC Open Data 500k row CSV file](https://data.cityofnewyork.us/City-Government/Case-Related-Information-About-Civil-Litigation/pjgc-h7uv/about_data), which loads fine but takes ~22 seconds on my computer to parse:
Looking into the profile analysis shows a lot of long calls _out_ from WASM into JS to call `strptime`, which Perspective uses for anything _not_ [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) formatted date or datetime strings. In Emscripten, [`strptime` is implemented as a JavaScript foreign call](https://github.com/emscripten-core/emscripten/blob/b94d6e6ced33576a1ad96c7f6e701788c6f49211/src/library_time.js#L2 …
> Better `datetime`/`date` string parsing performance

- cpp/perspective/src/cpp/arrow_loader.cpp
- packages/perspective-viewer-datagrid/src/js/data_listener/formatter_cache.js
- pnpm-lock.yaml
- rust/perspective-js/package.json
- rust/perspective-js/src/ts/perspective.browser.ts
- rust/perspective-js/src/ts/wasm/emscripten_api.ts
- rust/perspective-js/test/js/constructors/arrow.spec.ts
Fixes #2894, an issue with `perspective-viewer-datagrid`'s formatting. Though internally Perspective `date` columns have no timezone offset, we use JavaScript `Date` types to format these values to the locale/ui settings, which by default will format to string in local time, causing `date` columns to appear off-by-one in this plugin.
Added a test based on the [repro](https://github.com/jdangerx/repro-perspective-float-filter/tree/dates) provided, which asserts (_sans UI_) that Perspective's engine encodes and decodes `date` columns types transitively.
> Fix `date` formatting for `perspective-viewer-datagrid` plugin

- cpp/perspective/src/cpp/arrow_loader.cpp
- cpp/perspective/src/cpp/server.cpp
- cpp/perspective/src/cpp/table.cpp
- cpp/perspective/src/include/perspective/arrow_loader.h
- cpp/perspective/src/include/perspective/server.h
- cpp/perspective/src/include/perspective/table.h
This fixes a couple of places where we're overallocating.
1. Reserve vocabs while loading arrows into perspective to prevent overgrowth.
2. Free data tables and protobuf messages before processing the table to minimize the concurrent copies of the data in memory.
> Fix overallocations

- .github/actions/install-deps/action.yaml
- .github/workflows/build.yaml
- cmake/modules/FindInstallDependency.cmake
- cpp/perspective/CMakeLists.txt
- package.json
- rust/perspective-python/pyodide-tests/README.md
- rust/perspective-python/pyodide-tests/tests/test_smoke.py
- rust/perspective-python/requirements-pyodide.txt
- rust/perspective-python/test.mjs
- tools/perspective-scripts/setup.mjs
- Switch to using global `CMAKE_CXX_FLAGS` to ensure every target we
need to link, including all Arrow components, is built with Emscripten
exceptions support.  The build already does the same thing for wasm
exceptions so it's at least more consistent now.
- Add two regression tests to the pytest-pyodide suite for pyarrow and
pandas examples, which were previously crashing due to inconsistent
Emscripten exceptions support between the object files
Also includes:
- small devex fix for the setup script when using Pyodide
- splits CI job for Pyodide wheel into build/test, uploads the artifact even when test suite fails
-   [ ] Description contains a link to the Github Issue, and any relevent …
> Support for pyodide 0.27.1, including pyarrow + pandas

- cpp/perspective/CMakeLists.txt
- cpp/perspective/src/cpp/binding_api.cpp
- cpp/perspective/src/cpp/heap_instruments.cpp
- cpp/perspective/src/include/perspective/heap_instruments.h
- rust/perspective-js/src/ts/wasm/emscripten_api.ts
Conditionally compile in heap instrumentation to find allocation hotspots.
> Heap Profiling Tooling

- packages/perspective-viewer-datagrid/package.json
- pnpm-lock.yaml
- rust/perspective-viewer/src/rust/components/column_selector/inactive_column.rs
- rust/perspective-viewer/src/rust/components/viewer.rs
- rust/perspective-viewer/src/rust/model/update_and_render.rs
This PR fixes an issue with `perspective-viewer-datagrid` which caused scroll position to drift when the component dimensions change.
> Fix datagrid scroll drift on resize

- cpp/perspective/src/cpp/arrow_loader.cpp
- rust/perspective-python/perspective/tests/table/test_to_polars.py
- rust/perspective-python/src/client/polars.rs
- rust/perspective-python/src/server/server_sync.rs
- rust/perspective-server/src/local_client.rs
This PR fixes the Python `View::to_polars` function to work and adds a test.
While attempting to implement transitive testing (perspective -> polars -> perspective), I realized [Polars stores dictionary columns in the uncommon `LargeUTF8` dictionary format](https://github.com/pola-rs/polars/issues/320), which caused segfaults in our u32-indexed dictionary reading code. As a result, this PR also adds support for Arrow/PyArrow`LargeUTF8` dictionary columns.
> Fix `View::to_polars` and add `LargeUTF8` Arrow dictionary support

- packages/perspective-viewer-d3fc/src/ts/legend/filter.ts
- packages/perspective-viewer-d3fc/test/js/axisLabel.spec.ts
This PR addresses issue #2566. When the data is grouped and a date is part of the grouped data, the date values are then represented in epoch format. I couldn't figure out the exact source of the problem, and this solution addresses the problem. I included a function in the filter.ts file since all the plugins affected by this issue import the functions in filter.ts. I refine the date type values before the functions in filter.ts run. The tests included confirm this solution too.
-   [x] Description contains a link to the Github Issue, and any relevent
-   [x] Include new tests that fail without this PR but passes with it.
-   [ ] Include any relevent Documentation changes related to …
> Show appropriate date when date is part of grouped data on chart.

- docs/md/SUMMARY.md
- docs/md/how_to/javascript/custom_worker.md
- examples/blocks/src/editable/README.md
- examples/blocks/src/editable/index.html
- rust/perspective-js/src/ts/perspective.browser.ts
- rust/perspective-js/src/ts/wasm/browser.ts
- rust/perspective-js/src/ts/wasm/engine.ts
- rust/perspective-js/test/html/service_worker.html
- rust/perspective-js/test/html/shared_worker.html
- rust/perspective-js/test/html/worker.html
- rust/perspective-js/test/js/workers.spec.js
This PR adds support for `SharedWorker` and `ServiceWorker` architectures to `@finos/perspective`'s web worker runtime, as well as overriding the default dedicated `Worker` instance.
```javascript
// Dedicated Worker
const worker = await perspective.worker(new Worker(url));
// SharedWorker
const worker = await perspective.worker(new SharedWorker(url));
// ServiceWorker
const registration = await navigator.serviceWorker.register(url, {
scope: "", // Your scope here
});
const worker = await perspective.worker(registration.active);
```
The `editable` example has been updated to use a `SharedWorker`, which means opening this example in multiple browser tabs will use the same `Table` state and receive eachother's updates.
https://github.com/user-attachments/assets/9b38c209-95c9-4e43-8950-ed7d70 …
> Add dedicated `Worker`, `SharedWorker` and `ServiceWorker` support

- rust/perspective-python/Cargo.toml
- rust/perspective-python/perspective/tests/async/test_websocket_client.py
- rust/perspective-python/perspective/tests/multi_threaded/test_multi_threaded.py
- rust/perspective-python/src/client/client_async.rs
- rust/perspective-python/src/server/server_sync.rs
This PR fixes a regression in `3.4.0` which causes a panic during the `View.on_update` notification of a non-synchronous `Client`. I've updated the multi threading test to assert single and concurrent thread updates (the old tests dispatched `on_update` notifications to an already-closed event loop that drops errors ...), and I've added a local-loopback websocket client test which replicates the bug in `3.4.0` and passes in this PR.
> Fix segfault in Python webservers

- .github/workflows/build.yaml
- packages/perspective-jupyterlab/src/js/view.js
- rust/perspective-python/requirements.txt
- rust/perspective-python/test.mjs
We had a pytest which deadlocked in the CI sdist tests. Exception spew from errors which
caused the deadlock was also somehow being swallowed and didn't make it to the log
output in Github Actions.
Add a timeout with pytest-timeout when running the non-pyodide pytest suite, including
for the CI sdist tests. When a test deadlocks, the timeout will fire and pytest-timeout then
prints the deadlocked test's output.
This is a run on a test tag, which shows the error output which was previously being lost in CI:
https://github.com/tomjakubowski/perspective/actions/runs/13820587424/job/38668499105
> Add timeouts to pytest, fix jupyterlab error

- rust/perspective-viewer/test/html/superstore-single-threaded.html
- rust/perspective-viewer/test/js/export_table.spec.ts
- tools/perspective-esbuild-plugin/worker.js
- tools/perspective-test/load-viewer-csv-single-threaded.js
- tools/perspective-test/src/js/start_test_server.ts
This PR fixes `<perspective-viewer>`'s export functionality with the `html` format, which was regressed by #2936. A test has also been added for single-threaded mode.
Export-to-html requires single-threaded engine mode for the WebAssembly runtime, due to the security context of the `file://` protocol which prevents features e.g. Web Workers. This mode _should not_ be relied on otherwise due to the performance impact, as the lack of a concurrent worker means engine processing locks the UI. Ergo, running in this mode yields an obnoxious console warning.
> Fix export-to-html in `perspective-viewer`

- .github/workflows/build.yaml
- cpp/perspective/build.js
- cpp/perspective/src/cpp/base.cpp
- cpp/perspective/src/cpp/binding_api.cpp
- cpp/perspective/src/cpp/context_zero.cpp
- cpp/perspective/src/cpp/data_table.cpp
- cpp/perspective/src/cpp/flat_traversal.cpp
- cpp/perspective/src/cpp/gnode.cpp
- cpp/perspective/src/cpp/gnode_state.cpp
- cpp/perspective/src/cpp/server.cpp
- cpp/perspective/src/cpp/table.cpp
- cpp/perspective/src/include/perspective/base.h
- cpp/perspective/src/include/perspective/data_table.h
- cpp/perspective/src/include/perspective/flat_traversal.h
- cpp/perspective/src/include/perspective/gnode.h
- cpp/perspective/src/include/perspective/gnode_state.h
- cpp/perspective/src/include/perspective/parallel_for.h
- cpp/perspective/src/include/perspective/scalar.h
- rust/perspective-js/test/js/constructors.spec.js
- rust/perspective-js/test/js/expressions/multiple_views.spec.js
- rust/perspective-js/test/js/limit.spec.js
- rust/perspective-js/test/js/updates.spec.js
- rust/perspective-python/perspective/tests/table/test_table_limit.py
- rust/perspective-server/build/psp.rs
- tools/perspective-bench/cross_platform_suite.mjs
This PR decouples primary keys from the limit functionality of perspective tables, allowing us to handle aggregates like "last by index" a bit better when users have a limit and want to rely on insert order to window their data.
Along the way I also fixed some memory safety issues where we had called `new` to allocate some memory and free'd it with `free` rather than `delete`. This wasn't breaking anything at the moment, but may have been relying on undefined behavior accidentally.
The new benchmarks also triggered a bug in our polling implementation where if a table was dirtied and deleted before the `poll` call, it would segfault the poll call because we hadn't removed it from the dirty map in the server, so I fixed that as well.
> Update `limit` behavior to use incrementing `index` (fix `last_by_index` aggregate)

- packages/perspective-viewer-datagrid/src/js/custom_elements/datagrid.js
- packages/perspective-viewer-datagrid/src/js/data_listener/format_cell.js
- packages/perspective-viewer-datagrid/src/js/event_handlers/click.js
- packages/perspective-viewer-datagrid/src/js/event_handlers/select_region.js
- packages/perspective-viewer-datagrid/src/js/model/create.js
- packages/perspective-viewer-datagrid/src/js/model/toolbar.js
- rust/perspective-client/src/rust/client.rs
- rust/perspective-client/src/rust/config/view_config.rs
- rust/perspective-client/src/rust/session.rs
- rust/perspective-client/src/rust/utils/clone.rs
- rust/perspective-client/src/rust/view.rs
- rust/perspective-js/src/rust/client.rs
- rust/perspective-js/src/rust/utils/console_logger.rs
- rust/perspective-js/src/rust/utils/futures.rs
- rust/perspective-python/src/client/client_async.rs
- rust/perspective-viewer/src/rust/components/copy_dropdown.rs
- rust/perspective-viewer/src/rust/components/export_dropdown.rs
- rust/perspective-viewer/src/rust/components/viewer.rs
- rust/perspective-viewer/src/rust/custom_elements/copy_dropdown.rs
- rust/perspective-viewer/src/rust/custom_elements/export_dropdown.rs
- rust/perspective-viewer/src/rust/custom_elements/viewer.rs
- rust/perspective-viewer/src/rust/lib.rs
- rust/perspective-viewer/src/rust/model/copy_export.rs
- rust/perspective-viewer/src/rust/model/export_method.rs
- rust/perspective-viewer/src/rust/model/get_viewer_config.rs
- rust/perspective-viewer/src/rust/renderer.rs
- rust/perspective-viewer/src/rust/session.rs
Thsi PR adds a export support for `perspective-viewer-datagrid`, which allows the datagrid contents to be serialized to clipboard or download in the HTML rendered format provided by the plugin itself (rather than the engine). This method was already implemented for charts (which export png).
Additionally, the signature of the `PerspectiveViewer::copy` has been changed to accept a `String` as an argument, signifying the desired export method (previous `bool` to choose between `"csv"` and `"csv-all"` methods).
> Add API for keyboard copy from `perspective-viewer-datagrid`

- .github/workflows/build.yaml
- rust/perspective-js/src/rust/utils/console_logger.rs
- rust/perspective-js/src/ts/wasm/browser.ts
- rust/perspective-js/test/js/workers.spec.js
- tools/perspective-bench/cross_platform_suite.mjs
#2936 added support for `SharedWorker` and `ServiceWorker`, in theory without introducing any dependence on these APIs (as for these runtime modes, the worker is constructed externally and passed in as an argument). However, in practice a single `instanceof` check within this initialization is a runtime "Missing Symbol" error in _some_ browsers which lack this API entirely. This PR fixes this issue and adds a test which deletes the `ServiceWorker` and `SharedWorker` symbols from Chrome before initializing the engine.
It should be noted that Perspective _only supports the browsers we run CI tests for_, which it currently only Desktop Chrome and Node.js. As a general rule, we also don't accept PRs for fixes to unsupported browsers as they are virtually impossible to maintain beyond a few …
> Fix support for browsers lacking the `SharedWorker` API

- package.json
- packages/perspective-jupyterlab/DEVELOPMENT.md
- packages/perspective-jupyterlab/README.md
- packages/perspective-jupyterlab/build.mjs
- packages/perspective-jupyterlab/src/js/view.js
- packages/perspective-jupyterlab/test/jupyter/widget.spec.mts
- pnpm-lock.yaml
- rust/perspective-client/src/rust/client.rs
- rust/perspective-client/src/rust/session.rs
- rust/perspective-js/package.json
- rust/perspective-python/perspective/tests/server/test_session.py
- rust/perspective-python/perspective/widget/__init__.py
- rust/perspective-python/perspective/widget/viewer/viewer.py
- rust/perspective-python/src/client/client_sync.rs
- rust/perspective-python/src/client/mod.rs
- rust/perspective-python/src/client/proxy_session.rs
- rust/perspective-python/src/lib.rs
- rust/perspective-python/test.mjs
- tools/perspective-scripts/sh.mjs
- tools/perspective-scripts/test_js.mjs
- tools/perspective-test/playwright.config.ts
AsyncTable support for PerspectiveWidget
When a `PerspectiveWidget()` is constructed with an `AsyncTable` data
argument, its interface becomes async and methods which operate on the
table return coroutines.
- Add async version of ProxySession.handle_request() with unit test
- Reënable perspective-client unit tests
- New jupyter playwright tests for widget + AsyncTable
> AsyncTable support in widget

- .vscode/settings.default.json
- rust/perspective-viewer/README.md
These settings ensure the correct formatting (as per `pnpm run lint`) is applied when vscode formats a Javascript, Typescript, TSX, Markdown, LESS, HTML, or JSON file.
> Add vscode settings to enable prettier

- cpp/perspective/src/cpp/arrow_loader.cpp
- cpp/perspective/src/cpp/base.cpp
- cpp/perspective/src/cpp/binding_api.cpp
- cpp/perspective/src/cpp/context_zero.cpp
- cpp/perspective/src/cpp/data_table.cpp
- cpp/perspective/src/cpp/flat_traversal.cpp
- cpp/perspective/src/cpp/gnode.cpp
- cpp/perspective/src/cpp/gnode_state.cpp
- cpp/perspective/src/cpp/server.cpp
- cpp/perspective/src/cpp/table.cpp
- cpp/perspective/src/include/perspective/arrow_loader.h
- cpp/perspective/src/include/perspective/base.h
- cpp/perspective/src/include/perspective/data_table.h
- cpp/perspective/src/include/perspective/flat_traversal.h
- cpp/perspective/src/include/perspective/gnode.h
- cpp/perspective/src/include/perspective/gnode_state.h
- cpp/perspective/src/include/perspective/scalar.h
- cpp/perspective/src/include/perspective/server.h
- rust/perspective-js/src/ts/wasm/engine.ts
- rust/perspective-js/test/js/updates.spec.js
- rust/perspective-python/perspective/tests/table/test_table_limit.py
- rust/perspective-server/src/ffi.rs
- rust/perspective-server/src/local_session.rs
This PR addresses a resource leak introduced in #2964, which causes unbound resource growth (recoverable) in the processing of a `View` with some `group_by` and `split_by` configs attached to a `Table` with a `limit`, causing increased memory usage, over-time performance degradation of streaming `View` data, as well as data accumulation errors with a `limit` and `split_by` (but no `group_by`).
#2964 sought to address a primary key implicit ordering feature by tracking the limit property and allocation impact within the engine itself, where previously we'd simply applied `id % limit` to the auto-incrementing primary key generator. However, the implementation failed to account for bounded tracking of these values over time, leading to some cases which never reclaimed primary keys (just the …
> Fix `limit` overflow bug

- .github/actions/config/action.yaml
- .github/workflows/build.yaml
This modifies the CI to build production releases on the `master` branch whenever a PR is merged. Previously, the same _dev_ CI workflow was run on `master` branch merges, and only release tags built the full production workflow, which includes MacOS & Windows python wheels and benchmarks among other tweaks.
As a result, we'll now have apples-to-apples intermediate builds between releases, which will halpe keep regressions out of released perspective wheels/crates/packages.
> Nightly artifacts

- .cargo/config.toml
- Cargo.lock
- pnpm-lock.yaml
- rust/perspective-client/Cargo.toml
- rust/perspective-client/src/rust/client.rs
- rust/perspective-client/src/rust/utils/mod.rs
- rust/perspective-js/Cargo.toml
- rust/perspective-js/src/rust/utils/browser.rs
- rust/perspective-python/perspective/tests/server/test_session.py
- rust/perspective-python/src/client/proxy_session.rs
- rust/perspective-viewer/Cargo.toml
- rust/perspective-viewer/src/rust/components/form/debug.rs
- rust/perspective-viewer/src/rust/custom_events.rs
- rust/perspective-viewer/src/rust/utils/browser/blob.rs
- tools/perspective-bench/package.json
This PR fixes an issue which caused `Client` instances bound to a `ProxySession` to mis-route some messages due to re-used Message IDs. `ProxySession` is used by the `PerspectiveWidget` Jupyter widget to share a connection for both the Widget and local `Client`, and it relies on `msg_id` field to discriminate transport messages to each. These are now seeded randomly instead of starting at 0. The fix applied may still rarely have conflicts - but they would require a few unlikely conditions to occur in sequence, and eliminating conflicts completely would be quite a bit more difficult to implement.
A test is included based on the issue reported in https://github.com/tomjakubowski/perspective/tree/bug/session
> Fix `ProxySession` message routing bug with Jupyter widget

- .github/actions/install-deps/action.yaml
- .github/workflows/build.yaml
- README.md
- package.json
- pnpm-lock.yaml
- tools/perspective-scripts/lint_headers.mjs
- tools/perspective-scripts/publish.mjs
- tools/perspective-scripts/version.mjs
- tools/perspective-scripts/workspace.mjs
This PR modifies the project's CI workflow to template `package.json`, `pyproject.toml` and `Cargo.toml` metadata files with a timestamped version of the latest commit, e.g. `3.6.1-dev123123123` for nightly builds. There is no impact to the published artifacts nor the workflow for tag/release/dev builds.
> Nightly versions

- Cargo.lock
- packages/perspective-workspace/test/js/table.spec.js
- rust/perspective-client/src/rust/client.rs
- rust/perspective-client/src/rust/utils/mod.rs
- rust/perspective-js/Cargo.toml
- rust/perspective-js/src/rust/client.rs
- rust/perspective-js/src/rust/table_data.rs
- rust/perspective-js/src/rust/utils/errors.rs
- rust/perspective-js/src/rust/utils/futures.rs
- rust/perspective-js/src/rust/utils/local_poll_loop.rs
- rust/perspective-viewer/Cargo.toml
- rust/perspective-viewer/src/less/status-bar.less
- rust/perspective-viewer/src/rust/components/column_selector/inactive_column.rs
- rust/perspective-viewer/src/rust/components/error_message.rs
- rust/perspective-viewer/src/rust/components/plugin_selector.rs
- rust/perspective-viewer/src/rust/components/status_bar.rs
- rust/perspective-viewer/src/rust/components/status_indicator.rs
- rust/perspective-viewer/src/rust/components/viewer.rs
- rust/perspective-viewer/src/rust/custom_elements/viewer.rs
- rust/perspective-viewer/src/rust/model/restore_and_render.rs
- rust/perspective-viewer/src/rust/model/update_and_render.rs
- rust/perspective-viewer/src/rust/session.rs
- rust/perspective-viewer/src/rust/session/metadata.rs
- rust/perspective-viewer/test/js/settings.spec.js
This PR adds a new UX for capturing the error details on hover over the error status icon. Additionally, the `perspective_js::ApiError` error type has been upgraded to `thiserror` derived version, in order to support the new UX features:
* Instances of duplicated stack trace inlining have been removed.
* `String -> Rich error type -> String -> Rich error type -> ...` conversions flattened to use `ApiError` everywhere.
* Better stacktraces (in debug builds), better error messages with categories overall. 
* UI is no longer borked nor does it auto-reset (though dismissing the dialog will reset the viewer).
* Rust API has changed to take `ClientError`/`ApiError` for `Client::on_error` callbacks, which is an API breaking change (though this type implements `Display` also).
> New error UX

- rust/perspective-client/build.rs
This PR fixes Windows CI for Github Actions runners, which seem to have changed their disk layouts somewhat.
> Fix Windows CI

- rust/perspective-viewer/src/rust/custom_elements/viewer.rs
- rust/perspective-viewer/src/rust/utils/browser/mod.rs
- rust/perspective-viewer/test/html/superstore_with_input.html
- rust/perspective-viewer/test/js/focus.spec.js
This PR fixes a small bug which causes Perspective to steal focus via `document.activeElement.blur()` when DOM-reconstructing API methods are called, like `perspective_viewer::restore`. This was done intentionally to make sure that modal windows and dropdowns rooted in the UI are dismissed before their parent widgets are removed, but this behavior is no longer necessary for this case. A test has also been added to assert focus is not stolen.
> Fix `perspective_viewer::restore` calls blurring

- cpp/perspective/src/cpp/view.cpp
- rust/perspective-python/perspective/tests/multi_threaded/test_multi_threaded.py
This PR fixes a missing lock in `perspective_client::View::to_arrow` and `perspective_client::View::to_csv` methods, which impacted data consistency in multithreaded contexts. A test has been added which repros the issue _most of the time_ without the applied fix.
This regression introduced in #2991, which has not been released in a version yet, so there is release impact.
> Fix `to_arrow` thread safety

- rust/perspective-client/src/rust/config/expressions.rs
I noticed while reading the expressions docs that `replace_all` was mistyped as `replace`.
https://docs.rs/perspective-client/latest/perspective_client/config/expressions/index.html#perspective-exprtk-extensions
This PR fixes that. I also added a pretty basic unit test which confirms that `insert_text`
starts with `label` for all of the `COMPLETIONS`.
> Fix typo in docs for replace_all

- Cargo.lock
- docs/md/SUMMARY.md
- examples/rust-axum/Cargo.toml
- rust/perspective-client/Cargo.toml
- rust/perspective-client/src/rust/client.rs
- rust/perspective-client/src/rust/table.rs
- rust/perspective-client/src/rust/utils/mod.rs
- rust/perspective-viewer/Cargo.toml
- rust/perspective/Cargo.toml
- rust/perspective/src/axum.rs
This PR fixes a rust dependency duplication on the `rand` crate which made downstream consumption unpleasant, as well as a few build script and env fixes encountered during the release process for `3.7.0`.
> Fix dep version conflict with `rand`

- packages/perspective-viewer-datagrid/src/js/event_handlers/header_click.js
- packages/perspective-viewer-datagrid/test/js/superstore.spec.js
- tools/perspective-test/src/js/utils.ts
This PR fixes a regression in datagrid editing introduced in #3014 and adds regression tests. While tests already existed for this case, the tests used DOM manipulation to simulate user interaction with the editable content, which bypassed the regression. The new tests instead use `playwright`'s automation APIs.
> Fix datagrid editing and add tests

- cpp/perspective/src/cpp/computed_expression.cpp
- cpp/perspective/src/cpp/computed_function.cpp
- cpp/perspective/src/cpp/server.cpp
- cpp/perspective/src/cpp/table.cpp
- cpp/perspective/src/include/perspective/computed_expression.h
- cpp/perspective/src/include/perspective/server.h
- cpp/perspective/src/include/perspective/table.h
- rust/perspective-python/perspective/tests/multi_threaded/test_multi_threaded.py
This PR fixes a memory corruption issue which can be encountered in `perspective-python` or `perspective-rs` when:
1. Multiple `Server` instances exist in the same process, and
2. Both instances have `View` instances with `expressions` fields, and
3. `View` methods on each are called from separate threads concurrently
This has technically been an issue since Perspective  `v3.0`, but only because before this version, #1 in this list was not possible as there was no public API for instancing multiple Servers.
> Fix thread safety of multiple `Server` instances in the same process

- cpp/perspective/src/cpp/computed_function.cpp
- docs/md/explanation/architecture/client_server.md
- docs/md/explanation/architecture/server_only.md
- rust/perspective-js/test/js/expressions/numeric.spec.js
- rust/perspective-js/test/js/leaks.spec.js
This PR modifies the behavior of the `null` literal in ExprTK expressions to preserve `null` when being cast e.g. `float(null)`, which is required to satisfy the type checker for e.g. branching. A test has been added for this case - I don't think this can be called a regression since it's always been the case, but it is at least a bug.
> Fix `null` handling for cast ExprTK functions

- docs/docusaurus.config.js
- docs/md/how_to/python/multithreading.md
- examples/python-tornado-streaming/server.py
- rust/perspective-python/src/server/server_sync.rs
- rust/perspective-server/src/server.rs
* Remove `/blog` link from Perspective OSS docs site
* Update docs on `on_poll_request` kwarg for `Server` constructor.
> Remove blog links

- Cargo.lock
- packages/perspective-viewer-datagrid/src/js/custom_elements/datagrid.js
- packages/perspective-viewer-datagrid/src/js/data_listener/index.js
- rust/generate-metadata/main.rs
- rust/perspective-client/Cargo.toml
- rust/perspective-client/perspective.proto
- rust/perspective-client/src/rust/client.rs
- rust/perspective-client/src/rust/lib.rs
- rust/perspective-client/src/rust/view.rs
- rust/perspective-js/build.js
- rust/perspective-js/src/rust/client.rs
- rust/perspective-js/src/rust/lib.rs
- rust/perspective-js/src/rust/utils/serde.rs
- rust/perspective-js/src/rust/view.rs
- rust/perspective-js/src/ts/wasm/engine.ts
- rust/perspective-js/test/js/aggregates.spec.js
- rust/perspective-js/test/js/expressions/functionality.spec.js
- rust/perspective-js/test/js/group_by.spec.js
- rust/perspective-js/test/js/sort.spec.js
- rust/perspective-python/perspective/tests/table/test_column_paths.py
- rust/perspective-python/perspective/tests/table/test_view.py
- rust/perspective-python/src/client/client_async.rs
- rust/perspective-python/src/client/client_sync.rs
- rust/perspective-server/cpp/perspective/src/cpp/server.cpp
- rust/perspective-server/cpp/perspective/src/cpp/view.cpp
- rust/perspective-server/cpp/perspective/src/include/perspective/server.h
- rust/perspective-server/cpp/perspective/src/include/perspective/view.h
- rust/perspective-viewer/src/rust/lib.rs
This PR fixes `perspective-viewer-datagrid` to handle `split_by` columns which change due to a `Table::update` call which introduces a new value (or removes all instances of an existing one).
In order to implement this fix without requiring the datagrid to fetch _all_ column names for each tick, two breaking API changes are introduced as well:
* `View::column_paths` now takes optional `ColumnWindow` `start_col` and `end_col` bounds.
* `View::column_paths` now no longer returns `__ROW_PATH__` as an output column when a `group_by` is applied (though this column is still in the output data).
https://github.com/user-attachments/assets/32a9e140-29f2-4966-9a68-020c708a7cdb
> Update column paths when the colun set changes in `perspective-viewer-datagrid`

- rust/perspective-client/src/rust/config/aggregates.rs
- rust/perspective-js/test/js/view_config.spec.js
- rust/perspective-server/cmake/modules/SetupClangd.cmake
- rust/perspective-server/cpp/perspective/src/cpp/aggspec.cpp
- rust/perspective-server/cpp/perspective/src/cpp/server.cpp
This PR fixes the `View::get_config` method, which has been neglecting to output the `aggregates` field correctly since version`3.0`. This bug _only_ affected this specific method - e.g., `HTMLPerspectiveVIewerElement::save` does not show similar issues, which is why this bug went undetected for so long.
Also: tests.
> Fix `aggregates` field in `View::get_config`
