- packages/perspective/src/cpp/main.cpp
- packages/perspective/test/js/constructors.js
Adding utf16<->utf8 conversion for tabular data.
> Fixes #14: Fixing issue with encoding, data only

- packages/perspective-jupyterlab/src/ts/index.ts
- needs to be `application/psp+json`
- making attributes start with _
> change mime renderer type to not interfere with saving notebook

- packages/perspective-jupyterlab/package.json
- packages/perspective-jupyterlab/src/ts/index.ts
- packages/perspective-utils/README.md
- packages/perspective-utils/package.json
- packages/perspective-utils/src/ts/index.ts
- packages/perspective-utils/tsconfig.json
- 3 helper classes to stream data from various endpoint types
- changes to the jupyterlab plugin to support these
Please review and suggest changes @texodus @nmichaud
> Adding utility classes to allow direct web socket/socketio/http connections to perspective in jupyterlab

- packages/perspective-viewer/src/js/view.js
- packages/perspective/src/js/perspective.js
- packages/perspective/src/js/perspective.parallel.js
Generally improved error handling and reporting, as well.
> Added table and view deletion callbacks

- packages/perspective-viewer-hypergrid/src/js/hypergrid.js
> Properly handle case when there is no data

- README.md
Adding instructions on Windows 10 installation of Perspective and its prerequisites.
> Windows 10 installation instructions

- packages/perspective-jupyterlab/src/ts/index.ts
This lets you provide a schema for more diverse data sources. 
Goes along with:
https://github.com/timkpaine/perspective-python/issues/12
> Support for initializing with schema

- .gitignore
- packages/perspective-viewer-highcharts/src/js/highcharts.js
- packages/perspective-viewer-highcharts/test/results/results.json
Reversed direction of legends on charts with a ColorAxis, such that larger numbers are on top.
> Fixed heatmap legend direction

- packages/perspective/test/js/constructors.js
> Added tests to verify deletions cause no errors

- packages/perspective-viewer/src/js/utils.js
Adding template polyfill for browsers that do not support the template tag
> Adding template polyfill for browsers that do not support the template tag

- .travis.yml
- README.md
- docker/emsdk/Dockerfile
- docker/puppeteer/Dockerfile
- package.json
- packages/perspective-examples/package.json
- packages/perspective-jupyterlab/package.json
- packages/perspective-viewer-highcharts/package.json
- packages/perspective-viewer-hypergrid/package.json
- packages/perspective-viewer/package.json
- packages/perspective-viewer/src/less/material.less
- packages/perspective/CMakeLists.txt
- packages/perspective/package.json
- packages/perspective/src/js/perspective.asmjs.js
- packages/perspective/src/js/perspective.js
- packages/perspective/test/js/perspective.spec.js
An "officially" supported docker emscripten container by default, for cases like #40
> Add `emscripten` docker container

- package.json
- packages/perspective-examples/src/html/theme-material-dark.html
- packages/perspective-viewer/src/js/view.js
- packages/perspective-viewer/src/less/default.less
- packages/perspective-viewer/src/less/material.less
- packages/perspective-viewer/src/less/row.less
- packages/perspective-viewer/src/less/view.less
- packages/perspective/package.json
- packages/perspective/src/config/common.config.js
Various fixes from the 0.1.17 release
> Release fixes

- packages/perspective/.npmignore
- Skip publishing the cpp source code for perspective.
- Slightly improve the logging and build time for perspective core module
> Forgo publishing cpp source code

- packages/perspective-viewer-highcharts/src/js/config.js
- packages/perspective-viewer-highcharts/src/js/tooltip.js
- packages/perspective-viewer/src/less/default.less
- packages/perspective-viewer/src/less/material.dark.less
- packages/perspective-viewer/src/less/material.less
General Highcharts tooltip fixes, as well as fixes for the Material theme
> Material tooltip

- packages/perspective-jupyterlab/src/ts/index.ts
- packages/perspective-viewer-hypergrid/src/js/hypergrid.js
- packages/perspective-viewer/src/less/material.dark.less
> fix for #160

- packages/perspective-viewer/package.json
- packages/perspective/src/config/common.config.js
Fixed [installation issue](https://github.com/axa-ch/patterns-library/issues/505)
> Updated webcomponentsjs

- packages/perspective-jupyterlab/README.md
- packages/perspective-jupyterlab/example.ipynb
> Elaborated Jupyterlab plugin documentation, added example notebook

- packages/perspective-viewer-hypergrid/src/js/PerspectiveDataModel.js
- packages/perspective-viewer-hypergrid/src/js/hypergrid.js
- packages/perspective-viewer-hypergrid/src/js/psp-to-hypergrid.js
- packages/perspective-viewer/src/js/view.js
- packages/perspective/src/config/perspective.node.config.js
- packages/perspective/src/js/api.js
- packages/perspective/src/js/perspective.js
- packages/perspective/src/js/perspective.node.js
- packages/perspective/src/js/view_formatters.js
- packages/perspective/test/config/test_node.config.js
- packages/perspective/test/js/constructors.js
Converted Hypergrid plugin to column-oriented API to reduce message size on wire, and replaced frame drop with lag for rendering.
> Remote performance

- package.json
- packages/perspective/package.json
PSP_CPU_COUNT controls the # of CPUs which should be utilized during compilation.  Refactor of work originally done in #218
> Added PSP_CPU_COUNT env var

- packages/perspective-jupyterlab/src/ts/utils.ts
- packages/perspective-jupyterlab/src/ts/widget.ts
Works with timkpaine/perspective-python#32
> Added Jupyter API for incremental updates

- packages/perspective-viewer-hypergrid/src/js/PerspectiveDataModel.js
- packages/perspective-viewer-hypergrid/src/js/hypergrid.js
- packages/perspective-viewer-hypergrid/test/js/superstore.spec.js
- packages/perspective-viewer-hypergrid/test/results/results.json
- packages/perspective-viewer/src/js/computed_column.js
- packages/perspective-viewer/src/js/view.js
- packages/perspective-viewer/test/js/computed_column_tests.js
- packages/perspective-viewer/test/results/results.json
- packages/perspective/test/js/updates.js
Added `computed-columns` property to `<perspective-viewer>` component.
> Computed persistence

- docs/perspective-viewer.md
- packages/perspective-viewer/README.md
- packages/perspective/src/include/perspective/filter.h
- packages/perspective/src/include/perspective/gnode.h
- packages/perspective/test/js/pivots.js
Fix bug reported by @nmichaud where there was an issue with updates specifying the pkey column where value for agg column is missing. Added a test for this as well.
> Fix bug with pkey column update with missing agg value

- packages/perspective-viewer-highcharts/src/js/config.js
- packages/perspective-viewer-highcharts/src/js/tooltip.js
- packages/perspective-viewer-hypergrid/src/js/hypergrid.js
- packages/perspective-viewer-hypergrid/src/js/perspective-plugin.js
- packages/perspective-viewer/src/js/computed_column.js
- packages/perspective-viewer/src/js/row.js
- packages/perspective-viewer/src/js/view.js
- packages/perspective-viewer/src/less/computed_column.less
- packages/perspective-viewer/src/less/default.less
- packages/perspective-viewer/src/less/material.less
- packages/perspective-viewer/src/less/row.less
- packages/perspective-viewer/test/js/computed_column_tests.js
- packages/perspective/src/cpp/main.cpp
- packages/perspective/src/js/date_parser.js
- packages/perspective/src/js/defaults.js
- packages/perspective/src/js/perspective.js
- packages/perspective/test/js/constructors.js
Added support for proper `date` types as well as inferrence.  Fixes #262
> Date types

- packages/perspective/src/cpp/context_one.cpp
- packages/perspective/src/cpp/main.cpp
- packages/perspective/src/js/perspective.js
Also fix a slight memory leak.
> Cleanup cpp api

- docs/perspective-viewer.md
- packages/perspective-viewer/README.md
- packages/perspective-viewer/src/js/view.js
Wrap `__WORKER__` in an IIFE and return `getInstance()` into scope in order to implement singleton pattern.
> Refactor __WORKER__ into proper singleton

- packages/perspective-viewer-highcharts/src/js/highcharts.js
- packages/perspective-viewer-highcharts/test/html/render_warning.html
- packages/perspective-viewer-highcharts/test/js/bar.spec.js
- packages/perspective-viewer-highcharts/test/results/results.json
- packages/perspective-viewer/src/html/view.html
- packages/perspective-viewer/src/js/view.js
- packages/perspective-viewer/src/less/default.less
- packages/perspective-viewer/src/less/variables.less
- packages/perspective-viewer/test/js/utils.js
- Add render warnings
- Refactor `debounce_update` to use named parameters
- Test render warnings and consecutive updates
> Add warnings when data to be rendered will slow down browser

- packages/perspective-jupyterlab/package.json
- packages/perspective-jupyterlab/src/config/mimerenderer.config.js
- packages/perspective-jupyterlab/src/config/plugin.config.js
- packages/perspective-jupyterlab/src/less/material.less
- packages/perspective-jupyterlab/src/ts/arraybuffer.d.ts
- packages/perspective-jupyterlab/src/ts/index.ts
- packages/perspective-jupyterlab/src/ts/mimerenderer.ts
- packages/perspective-jupyterlab/src/ts/plugin.ts
- packages/perspective-jupyterlab/src/ts/utils.ts
- packages/perspective-jupyterlab/src/ts/version.ts
- packages/perspective-jupyterlab/src/ts/widget.ts
- Removing stale dependencies
- removing comm feature (no longer needed)
- adding computed columns
- adding embed hook, will require much more work so separating from this 
- bump copyright year
> Jupyterlab plugin: Cleanup and computed columns

- packages/perspective/test/js/pivots.js
- src/cpp/sparse_tree.cpp
Weighted mean aggregation calculation now correctly handles null/missing values
> Fix weighted mean null/missing value handling

- packages/perspective-viewer/src/js/row.js
- packages/perspective-viewer/src/js/viewer/action_element.js
- packages/perspective-viewer/src/js/viewer/dom_element.js
- packages/perspective-viewer/src/js/viewer/dragdrop.js
- packages/perspective-viewer/src/js/viewer/perspective_element.js
- packages/perspective-viewer/src/less/material.less
- packages/perspective-viewer/src/less/row.less
- packages/perspective-viewer/src/less/viewer.less
- packages/perspective/src/js/defaults.js
- packages/perspective/src/js/perspective.js
- packages/perspective/test/js/pivots.js
Implements a UX for column sorting on arbitrary columns.
> Full column sort

- packages/perspective/src/js/parse_data.js
- packages/perspective/test/js/constructors.js
- src/cpp/main.cpp
- Port `data_types` and `get_data_type`
- Remove vestigial code in DataParser
- Add test (skipped) for nasty edge case of upgrading int to float columns
> Port data_types and get_data_type

- package.json
- packages/perspective-viewer-highcharts/babel.config.js
- packages/perspective-viewer-hypergrid/babel.config.js
- packages/perspective-viewer/babel.config.js
- packages/perspective/babel.config.js
- yarn.lock
Improves build asset size ~10%
> Removed regenerator-plugin in favor of fast-async

- packages/perspective/package.json
> Add missing dependencies

- CMakeLists.txt
> fix mac ending

- CMakeLists.txt
- scripts/build_cpp.js
- scripts/build_python.js
- scripts/test.js
- scripts/test_cpp.js
- scripts/test_python.js
- src/cpp/aggspec.cpp
- src/cpp/compat_impl_osx.cpp
- src/cpp/context_grouped_pkey.cpp
- src/cpp/context_one.cpp
- src/cpp/context_two.cpp
- src/cpp/gnode.cpp
- src/cpp/gnode_state.cpp
- src/cpp/port.cpp
- src/cpp/raii_impl_osx.cpp
- src/cpp/schema_column.cpp
- src/cpp/sparse_tree.cpp
- src/cpp/storage.cpp
- src/cpp/storage_impl_osx.cpp
- src/cpp/table.cpp
- src/cpp/vocab.cpp
- src/include/perspective/aggspec.h
- src/include/perspective/base.h
- src/include/perspective/config.h
- src/include/perspective/port.h
- src/include/perspective/schema_column.h
- src/include/perspective/sparse_tree.h
- src/include/perspective/traversal.h
Rebased & fixed version of #380
> Re-enable cpp warnings

- packages/perspective/package.json
- packages/perspective/src/js/perspective.node.js
- packages/perspective/src/js/perspective.parallel.js
Added heartbeat detection function to websocket to solve the connection interruption of the client due to network or other reasons. When the client connection is disconnected, the invalid connection is cleared on the node side intime
> Websocket heartbeat detection

- README.md
My editor removed some extra whitespace and i updated the links to point to bl.ocks
> Point README links to blocks

- README.md
Adds another example with a few charts from [IEX cloud](https://iexcloud.io)
> add another IEX demo

- packages/perspective-viewer-hypergrid/test/js/superstore.spec.js
- packages/perspective-viewer-hypergrid/test/results/results.json
- packages/perspective-viewer/src/js/viewer.js
- packages/perspective-viewer/src/js/viewer/perspective_element.js
For awaiting side-effecting attribute changes
```javascript
elem.setAttribute("row-pivots", '["State"]');
elem.flush();
elem.view.set_depth(0);
elem.notifyResize();
```
> Added `flush()` method to `<perspective-viewer>`

- examples/webpack/index.js
- examples/webpack/index.less
- examples/webpack/output/public/index.html
- examples/webpack/package.json
- examples/webpack/webpack.config.js
- packages/perspective-webpack-plugin/index.js
Fixes `@jpmorganchase/perspective-webpack-plugin` to work correctly with embedding `style-loader`, etc., and updates the webpack example to reflect this change.
> Webpack fix

- packages/perspective-viewer-highcharts/src/js/config.js
- packages/perspective-viewer-hypergrid/src/js/perspective-plugin.js
Fixes 2 independent bugs in the click-events feature
> Click event fix

- packages/perspective-jupyterlab/package.json
> Fix for Juypterlab build->dist

- packages/perspective/src/js/DataAccessor/DataAccessor.js
- packages/perspective/src/js/perspective.js
- packages/perspective/test/js/updates.js
> Fixed calls to `update()` with empty list from throwing exception

- packages/perspective-viewer-hypergrid/package.json
- packages/perspective-viewer-hypergrid/src/js/hypergrid.js
- packages/perspective-viewer-hypergrid/src/js/perspective-plugin.js
- packages/perspective-viewer-hypergrid/test/js/superstore.spec.js
- packages/perspective-viewer-hypergrid/test/results/results.json
- yarn.lock
Adds sort indicators to the perspective-viewer-hypergrid headers.
> Header sort indicator

- packages/perspective-viewer/src/js/viewer/dragdrop.js
https://github.com/jpmorganchase/perspective/issues/438
> Ensure that filter column stays active when filtering

- packages/perspective-viewer-d3fc/src/js/plugin/plugin.js
> Fixed merge error in new plugin API access to `view.config`

- packages/perspective/src/js/api.js
> `on_update` fix

- packages/perspective-viewer/src/js/viewer.js
> Added save() and restore() methods to plugin API

- packages/perspective/bench/js/bench.js
- packages/perspective/bench/js/browser_runtime.js
Also, fixed regression in view config property names.
> Updated benchmarked versions 

- packages/perspective-viewer-highcharts/src/js/color_axis.js
- packages/perspective-viewer-highcharts/src/js/draw.js
- packages/perspective-viewer-highcharts/src/js/highcharts.js
- packages/perspective-viewer-hypergrid/src/js/hypergrid.js
- packages/perspective-viewer/src/js/viewer.js
- packages/perspective-viewer/src/js/viewer/perspective_element.js
Only implemented for hypergrid and highcharts (d3fc implementation coming soon)
> Add 'styleElement' method to tell perspective-viewer to restyle picking up css changes

- packages/perspective-viewer/src/config/themes.config.js
> Fix for webpack 4 themes generation error on Windows

- examples/remote/index.css
- examples/remote/index.html
- examples/remote/package.json
- examples/remote/server.js
- package.json
- packages/perspective-bench/src/html/benchmark.html
- packages/perspective/package.json
- packages/perspective/src/js/API/host.js
- packages/perspective/src/js/perspective.js
- packages/perspective/src/js/perspective.node.js
- packages/perspective/src/js/perspective.parallel.js
- yarn.lock
Fixes & improvements for #589 
* Added a Server/Client Perspective example using streaming Arrows.
* Fixed websocket server issue which caused multiple clients to generate the same msg ID sequence.
* Fixed websocket heartbeat to fire even when downstream is saturated (as apparently this timeout applies for the client as well).
* Partially fixed `remove_*` methods not resolving in proxy cases (for self-removal).
> Row delta fixes

- cpp/perspective/CMakeLists.txt
- cpp/perspective/test/CMakeLists.txt
- python/table/.gitignore
- python/table/setup.cfg
- python/table/setup.py
Just a few boilerplate items before python merging:
- a better python make setup for perspective/table
- output perspective test into perspective/tests folder
> simplify python setup.py, add psp_test to python tests

- packages/perspective-phosphor/src/ts/widget.ts
Small enhancement to allow transferring data as column-based. 
for https://github.com/timkpaine/perspective-python/issues/52
> Allow transfer as columns

- packages/perspective-viewer-d3fc/src/js/charts/area.js
- packages/perspective-viewer-d3fc/src/js/charts/bar.js
- packages/perspective-viewer-d3fc/src/js/charts/column.js
- packages/perspective-viewer-d3fc/src/js/charts/heatmap.js
- packages/perspective-viewer-d3fc/src/js/charts/line.js
- packages/perspective-viewer-d3fc/src/js/charts/ohlcCandle.js
- packages/perspective-viewer-d3fc/src/js/charts/xy-scatter.js
- packages/perspective-viewer-d3fc/src/js/charts/y-scatter.js
- packages/perspective-viewer-d3fc/src/js/gridlines/gridlines.js
- packages/perspective-viewer-d3fc/src/js/series/colorStyles.js
> Fixed split-axis y_line charts in D3FC

- packages/perspective-viewer/src/js/viewer.js
> Make "view" attribute of `<perspective-viewer>` backwards compatible

- cpp/perspective/src/cpp/gnode.cpp
- cpp/perspective/src/include/perspective/gnode.h
- packages/perspective-viewer-hypergrid/src/js/perspective-plugin.js
- packages/perspective/src/js/perspective.js
Fixes a small memory leak in `to_format()`, and reduces overall peak memory usage on table load.
> Memory usage fixes

- packages/perspective-jupyterlab/src/ts/widget.ts
- packages/perspective-phosphor/README.md
- packages/perspective-phosphor/src/ts/widget.ts
Fixes:
#620 
#621 
#622 
#623 
#627
> Phosphor and JupyterLab bug and regression fixes

- packages/perspective-viewer/src/html/viewer.html
- packages/perspective-viewer/src/less/default.less
Slightly improve quality of life for the toolbar UI—adds hover styles and clearer titles for buttons and transpose button.
> Add hover styles to copy, download, reset

- packages/perspective-viewer/src/html/viewer.html
- packages/perspective-viewer/src/js/viewer/action_element.js
- packages/perspective-viewer/src/js/viewer/dom_element.js
- packages/perspective-viewer/src/less/viewer.less
Made side panel resizable.  Hopefully supercedes #619
> Made side-panel resizable

- packages/perspective-jupyterlab/package.json
- packages/perspective-jupyterlab/src/config/plugin.config.js
- packages/perspective-jupyterlab/test/js/beforeEachSpec.js
- packages/perspective-jupyterlab/test/js/jest.unit.config.js
- packages/perspective-jupyterlab/test/js/regressions.spec.js
- packages/perspective-jupyterlab/test/js/transform.js
- packages/perspective-jupyterlab/test/js/utils.js
> Fix jlab again

- examples/simple/dataset.html
This example makes it easy to play with various dataset sizes/configurations.
> Added 'dataset' configurable data example

- packages/perspective-viewer-hypergrid/src/js/hypergrid.js
- packages/perspective-viewer-hypergrid/src/js/psp-to-hypergrid.js
- packages/perspective/src/js/perspective.js
- packages/perspective/test/js/to_format.js
> `leaves_only` flag for perspective

- docs/static/css/material.dark.css
- packages/perspective-viewer-d3fc/src/js/charts/area.js
- packages/perspective-viewer-d3fc/src/js/charts/bar.js
- packages/perspective-viewer-d3fc/src/js/charts/candlestick.js
- packages/perspective-viewer-d3fc/src/js/charts/column.js
- packages/perspective-viewer-d3fc/src/js/charts/heatmap.js
- packages/perspective-viewer-d3fc/src/js/charts/line.js
- packages/perspective-viewer-d3fc/src/js/charts/ohlc.js
- packages/perspective-viewer-d3fc/src/js/charts/sunburst.js
- packages/perspective-viewer-d3fc/src/js/charts/treemap.js
- packages/perspective-viewer-d3fc/src/js/charts/xy-scatter.js
- packages/perspective-viewer-d3fc/src/js/charts/y-scatter.js
- packages/perspective-viewer-d3fc/src/js/plugin/plugin.js
- packages/perspective-viewer-d3fc/test/results/results.json
- packages/perspective-viewer-highcharts/src/js/highcharts/draw.js
- packages/perspective-viewer-highcharts/src/js/highcharts/highcharts.js
- packages/perspective-viewer-highcharts/test/js/bar.spec.js
- packages/perspective-viewer-highcharts/test/results/results.json
- packages/perspective-viewer/src/html/viewer.html
- packages/perspective-viewer/src/js/viewer/action_element.js
- packages/perspective-viewer/src/js/viewer/dom_element.js
- packages/perspective-viewer/src/js/viewer/perspective_element.js
- packages/perspective-viewer/src/less/default.less
- packages/perspective-viewer/src/less/row.less
- packages/perspective-viewer/src/themes/material.less
- packages/perspective-viewer/test/js/unit/perspective_element.spec.js
- packages/perspective-viewer/test/js/utils.js
- packages/perspective-viewer/test/results/results.json
Rebases #671 and resolves several issues, such as real-time charting.
> Limit charts

- packages/perspective/src/js/perspective.js
- packages/perspective/test/js/to_format.js
> Readable dates

- .gitignore
- cpp/perspective/src/cpp/emscripten.cpp
- cpp/perspective/src/cpp/gnode.cpp
- cpp/perspective/src/include/perspective/binding.h
- cpp/perspective/src/include/perspective/gnode.h
- packages/perspective/test/js/computed.js
- packages/perspective/test/js/perspective.spec.js
> Computed column partial update

- packages/perspective-viewer/src/js/viewer/perspective_element.js
Fixes event throttling in perspective-viewer to work as originally intended, as well as several fixes to scripts to make this change easier to build and test.
> Throttle fix

- packages/perspective-viewer/src/js/computed_column.js
> New computed functions `pow`, `invert`, `sqrt`, `abs`

- packages/perspective-workspace/src/js/workspace/workspace.js
- packages/perspective-workspace/src/less/menu.less
- packages/perspective-workspace/src/less/tabbar.less
- packages/perspective-workspace/src/less/viewer.less
- packages/perspective-workspace/src/less/widget.less
- packages/perspective-workspace/src/less/workspace.less
- packages/perspective-workspace/test/results/linux.docker.json
Updates styling for viewer-focus effect in `@finos/perspective-workspace`.
> Style fixes for `perspective-workspace`

- packages/perspective-workspace/src/js/workspace/tabbar.js
- packages/perspective-workspace/src/js/workspace/tabbarrenderer.js
- packages/perspective-workspace/src/js/workspace/widget.js
- packages/perspective-workspace/src/less/tabbar.less
- packages/perspective-workspace/test/results/linux.docker.json
> Make `@finos/perspective-workspace` widget title editable by doubleclick

- packages/perspective-webpack-plugin/src/js/psp-worker-loader.js
> Emit source maps for WebWorker.

- examples/promo/src/index.js
- examples/promo/webpack.config.js
- packages/perspective-jupyterlab/package.json
- packages/perspective-jupyterlab/src/config/plugin.config.js
- packages/perspective-jupyterlab/src/config/webpack.config.js
- packages/perspective-jupyterlab/src/ts/plugin.ts
- packages/perspective-jupyterlab/src/ts/psp_widget.ts
- packages/perspective-jupyterlab/src/ts/widget.ts
- packages/perspective-jupyterlab/test/html/resize.html
- packages/perspective-workspace/package.json
- packages/perspective-workspace/src/js/index.js
- packages/perspective-workspace/src/js/workspace/commands.js
- packages/perspective-workspace/src/js/workspace/discrete.js
- packages/perspective-workspace/src/js/workspace/dockpanel.js
- packages/perspective-workspace/src/js/workspace/menu.js
- packages/perspective-workspace/src/js/workspace/tabbar.js
- packages/perspective-workspace/src/js/workspace/tabbarrenderer.js
- packages/perspective-workspace/src/js/workspace/widget.js
- packages/perspective-workspace/src/js/workspace/workspace.js
- packages/perspective-workspace/src/less/menu.less
- packages/perspective-workspace/src/less/workspace.less
- packages/perspective-workspace/test/js/unit/workspace.spec.js
- yarn.lock
> update dependencies to jupyterlab 2.0, phosphor -> lumino

- cpp/perspective/CMakeLists.txt
- cpp/perspective/src/cpp/aggspec.cpp
- cpp/perspective/src/cpp/computed.cpp
- cpp/perspective/src/cpp/computed_function.cpp
- cpp/perspective/src/cpp/emscripten.cpp
- cpp/perspective/src/cpp/gnode_state.cpp
- cpp/perspective/src/cpp/pool.cpp
- cpp/perspective/src/cpp/view.cpp
- cpp/perspective/src/include/perspective/base.h
As per title, adds `-Wall` build flag and fixes relevant warnings.
> Adds -Wall and fixes C++ build warnings

- docs/md/js.md
Adding a small example for update complete events
> add perspective-update-complete event example to js guide

- docs/i18n/en.json
- docs/md/development.md
- docs/md/installation.md
> add some build troubleshooting docs

- python/perspective/perspective/client/client.py
- python/perspective/perspective/client/dispatch.py
- python/perspective/perspective/client/table_api.py
- python/perspective/perspective/manager/manager_internal.py
- python/perspective/perspective/tests/client/__init__.py
- python/perspective/perspective/tests/client/test_client.py
- python/perspective/perspective/tests/tornado_handler/test_tornado_handler.py
- python/perspective/perspective/tornado_handler/tornado_client.py
Fixes for #1199 as per code review.
> `perspective-python` Client fixes

- examples/blocks/src/custom/index.html
- packages/perspective-viewer-datagrid/package.json
- packages/perspective-viewer-datagrid/src/js/plugin.js
- yarn.lock
`regular-table` 0.1.5 has a perspective-specific [fix](https://github.com/jpmorganchase/regular-table/pull/91) in version.
> Upgrade to regular-table 0.1.5 and fix custom-style example

- cpp/perspective/src/cpp/gnode.cpp
- cpp/perspective/src/cpp/sparse_tree.cpp
- python/perspective/perspective/tests/table/test_view.py
> Fix infinite loop bug in 2-sided context

- cpp/perspective/src/cpp/sparse_tree.cpp
- packages/perspective/index.d.ts
- packages/perspective/src/js/config/constants.js
- packages/perspective/test/js/pivots.js
fixes #750 & #1031 
- Abs sum formula rewritten
- Added tests
- Exposed to <perspective-viewer>
> Adding abs sum functionality

- examples/blocks/src/superstore/index.html
- packages/perspective-viewer/src/js/viewer.js
- packages/perspective/src/js/perspective.js
- packages/perspective/test/js/to_format.js
- python/perspective/perspective/table/view.py
- python/perspective/perspective/tests/table/test_to_format.py
> Fix Date/Time formatting in `perspective-viewer` CSV output

- packages/perspective-viewer/src/less/viewer.less
- packages/perspective-viewer/src/themes/material.dark.less
> Fixes style issue with <select> dark theme on Windows

- docs/logo.js
- docs/package.json
- docs/pages/en/index.js
- docs/siteConfig.js
- docs/static/js/animation.js
- packages/perspective-bench/package.json
- packages/perspective-test/package.json
- packages/perspective-webpack-plugin/package.json
- scripts/build_js.js
- scripts/setup.js
Updates to the docs site, which are already deployed on `gh-pages` but not reflected in the a release branch yet.  Also fixes the build script when a `PACKAGE` is targetted for a _mystery reason_ .. by reverting to an older glob syntax.
> Docs site updates

- azure-pipelines.yml
resolve issues raised in https://github.com/finos/perspective/issues/1337
> Add nightly complete builds

- cmake/modules/FindPybind.cmake
Should be str not int, presume this causes pybind to always git download
> Getting pybind version number always fails

- rust/perspective-vieux/src/rust/column_style.rs
Small fix to make the column style menu's placement responsive with respect to the browser's viewport.
> Responsive column style menu

- packages/perspective/src/js/perspective.js
- packages/perspective/test/js/expressions.js
- packages/perspective/test/js/expressions/parsing.js
- python/perspective/perspective/table/_utils.py
> Fixes `bucket()` computed function validation

- README.md
- examples/blocks/gists.json
- examples/blocks/src/covid/.block
- examples/blocks/src/covid/README.md
- examples/blocks/src/covid/index.html
Data sourced from https://covidtracking.com/
On bl.ocks https://bl.ocks.org/texodus/e074d7d9e5783e680d35f565d2b4b32
> New example

- examples/blocks/src/custom/custom_plugin.js
- packages/perspective-jupyterlab/src/js/psp_widget.js
- packages/perspective-viewer-datagrid/src/js/plugin.js
- rust/perspective-viewer/src/rust/custom_elements/viewer.rs
- rust/perspective-viewer/src/ts/viewer.ts
- tools/perspective-test/src/js/index.js
> Add `wait_for_table` flag to `getTable()`

- packages/perspective-jupyterlab/src/less/index.less
- rust/perspective-viewer/src/themes/material-dense.dark.less
- rust/perspective-viewer/src/themes/material-dense.less
- rust/perspective-viewer/src/themes/material.dark.less
- rust/perspective-viewer/src/themes/material.less
> `PerspectiveWidget()` dialog theme fix

- python/perspective/perspective/src/fill.cpp
- python/perspective/perspective/tests/table/test_table_limit.py
- rust/perspective-viewer/build.js
> Fix partial-updates on tables with `limit` set for python

- azure-pipelines.yml
Karmic retribution for not running a full azure build before merging these wheel changes originally ..
> Fix Azure windows wheel step

- examples/react/src/index.tsx
- packages/perspective-webpack-plugin/index.js
- packages/perspective/src/js/perspective.node.js
- rust/perspective-viewer/build.js
- rust/perspective-viewer/package.json
- rust/perspective-viewer/src/rust/js/monaco.rs
- rust/perspective-viewer/tsconfig.json
> Emit `.d.ts` declaration files for `@finos/perspective-viewer`

- packages/perspective-viewer-d3fc/src/js/charts/treemap.js
- packages/perspective-viewer-d3fc/src/js/series/treemap/treemapSeries.js
- packages/perspective-viewer-d3fc/src/js/series/treemap/treemapTransitions.js
- packages/perspective-viewer-d3fc/src/js/tooltip/selectionData.js
- packages/perspective-viewer-d3fc/src/js/tooltip/selectionEvent.js
> D3FC Treemap bug fixes

- rust/perspective-viewer/src/rust/components/filter_item.rs
- rust/perspective-viewer/src/rust/utils/datetime.rs
> `date` and `datetime` filter bug fixes and support for non-Chrome browsers

- cpp/perspective/src/cpp/arrow_loader.cpp
- python/perspective/perspective/include/perspective/python/table.h
- python/perspective/perspective/src/table.cpp
- python/perspective/perspective/tests/core/test_async.py
- scripts/test_python.js
> Fix async mode segfault on `.load()` with indexed Arrow

- packages/perspective-viewer-d3fc/package.json
- packages/perspective-viewer-datagrid/package.json
- packages/perspective-workspace/package.json
- packages/perspective/package.json
- rust/perspective-viewer/package.json
This PR add `main` field in package json for `@finos/perspective` , `@finos/perspective-viewer`, `@finos/perspective-viewer-datagrid` and `@finos/perspective-viewer-d3fc`.
> Add `main` field to package json

- azure-pipelines.yml
- cmake/arrow/CMakeLists.txt
- cmake/flatbuffers.txt.in
- cmake/modules/FindFlatbuffers.cmake
Removes `flatbuffers` system dependency and re-enables OSX/WIndows python builds.
> Fix flatbuffers

- packages/perspective-viewer-d3fc/build.js
- packages/perspective-viewer-datagrid/build.js
- packages/perspective-viewer-datagrid/index.d.ts
- packages/perspective-viewer-datagrid/package.json
> Export `perspective-viewer-datagrid` types

- packages/perspective-jupyterlab/src/js/psp_widget.js
- packages/perspective-jupyterlab/src/js/view.js
- packages/perspective-jupyterlab/test/jupyter/widget.spec.js
- packages/perspective-jupyterlab/test/results/results.json
> Fix JLab `settings` flicker

- rust/perspective-viewer/build.js
> Fix `debug` build script

- packages/perspective-viewer-datagrid/src/less/toolbar.less
- rust/perspective-viewer/src/less/status-bar.less
- rust/perspective-viewer/src/themes/material.less
Fixes alignment of theme dropdown and scroll lock/edit label
> Make toolbar icons configurable

- packages/perspective-viewer-d3fc/src/less/chart.less
Fixed version of #1871
Fixes #1869
> Changed default color label style for charts with multiple secondary axii

- README.md
- cpp/perspective/src/cpp/traversal.cpp
- python/perspective/perspective/tests/table/test_view.py
> Fix expand/collapse on first row of ctx2

- packages/perspective-viewer-datagrid/src/js/cell_flash.js
- packages/perspective-viewer-datagrid/src/js/regular_table_handlers.js
- packages/perspective-viewer-datagrid/src/js/sorting.js
- packages/perspective-viewer-datagrid/src/less/regular_table.less
- rust/perspective-viewer/src/rust/components/number_column_style.rs
> Add `pulse` numeric column background mode

- docs/js/concepts.js
- docs/md/expressions.md
- docs/sidebars.json
- rust/perspective-viewer/src/less/column-selector.less
A fork of #1848 with review comments fixed
> Expression Docs

- .github/workflows/build.yml
[fail](https://github.com/finos/perspective/runs/7283232392?check_suite_focus=true)
> Fix Python sdist CI build 

- python/perspective/setup.py
> Upper bound for `ipywidgets`

- rust/perspective-viewer/src/rust/components/filter_item.rs
- rust/perspective-viewer/test/results/results.json
> Add `not in` filter to valid string type filters in `<perspective-viewer>`

- packages/perspective-viewer-d3fc/src/js/axis/linearAxis.js
> Resize labels to avoid overlap

- packages/perspective-viewer-d3fc/src/js/plugin/plugin.js
- packages/perspective-viewer-d3fc/src/js/series/colorStyles.js
- packages/perspective-viewer-d3fc/src/js/series/pointSeriesCanvas.js
- rust/perspective-viewer/Cargo.lock
- rust/perspective-viewer/Cargo.toml
* Fixes a CSS whitespace issue which causes (at least) column selector column names to overflow their containers.
* Fixes a X/Y scatter labels to account for bubble size.
> Fix CSS and Scatter Chart positioning bugs

- packages/perspective-viewer-d3fc/src/js/series/pointSeriesCanvas.js
> Improved point label position

- packages/perspective-workspace/test/results/results.json
Fixes [this error](https://github.com/finos/perspective/actions/runs/3798849548/jobs/6461101749#step:21:1767) which annoyingly manifested with a chromium update.
> Fix test regression in chrome

- packages/perspective-cli/package.json
- packages/perspective-cli/src/html/index.html
- packages/perspective/src/js/perspective.node.js
> Add `@finos/perspective-viewer-openlayers` plugin to CLI package

- packages/perspective-viewer-d3fc/src/js/charts/xy-line.js
- packages/perspective-viewer-d3fc/test/js/integration/xy-line.spec.js
- packages/perspective-viewer-d3fc/test/results/results.json
> Fix legend on X/Y line chart

- package.json
- packages/perspective/src/js/perspective.node.js
- packages/perspective/src/js/websocket/client.js
- packages/perspective/test/js/remote.spec.js
- yarn.lock
> Fix ping loop state, make node server `close` method async

- .github/workflows/build.yml
xref: https://github.com/actions/runner/issues/2224
Microsoft / GitHub's docs suck and provided inaccurate information: https://github.com/actions/runner/issues/2224#issuecomment-1296341529
> Run yarn cache path commands in bash shell

- README.md
> link for dark mode logo in readme

- python/perspective/perspective/client/aiohttp.py
- python/perspective/perspective/client/tornado.py
- python/perspective/perspective/client/websocket.py
> pass through websocket connection arguments in python websocket clients, normalize max message size and ensure set for aiohttp

- packages/perspective-viewer-d3fc/src/js/tooltip/selectionData.js
> Handle zero values in line plots

- python/perspective/perspective/table/_accessor.py
- python/perspective/perspective/tests/table/test_table.py
- python/perspective/perspective/tests/table/test_table_numpy.py
resolved #1717 
**Before**
**After**
**Some extra tests**
> Coerce to float64 when user tries to pass in float32 as float64 - fixes #1717

- python/perspective/perspective/tests/table/test_update.py
#1819 Null value updates do not propagate to perspective viewer
BEFORE:
AFTER:
> Add skip test: _update_with_missing_or_null_values

- .github/workflows/build.yml
- cmake/Pybind.txt.in
- scripts/publish.js
https://github.com/finos/perspective/actions/runs/5061975244
> Add Python 3.11 support

- .github/workflows/build.yml
https://github.com/pyodide/pyodide/pull/3971
https://github.com/numpy/numpy/pull/24091
> Fix build regression in python dependency

- .github/workflows/build.yml
Removes the docs build from CI.
> Remove docs build from CI

- packages/perspective-viewer-d3fc/src/ts/axis/axisFactory.ts
- packages/perspective-viewer-d3fc/src/ts/axis/linearAxis.ts
- packages/perspective-viewer-d3fc/src/ts/legend/colorRangeLegend.ts
- packages/perspective-viewer-d3fc/test/js/nice.spec.ts
Rebased #2522 (mentions #1610)
> Update axis tick labels to accomodate small ranges

- .github/workflows/build.yaml
- docs/docs/js.md
- rust/perspective-viewer/Cargo.toml
- rust/perspective-viewer/src/less/status-bar.less
- rust/perspective-viewer/src/themes/icons.less
- rust/perspective-viewer/src/themes/pro-dark.less
- rust/perspective-viewer/src/themes/pro.less
- rust/perspective-viewer/src/themes/solarized-dark.less
* Fixes pyodide dist (cherry-picked from #2710)
* Fixes perspective-workspace icons not inlining correctly
> Fix missing icons

- cpp/perspective/src/cpp/gnode_state.cpp
- cpp/perspective/src/include/perspective/parallel_for.h
This is just cleaning up some accidental changes I left in the old PR to make stepping through the code in LLDB easier. Sorry!
> Fix parallel_for and cleanup commented out code.

- rust/perspective-js/test/js/leaks.spec.js
- rust/perspective-viewer/src/rust/renderer.rs
- rust/perspective-viewer/test/js/viewnotfound.spec.js
This is a rebased and fixed version fo #3039
> Fix concurrent `HTMLPerspectiveViewerElement::load` error
